### ISSUE TITLE
[bug] DeprecationWarning's crash Taichi

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1130]
**Describe the bug**
Please see https://github.com/yuanming-hu/difftaichi/issues/26

**Log/Screenshots**
```
Traceback (most recent call last):
  File "tmp.py", line 11, in <module>
    test()
  File "/home/yuanming/repos/taichi/python/taichi/lang/kernel.py", line 533, in wrapped
    return primal(*args, **kwargs)
  File "/home/yuanming/repos/taichi/python/taichi/lang/kernel.py", line 463, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/home/yuanming/repos/taichi/python/taichi/lang/kernel.py", line 343, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/home/yuanming/repos/taichi/python/taichi/lang/kernel.py", line 340, in taichi_ast_generator
    compiled()
  File "tmp.py", line 7, in test
    a = ti.sqr(b)
  File "/home/yuanming/repos/taichi/python/taichi/lang/util.py", line 174, in wrapped
    raise DeprecationWarning(msg)
DeprecationWarning: ti.sqr(x) is deprecated, please use x ** 2 instead
```
**(program exists)**

**To Reproduce**
```python
import taichi as ti
ti.init()

@ti.kernel
def test():
    b = 1
    a = ti.sqr(b)
    # a = b ** 2


test()

print('Success!')
```

**Comment by archibate** [comment]
Sorry, my fault, I should changes this back before merge, fixing in #1121.
