### ISSUE TITLE
[Bug] [IR] ti.sqrt(3) result in an error

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1172]
**Describe the bug**
I found that when `ti.sqrt` is given an integer as operand, LLVM complains it could not find `sqrt.i32`.
i.e. `ti.sqrt(3.0)` is fine, `ti.sqrt(3)` is an error.

**To Reproduce**
```py
import taichi as ti

ti.init(arch=ti.cpu)

@ti.kernel
def main():
    print(ti.sqrt(3))

main()
```

**Log/Screenshots**

```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-gy2kb0jx
[Taichi] <dev mode>, supported archs: [cpu, cuda, opengl], commit 8659d61c, python 3.8.2
Intrinsic has incorrect return type!
i32 (i32)* @llvm.sqrt.i32
[E 06/07/20 12:38:10.492] [codegen_llvm.cpp:finalize_offloaded_task_function@1235] !llvm::verifyFunction(*func, &errs())


***********************************
* Taichi Compiler Stack Traceback *                                                          
***********************************                                                          
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)                                  
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::CodeGenLLVM::finalize_offloaded_task_function()                                                                                        
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::CodeGenLLVMCPU::visit(taichi::lang::OffloadedStmt*)                                                                                    
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::CodeGenLLVM::visit(taichi::lang::Block*)  
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::CodeGenLLVM::emit_to_module()             
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::CodeGenLLVM::gen()                        
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::CodeGenCPU::codegen()                     
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::KernelCodeGen::compile()                  
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::Program::compile(taichi::lang::Kernel&)   
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::Kernel::compile()                         
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::Kernel::operator()()                      
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::ConstantFold::jit_evaluate_unary_op(taichi::lang::TypedConstant&, taichi::lang::UnaryOpStmt*, taichi::lang::TypedConstant const&)      
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::ConstantFold::visit(taichi::lang::UnaryOpStmt*)                                                                                        
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::BasicStmtVisitor::visit(taichi::lang::Block*)                                                                                          
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::irpass::constant_fold(taichi::lang::IRNode*)                                                                                           
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::irpass::full_simplify(taichi::lang::IRNode*, taichi::lang::Kernel*)                                                                    
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::irpass::compile_to_offloads(taichi::lang::IRNode*, taichi::lang::CompileConfig const&, bool, bool, bool, bool, bool)
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::Kernel::lower(bool)
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::Program::compile(taichi::lang::Kernel&)
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::Kernel::compile()
/tmp/taichi-gy2kb0jx/taichi_core.so: taichi::lang::Kernel::operator()()
/tmp/taichi-gy2kb0jx/taichi_core.so(+0x71fd14) [0x7fe8adb12d14]
/tmp/taichi-gy2kb0jx/taichi_core.so(+0x69b466) [0x7fe8ada8e466]
/usr/lib/libpython3.8.so.1.0: PyCFunction_Call
/usr/lib/libpython3.8.so.1.0: _PyObject_MakeTpCall
/usr/lib/libpython3.8.so.1.0(+0xfeb1d) [0x7fe8bd5d7b1d]
/usr/lib/libpython3.8.so.1.0: PyObject_Call
/usr/lib/libpython3.8.so.1.0(+0xb121b) [0x7fe8bd58a21b]
/usr/lib/libpython3.8.so.1.0: _PyObject_MakeTpCall
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall
/usr/lib/libpython3.8.so.1.0: PyObject_Call
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall
/usr/lib/libpython3.8.so.1.0: _PyObject_FastCallDict
/usr/lib/libpython3.8.so.1.0: _PyObject_Call_Prepend
/usr/lib/libpython3.8.so.1.0(+0x23d0e9) [0x7fe8bd7160e9]
/usr/lib/libpython3.8.so.1.0: PyObject_Call
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: PyEval_EvalCode
/usr/lib/libpython3.8.so.1.0(+0x2668c8) [0x7fe8bd73f8c8]
/usr/lib/libpython3.8.so.1.0(+0x26aba3) [0x7fe8bd743ba3]
/usr/lib/libpython3.8.so.1.0: PyRun_FileExFlags
/usr/lib/libpython3.8.so.1.0: PyRun_SimpleFileExFlags
/usr/lib/libpython3.8.so.1.0: Py_RunMain
/usr/lib/libpython3.8.so.1.0: Py_BytesMain
/usr/lib/libc.so.6: __libc_start_main
python(_start+0x2e) [0x559c4690905e]

Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "reset.my.py", line 9, in <module>
    main()
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 530, in wrapped
    return primal(*args, **kwargs)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 461, in __call__
    return self.compiled_functions[key](*args)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 425, in func__
    t_kernel()
RuntimeError: [codegen_llvm.cpp:finalize_offloaded_task_function@1235] !llvm::verifyFunction(*func, &errs())
```

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**

**Comment by xumingkuan** [comment]
Thanks for proposing this! Will fix it soon.
