### ISSUE TITLE
[test] Crashed test workers don't get re-run by rerunfailures

### ISSUE THREAD

**Issue by rexwangcc** [taichi-dev/taichi#1249]
**Describe the bug**
When running `ti test` with multiple threads, crashed workers don't get re-run and thus lead to test failures.

**Log/Screenshots**
`ti test -r3`:

<img width="873" alt="Screen Shot 2020-06-14 at 10 50 54 PM" src="https://user-images.githubusercontent.com/14366016/84613576-87335280-ae91-11ea-97cf-dd022d9c04c9.png">

**To Reproduce**
Make sure `rerunfailures-9.0, xdist-1.32.0` are available to Pytest and keep running `ti test -r3` until you will see `node down: Not properly terminated` and then no re-run tests are counted in the final report. 

This is a known issue with `pytest-xdist`: https://github.com/pytest-dev/pytest-xdist/issues/466 and no fixes are in-place yet. This is not a problem with single-threaded tests (`ti test -r3 -t0`). Opening this issue just for a record in case this start to bother our CI runners, not expecting anything useful could be done on Taichi side, except always using single-threaded tests by deafult.

**Comment by GabrielBlondeau-Kirby** [comment]
I think I have kind of the same issue :cry: 

```
============================= test session starts ==============================
00:42
platform linux -- Python 3.6.10, pytest-6.0.0, py-1.8.2, pluggy-0.13.1
00:42
rootdir: /home/rof/src/github.com/videoClerk/backend, configfile: pytest.ini
00:42
plugins: rerunfailures-9.0, xdist-1.27.0, forked-1.1.3, cov-2.6.1, celery-4.4.0rc4
00:42

gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / [...] / gw62 [80] / gw63 [80]

00:42
sss....s...................................................s........ss.s [ 90%]
00:42
...s...!!!!!!!!!!!!!!!!!!!! <ExceptionInfo TypeError("__init__() got an unexpected keyword argument 'filelocrepr'",) tblen=3>
00:42
INTERNALERROR> Traceback (most recent call last):
00:42
INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 327, in process_from_remote
00:42
INTERNALERROR>     rep = unserialize_report(eventname, kwargs["data"])
00:42
INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 434, in unserialize_report
00:42
INTERNALERROR>     return runner.TestReport(**assembled_report(reportdict))
00:42
INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 414, in assembled_report
00:42
INTERNALERROR>     style=data["style"],
00:42
INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'filelocrepr'
00:42
[gw2] node down: <ExceptionInfo TypeError("__init__() got an unexpected keyword argument 'filelocrepr'",) tblen=3>
00:42
FReplacing crashed worker gw2
00:42

gw0 [80] / gw1 [80] / [...] / gw63 [80]!!!!!!!!!!!!!!!!!!!! <ExceptionInfo TypeError("__init__() got an unexpected keyword argument 'filelocrepr'",) tblen=3>
00:42
INTERNALERROR> Traceback (most recent call last):
00:42
INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 327, in process_from_remote
00:42
INTERNALERROR>     rep = unserialize_report(eventname, kwargs["data"])
00:42
INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 434, in unserialize_report
00:42
INTERNALERROR>     return runner.TestReport(**assembled_report(reportdict))
00:42
INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 414, in assembled_report
00:42
INTERNALERROR>     style=data["style"],
00:42
INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'filelocrepr'
00:42
[gw2] node down: <ExceptionInfo TypeError("__init__() got an unexpected keyword argument 'filelocrepr'",) tblen=3>
00:42
Replacing crashed worker gw2
```

**Comment by pratibha-patil** [comment]
> I think I have kind of the same issue 😢
> 
> ```
> ============================= test session starts ==============================
> 00:42
> platform linux -- Python 3.6.10, pytest-6.0.0, py-1.8.2, pluggy-0.13.1
> 00:42
> rootdir: /home/rof/src/github.com/project, configfile: pytest.ini
> 00:42
> plugins: rerunfailures-9.0, xdist-1.27.0, forked-1.1.3, cov-2.6.1, celery-4.4.0rc4
> 00:42
> 
> gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / [...] / gw62 [80] / gw63 [80]
> 
> 00:42
> sss....s...................................................s........ss.s [ 90%]
> 00:42
> ...s...!!!!!!!!!!!!!!!!!!!! <ExceptionInfo TypeError("__init__() got an unexpected keyword argument 'filelocrepr'",) tblen=3>
> 00:42
> INTERNALERROR> Traceback (most recent call last):
> 00:42
> INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 327, in process_from_remote
> 00:42
> INTERNALERROR>     rep = unserialize_report(eventname, kwargs["data"])
> 00:42
> INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 434, in unserialize_report
> 00:42
> INTERNALERROR>     return runner.TestReport(**assembled_report(reportdict))
> 00:42
> INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 414, in assembled_report
> 00:42
> INTERNALERROR>     style=data["style"],
> 00:42
> INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'filelocrepr'
> 00:42
> [gw2] node down: <ExceptionInfo TypeError("__init__() got an unexpected keyword argument 'filelocrepr'",) tblen=3>
> 00:42
> FReplacing crashed worker gw2
> 00:42
> 
> gw0 [80] / gw1 [80] / [...] / gw63 [80]!!!!!!!!!!!!!!!!!!!! <ExceptionInfo TypeError("__init__() got an unexpected keyword argument 'filelocrepr'",) tblen=3>
> 00:42
> INTERNALERROR> Traceback (most recent call last):
> 00:42
> INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 327, in process_from_remote
> 00:42
> INTERNALERROR>     rep = unserialize_report(eventname, kwargs["data"])
> 00:42
> INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 434, in unserialize_report
> 00:42
> INTERNALERROR>     return runner.TestReport(**assembled_report(reportdict))
> 00:42
> INTERNALERROR>   File "/home/rof/.pyenv/versions/3.6.10/lib/python3.6/site-packages/xdist/workermanage.py", line 414, in assembled_report
> 00:42
> INTERNALERROR>     style=data["style"],
> 00:42
> INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'filelocrepr'
> 00:42
> [gw2] node down: <ExceptionInfo TypeError("__init__() got an unexpected keyword argument 'filelocrepr'",) tblen=3>
> 00:42
> Replacing crashed worker gw2
> ```

I am also facing same issue with pytest 6.2.5  and 7.0.0 and pytest-xdist==1.27.0 /latest
