### ISSUE TITLE
CUDA Error CUDA_ERROR_NOT_FOUND: named symbol not found while calling module_get_function

### ISSUE THREAD

**Issue by qmdxcube** [taichi-dev/taichi#1280]
Windows 10 64bit + Python 3.7.7 + GeForce RTX 2060 + CUDA 11.0 +Sublime Text
taichi installation file: taichi-0.6.11-cp37-cp37m-win_amd64.whl (17.1 MB)
If I run the CUDA sample codes using Visuo Studio, all is OK. But when I run the examples provided with taichi, following issue appeared. When the parameter arch is changed from ti.cuda to ti.cpu, the code can be run normally. How to fix this problem? Thank you very much.

[Taichi] mode=release
[Taichi] version 0.6.11, supported archs: [cpu, cuda, opengl], commit 762aca58, python 3.7.7
[E 06/19/20 15:34:58.823] [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void * *,void *,char const *>::operator ()@68] CUDA Error CUDA_ERROR_NOT_FOUND: named symbol not found while calling module_get_function (cuModuleGetFunction)

[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m* Taichi Compiler Stack Traceback *
[0m[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m0x7ffac9be8cf1: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9cb507a: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9d61df3: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9d65203: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9d65110: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9d631b8: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9b25b6a: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9b33abd: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9b34b3b: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9aaf602: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9b7bf69: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9b37f46: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffac9a8d61b: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffaccf3e06d: [0m[38;2;255;000;000mPyMethodDef_RawFastCallKeywords[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3db53: [0m[38;2;255;000;000mPyFunction_FastCallDict[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf453b8: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3e3ac: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3dc0c: [0m[38;2;255;000;000mPyFunction_FastCallDict[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf453b8: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3d624: [0m[38;2;255;000;000mPyFunction_FastCallDict[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf48270: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3e3ac: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3d70f: [0m[38;2;255;000;000mPyFunction_FastCallDict[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf305c5: [0m[38;2;255;000;000mPyObject_SetItem[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf46383: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3d624: [0m[38;2;255;000;000mPyFunction_FastCallDict[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf48270: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3e3ac: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3d70f: [0m[38;2;255;000;000mPyFunction_FastCallDict[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf305c5: [0m[38;2;255;000;000mPyObject_SetItem[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf46383: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf3e3ac: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf4b573: [0m[38;2;255;000;000mPyEval_EvalCodeEx[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf4b4d1: [0m[38;2;255;000;000mPyEval_EvalCode[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf4b47b: [0m[38;2;255;000;000mPyArena_Free[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffacd0b4201: [0m[38;2;255;000;000mPyRun_FileExFlags[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffacd0b499d: [0m[38;2;255;000;000mPyRun_SimpleFileExFlags[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffacd0b40df: [0m[38;2;255;000;000mPyRun_AnyFileExFlags[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffacd0014ac: [0m[38;2;255;000;000mPy_UnixMain[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffacd001553: [0m[38;2;255;000;000mPy_UnixMain[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf71270: [0m[38;2;255;000;000mPyErr_NoMemory[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf1107b: [0m[38;2;255;000;000mPy_Main[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ffaccf11056: [0m[38;2;255;000;000mPy_Main[0m[38;2;255;000;255m in python37.dll
[0m[38;2;255;000;255m0x7ff63ef6126d: [0m[38;2;255;000;000mUnknown Function[0m[38;2;255;000;255m in python.exe
[0m[38;2;255;000;255m0x7ffb0fee7bd4: [0m[38;2;255;000;000mBaseThreadInitThunk[0m[38;2;255;000;255m in KERNEL32.DLL
[0m[38;2;255;000;255m0x7ffb10face71: [0m[38;2;255;000;000mRtlUserThreadStart[0m[38;2;255;000;255m in ntdll.dll
[0m[38;2;255;165;000m
Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
[0mTraceback (most recent call last):
  File "G:\Research\Large-scale TO\taichi-master\examples\mpm88.py", line 76, in <module>
    x[i] = [random.random() * 0.4 + 0.2, random.random() * 0.4 + 0.2]
  File "D:\Python37\lib\site-packages\taichi\lang\util.py", line 209, in wrapped
    return func(*args, **kwargs)
  File "D:\Python37\lib\site-packages\taichi\lang\matrix.py", line 354, in __setitem__
    self(i, j)[index] = item[i][j]
  File "D:\Python37\lib\site-packages\taichi\lang\util.py", line 209, in wrapped
    return func(*args, **kwargs)
  File "D:\Python37\lib\site-packages\taichi\lang\expr.py", line 43, in __setitem__
    self.materialize_layout_callback()
  File "D:\Python37\lib\site-packages\taichi\lang\impl.py", line 177, in materialize
    taichi_lang_core.layout(layout)
RuntimeError: [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void * *,void *,char const *>::operator ()@68] CUDA Error CUDA_ERROR_NOT_FOUND: named symbol not found while calling module_get_function (cuModuleGetFunction)
[Finished in 1.3s with exit code 1]
[shell_cmd: python -u "G:\Research\Large-scale TO\taichi-master\examples\mpm88.py"]
[dir: G:\Research\Large-scale TO\taichi-master\examples]
[path: D:\CUDA\v11.0\bin;D:\CUDA\v11.0\libnvvp;;D:\Python37\Scripts\;D:\Python37\;D:\MSC.Software\Patran_x64\20190\bin;D:\SIMULIA\Commands;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\matlab2019a\runtime\win64;D:\matlab2019a\bin;D:\matlab2019a\polyspace\bin;D:\CTEX\UserData\miktex\bin;D:\CTEX\MiKTeX\miktex\bin;D:\CTEX\CTeX\ctex\bin;D:\CTEX\CTeX\cct\bin;D:\CTEX\CTeX\ty\bin;D:\CTEX\Ghostscript\gs9.05\bin;D:\CTEX\GSview\gsview;D:\CTEX\WinEdt;D:\PTC\bin;D:\PTC\mech\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.1.0\;C:\Users\123\AppData\Local\Microsoft\WindowsApps;]

**Comment by archibate** [comment]
Thank for reporting! But note that the issue is already solved in #1271, and will be soon released in v0.6.12 this Sunday. Before that, you may use `ti.init(ti.opengl)` to walk around.

**Comment by qmdxcube** [comment]
Thanks a lot for your reply. I look forward to the release of v0.6.12.
