### ISSUE TITLE
Failed to print variables for debugging

### ISSUE THREAD

**Issue by XunZhan** [taichi-dev/taichi#1323]
**Bug Description**
I was trying to print out a vector in the examples/pbf.2dpy but got errors for it. The vector (velocities) is declared outside the kernel (function update_velocities()) while being updated inside the kernel. Constant variables can be printed inside the kernel but the vector can't.

**Log/Screenshots/Reproduce**
I added some code under function update_velocities (line 253) and make it:
```Python
@ti.kernel
def update_velocities():
    for i in positions:
        velocities[i] = (positions[i] - old_positions[i]) / time_delta
    print(velocities)
```

Then I got the following errors:
```Python
* Taichi Core - Stack Traceback *                             
==========================================================================================
|                       Module |  Offset | Function                                      |
|----------------------------------------------------------------------------------------|
*               taichi_core.so |     110 | taichi::Logger::error(std::__1::basic_string< |
                                         | char, std::__1::char_traits<char>, std::__1:: |
                                         | allocator<char> > const&, bool)               |
*               taichi_core.so |     786 | taichi::lang::load_if_ptr(taichi::lang::Expr  |
                                         | const&)                                       |
*               taichi_core.so |      68 | std::__1::unique_ptr<taichi::lang::FrontendEv |
                                         | alStmt, std::__1::default_delete<taichi::lang |
                                         | ::FrontendEvalStmt> > taichi::lang::Stmt::mak |
                                         | e_typed<taichi::lang::FrontendEvalStmt, taich |
                                         | i::lang::Expr const&>(taichi::lang::Expr cons |
                                         | t&)                                           |
*               taichi_core.so |     163 | taichi::lang::Expr::eval() const              |
*               taichi_core.so |     321 | taichi::lang::Expr::operator=(taichi::lang::E |
                                         | xpr const&)                                   |
*               taichi_core.so |     116 | bool pybind11::detail::variant_caster<std::__ |
                                         | 1::variant<taichi::lang::Expr, std::__1::basi |
                                         | c_string<char, std::__1::char_traits<char>, s |
                                         | td::__1::allocator<char> > > >::load_alternat |
                                         | ive<taichi::lang::Expr, std::__1::basic_strin |
                                         | g<char, std::__1::char_traits<char>, std::__1 |
                                         | ::allocator<char> > >(pybind11::handle, bool, |
                                         |  pybind11::detail::type_list<taichi::lang::Ex |
                                         | pr, std::__1::basic_string<char, std::__1::ch |
                                         | ar_traits<char>, std::__1::allocator<char> >  |
                                         | >)                                            |
*               taichi_core.so |     381 | pybind11::detail::list_caster<std::__1::vecto |
                                         | r<std::__1::variant<taichi::lang::Expr, std:: |
                                         | __1::basic_string<char, std::__1::char_traits |
                                         | <char>, std::__1::allocator<char> > >, std::_ |
                                         | _1::allocator<std::__1::variant<taichi::lang: |
                                         | :Expr, std::__1::basic_string<char, std::__1: |
                                         | :char_traits<char>, std::__1::allocator<char> |
                                         |  > > > >, std::__1::variant<taichi::lang::Exp |
                                         | r, std::__1::basic_string<char, std::__1::cha |
                                         | r_traits<char>, std::__1::allocator<char> > > |
                                         |  >::load(pybind11::handle, bool)              |
*               taichi_core.so |      57 | void pybind11::cpp_function::initialize<taich |
                                         | i::export_lang(pybind11::module&)::$_48, void |
                                         | , std::__1::vector<std::__1::variant<taichi:: |
                                         | lang::Expr, std::__1::basic_string<char, std: |
                                         | :__1::char_traits<char>, std::__1::allocator< |
                                         | char> > >, std::__1::allocator<std::__1::vari |
                                         | ant<taichi::lang::Expr, std::__1::basic_strin |
                                         | g<char, std::__1::char_traits<char>, std::__1 |
                                         | ::allocator<char> > > > >, pybind11::name, py |
                                         | bind11::scope, pybind11::sibling>(taichi::exp |
                                         | ort_lang(pybind11::module&)::$_48&&, void (*) |
                                         | (std::__1::vector<std::__1::variant<taichi::l |
                                         | ang::Expr, std::__1::basic_string<char, std:: |
                                         | __1::char_traits<char>, std::__1::allocator<c |
                                         | har> > >, std::__1::allocator<std::__1::varia |
                                         | nt<taichi::lang::Expr, std::__1::basic_string |
                                         | <char, std::__1::char_traits<char>, std::__1: |
                                         | :allocator<char> > > > >), pybind11::name con |
                                         | st&, pybind11::scope const&, pybind11::siblin |
                                         | g const&)::'lambda'(pybind11::detail::functio |
                                         | n_call&)::__invoke(pybind11::detail::function |
                                         | _call&)                                       |
*               taichi_core.so |    4075 | pybind11::cpp_function::dispatcher(_object*,  |
                                         | _object*, _object*)                           |
*                      Python3 |     722 | (null)                                        |
*                      Python3 |      41 | (null)                                        |
*                      Python3 |     656 | (null)                                        |
*                      Python3 |   28360 | (null)                                        |
*                      Python3 |    2888 | (null)                                        |
*                      Python3 |     455 | (null)                                        |
*                      Python3 |   29134 | (null)                                        |
*                      Python3 |    2888 | (null)                                        |
*                      Python3 |     228 | (null)                                        |
*                      Python3 |     780 | (null)                                        |
*                      Python3 |   28360 | (null)                                        |
*                      Python3 |     237 | (null)                                        |
*                      Python3 |     780 | (null)                                        |
*                      Python3 |   28520 | (null)                                        |
*                      Python3 |    2888 | (null)                                        |
*                      Python3 |     455 | (null)                                        |
*               taichi_core.so |      43 | pybind11::object pybind11::detail::object_api |
                                         | <pybind11::handle>::operator()<(pybind11::ret |
                                         | urn_value_policy)1>() const                   |
*               taichi_core.so |      34 | std::__1::__function::__func<pybind11::detail |
                                         | ::type_caster<std::__1::function<void ()>, vo |
                                         | id>::load(pybind11::handle, bool)::func_wrapp |
                                         | er, std::__1::allocator<pybind11::detail::typ |
                                         | e_caster<std::__1::function<void ()>, void>:: |
                                         | load(pybind11::handle, bool)::func_wrapper>,  |
                                         | void ()>::operator()()                        |
*               taichi_core.so |     355 | taichi::lang::Kernel::Kernel(taichi::lang::Pr |
                                         | ogram&, std::__1::function<void ()>, std::__1 |
                                         | ::basic_string<char, std::__1::char_traits<ch |
                                         | ar>, std::__1::allocator<char> >, bool)       |
*               taichi_core.so |     144 | taichi::lang::Program::kernel(std::__1::funct |
                                         | ion<void ()> const&, std::__1::basic_string<c |
                                         | har, std::__1::char_traits<char>, std::__1::a |
                                         | llocator<char> > const&, bool)                |
*               taichi_core.so |     204 | void pybind11::cpp_function::initialize<taich |
                                         | i::export_lang(pybind11::module&)::$_14, taic |
                                         | hi::lang::Kernel&, taichi::lang::Program::Ker |
                                         | nelProxy*, std::__1::function<void ()> const& |
                                         | , pybind11::name, pybind11::is_method, pybind |
                                         | 11::sibling, pybind11::return_value_policy>(t |
                                         | aichi::export_lang(pybind11::module&)::$_14&& |
                                         | , taichi::lang::Kernel& (*)(taichi::lang::Pro |
                                         | gram::KernelProxy*, std::__1::function<void ( |
                                         | )> const&), pybind11::name const&, pybind11:: |
                                         | is_method const&, pybind11::sibling const&, p |
                                         | ybind11::return_value_policy const&)::'lambda |
                                         | '(pybind11::detail::function_call&)::__invoke |
                                         | (pybind11::detail::function_call&)            |
*               taichi_core.so |    4075 | pybind11::cpp_function::dispatcher(_object*,  |
                                         | _object*, _object*)                           |
*                      Python3 |     722 | (null)                                        |
*                      Python3 |     332 | (null)                                        |
*                      Python3 |     773 | (null)                                        |
*                      Python3 |   28360 | (null)                                        |
*                      Python3 |    2888 | (null)                                        |
*                      Python3 |     228 | (null)                                        |
*                      Python3 |     780 | (null)                                        |
*                      Python3 |   28692 | (null)                                        |
*                      Python3 |    2888 | (null)                                        |
*                      Python3 |     455 | (null)                                        |
*                      Python3 |     131 | (null)                                        |
*                      Python3 |     169 | (null)                                        |
*                      Python3 |     136 | (null)                                        |
*                      Python3 |   29134 | (null)                                        |
*                      Python3 |    2888 | (null)                                        |
*                      Python3 |     228 | (null)                                        |
*                      Python3 |     780 | (null)                                        |
*                      Python3 |   28520 | (null)                                        |
*                      Python3 |     237 | (null)                                        |
*                      Python3 |     780 | (null)                                        |
*                      Python3 |   28520 | (null)                                        |
*                      Python3 |     237 | (null)                                        |
*                      Python3 |     780 | (null)                                        |
*                      Python3 |   28520 | (null)                                        |
*                      Python3 |    2888 | (null)                                        |
*                      Python3 |      48 | (null)                                        |
*                      Python3 |     174 | (null)                                        |
*                      Python3 |     270 | (null)                                        |
*                      Python3 |    6590 | (null)                                        |
*                      Python3 |     111 | (null)                                        |
*                libdyld.dylib |       1 | (null)                                        |
*                          ??? |       2 | (null)                                        |
==========================================================================================


Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "/Users/xun/Downloads/demos/pbf.py", line 348, in <module>
    main()
  File "/Users/xun/Downloads/demos/pbf.py", line 339, in main
    run_pbf()
  File "/Users/xun/Downloads/demos/pbf.py", line 274, in run_pbf
    update_velocities()
  File "/Library/Python/3.7/site-packages/taichi/lang/kernel.py", line 530, in wrapped
    return primal(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/taichi/lang/kernel.py", line 460, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/Library/Python/3.7/site-packages/taichi/lang/kernel.py", line 340, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/Library/Python/3.7/site-packages/taichi/lang/kernel.py", line 337, in taichi_ast_generator
    compiled()
  File "/Users/xun/Downloads/demos/pbf.py", line 257, in update_velocities
    print(velocities)
  File "/Library/Python/3.7/site-packages/taichi/lang/util.py", line 189, in wrapped
    return func(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/taichi/lang/impl.py", line 335, in ti_print
    taichi_lang_core.create_print(contentries)
RuntimeError: [expr.cpp:load_if_ptr@172] ptr.cast<GlobalVariableExpression>()->snode->num_active_indices == 0
```

**Comment by XunZhan** [comment]
btw, I changed the init function to
```Python
ti.init(arch=ti.cpu, debug=True)
```

**Comment by yuanming-hu** [comment]
Hi @XunZhan,

Printing a tensor in the kernel is not supported. You can print each element of the tensor instead. Could you try
```python
for i in velocities:
    print(i, velocities[i])
```
?

**Comment by XunZhan** [comment]
> Hi @XunZhan,
> 
> Printing a tensor in the kernel is not supported. You can print each element of the tensor instead. Could you try
> 
> ```python
> for i in velocities:
>     print(i, velocities[i])
> ```
> 
> ?

It works. I previously used this but just wondering if we can make it simpler. Thanks! Maybe I should tag it as feature request.
