### ISSUE TITLE
Taichi run with a error

### ISSUE THREAD

**Issue by dayexingyang** [taichi-dev/taichi#1373]
Hello,
I am new to both Taichi and python. I installed Taichi and run the cases in Example folder with a error as follow:

 _[Taichi] mode=release
Share object taichi_core import failed, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "fractal.py", line 1, in <module>
    import taichi as ti
  File "/home/daye/.local/lib/python3.6/site-packages/taichi/__init__.py", line 2, in <module>
    from taichi.core import ti_core
  File "/home/daye/.local/lib/python3.6/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import ti_core, build, format, load_module, start_memory_monitoring, \
  File "/home/daye/.local/lib/python3.6/site-packages/taichi/core/util.py", line 276, in <module>
    import_ti_core()
  File "/home/daye/.local/lib/python3.6/site-packages/taichi/core/util.py", line 46, in import_ti_core
    raise e
  File "/home/daye/.local/lib/python3.6/site-packages/taichi/core/util.py", line 38, in import_ti_core
    import taichi_core as core
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/daye/.local/lib/python3.6/site-packages/taichi/core/../lib/taichi_core.so)_

My system is Ubuntu 16.04 and the python version is 3.6. It seems to be a problem of python. I'm new to python and I have searched the problem in website but not find a right solution to figure it out.

Daye

**Comment by yuanming-hu** [comment]
Please see https://github.com/taichi-dev/taichi/issues/701

**Comment by dayexingyang** [comment]
> Please see #701. Solution is probably [tensorflow/serving#819 (comment)](https://github.com/tensorflow/serving/issues/819#issuecomment-377776784)

It works! Thank you!
