### ISSUE TITLE
Raise "RuntimeError: [ir.cpp:get_attribute@293] Attribute dim not found." after I set parameters for a @ti.kernel function.

### ISSUE THREAD

**Issue by crissallan** [taichi-dev/taichi#1519]
**Describe the bug**
Raise "RuntimeError: [ir.cpp:get_attribute@293] Attribute dim not found." after I set parameters for a @ti.kernel function.

**To Reproduce**
`if __name__ == "__main__":`
`>>>>ti.init(arch=ti.cpu, debug=True)`
`>>>>a = ti.var(ti.i32, shape=(10))`
`>>>>b = ti.var(ti.i32, shape=(10))`

`>>>>@ti.kernel`
`>>>>def shift(v1: ti.i32, v2: ti.i32):`
`>>>>>>>>for i in range(10):`
`>>>>>>>>>>>>v1[i] = v2[i]`

`>>>>shift(a, b)`

BUT, if I didn't set parameters for the function "shift" like the code below, the code could run successfully.
`if __name__ == "__main__":`
`>>>>ti.init(arch=ti.cpu, debug=True)`
`>>>>a = ti.var(ti.i32, shape=(10))`
`>>>>b = ti.var(ti.i32, shape=(10))`

`>>>>@ti.kernel`
`>>>>def shift():`
`>>>>>>>>for i in range(10):`
`>>>>>>>>>>>>a[i] = b[i]`

`>>>>shift()`

**Log/Screenshots**
Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "/Users/crissallan/PycharmProjects/TaiChi_Learning/course_1/test_installation.py", line 40, in <module>
    shift(a, b)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/taichi/lang/kernel.py", line 562, in wrapped
    return primal(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/taichi/lang/kernel.py", line 490, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/taichi/lang/kernel.py", line 369, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/taichi/lang/kernel.py", line 366, in taichi_ast_generator
    compiled()
  File "/Users/crissallan/PycharmProjects/TaiChi_Learning/course_1/test_installation.py", line 38, in shift
    v1[i] = v2[i]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/taichi/lang/util.py", line 202, in wrapped
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/taichi/lang/impl.py", line 105, in subscript
    tensor_dim = int(value.ptr.get_attribute("dim"))
RuntimeError: [ir.cpp:get_attribute@293] Attribute dim not found.

**Comment by archibate** [comment]
Thank for reporting, this is probably not a bug.

> `def shift(v1: ti.i32, v2: ti.i32):`

The type annotation `ti.i32` means it take **integers**.
If you want to **pass tensor as argument**, consider use:
```py
def shift(v1: ti.template(), v2: ti.template()):
```
instead.

See https://taichi.readthedocs.io/en/stable/meta.html#template-metaprogramming for documentantion on this topic.

**Comment by crissallan** [comment]
> you want to **pass tensor as argument**, consider use:

Many thanks!
