### ISSUE TITLE
can't see results on windows

### ISSUE THREAD

**Issue by mirlip** [taichi-dev/taichi#168]
Hi,
now that it compiles, I ran some examples (those in the pdf docs). The simulation and render seem to run fine, without error, but when trying to show the results, I get an error:
NameError: name 'create_window' is not defined
It comes from the fact that the try to "from .qt_viewer import create_window" fails. I have pyqt5 installed and working. Do I have to install anything else? All deps where found during compile.
Even when I go to the folder I ran the command from, the outputs folder are empty...

This is the log for the simulation:
```
D:\python\bin\taichi>..\python.exe projects\examples\simulation\3d\mgpcg_smoke_3d.py
[T 10/12/18 21:11:36.023] [logging.cpp:taichi::Logger::Logger@67] Taichi core started. Thread ID = 3988
Warning: Qt initialization failed.
name 'os' is not defined
frame 0
Simulation time: 0.0
Seeding----------------------------------------------------- ==> 1164.13 ms ~ 1164.13 ms
[D 10/12/18 21:11:37.410] [poisson_solver3d.cpp:taichi::MultigridPCGPoissonSolver3D::run@451]
residual.sum(): -0.000686646
  [48, 0, 48]
 MGPCG iteration #00, nu=6.972348
  [48, 0, 48]
 MGPCG iteration #01, nu=1.257912
  [48, 0, 48]
 MGPCG iteration #02, nu=0.142727
  [48, 1, 47]
 MGPCG iteration #03, nu=0.008462
  [11, 0, 11]
 MGPCG iteration #04, nu=0.000756
  [18, 0, 18]
 MGPCG iteration #05, nu=0.000106
  [47, 0, 47]
 MGPCG iteration #06, nu=0.000010
  [48, 0, 48]
 MGPCG iteration #07, nu=0.000001
  [48, 0, 48]
 MGPCG iteration #08, nu=0.000000
fluid_3d.cpp[259]: project()-------------------------------- ==> 2288.40 ms ~ 2288.40 ms
fluid_3d.cpp[261]: move_trackers(delta_t)------------------- ==>   2.84 ms ~   2.84 ms
fluid_3d.cpp[262]: remove_outside_trackers()---------------- ==>   0.19 ms ~   0.19 ms
fluid_3d.cpp[263]: advect(delta_t)-------------------------- ==> 378.38 ms ~ 378.38 ms
Time: 3.8412487506866455
Traceback (most recent call last):
  File "projects\examples\simulation\3d\mgpcg_smoke_3d.py", line 69, in <module>
    show_image('Vis', img)
  File "D:\python\bin\taichi\python\taichi\gui\image_viewer.py", line 34, in show_image
    create_window(name, img)
NameError: name 'create_window' is not defined
```

**Comment by mirlip** [comment]
Awesome :)
