### ISSUE TITLE
SNodeType=pointer not supported on Metal

### ISSUE THREAD

**Issue by devenguo** [taichi-dev/taichi#1740]
Running the codes on macOS:
https://forum.taichi.graphics/t/homework1-eulerian-fluid-simulation-smoke/997/2

Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "smoke.py", line 577, in <module>
    main()
  File "smoke.py", line 573, in main
    smoke_solver.run()
  File "smoke.py", line 543, in run
    self.reset()
  File "smoke.py", line 521, in reset
    self._dens_buffer.fill(0.0)
  File "/Users/guodewen/anaconda3/envs/taichi/lib/python3.7/site-packages/taichi/lang/util.py", line 212, in wrapped
    return func(*args, **kwargs)
  File "/Users/guodewen/anaconda3/envs/taichi/lib/python3.7/site-packages/taichi/lang/expr.py", line 126, in fill
    fill_tensor(self, val)
  File "/Users/guodewen/anaconda3/envs/taichi/lib/python3.7/site-packages/taichi/lang/kernel.py", line 580, in wrapped
    return primal(*args, **kwargs)
  File "/Users/guodewen/anaconda3/envs/taichi/lib/python3.7/site-packages/taichi/lang/kernel.py", line 507, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/Users/guodewen/anaconda3/envs/taichi/lib/python3.7/site-packages/taichi/lang/kernel.py", line 309, in materialize
    self.runtime.materialize()
  File "/Users/guodewen/anaconda3/envs/taichi/lib/python3.7/site-packages/taichi/lang/impl.py", line 216, in materialize
    taichi_lang_core.layout(layout)
RuntimeError: [struct_metal.cpp:generate_types@230] SNodeType=pointer not supported on Metal
>>> Running time: 0.67s

**Comment by archibate** [comment]
This is because the sparse feature is not yet supported on Metal backend.
Solution:
1. Replace `ti.init(ti.gpu)` by `ti.init(ti.cpu)`.
2. Replace all `xxx.pointer` by `xxx.bitmasked`.

**Comment by k-ye** [comment]
This feature is finally shipped in https://github.com/taichi-dev/taichi/releases/tag/v0.7.25. Feel free to give it a try, thx!
