### ISSUE TITLE
prerequisites should be add to README or docs

### ISSUE THREAD

**Issue by lanybass** [taichi-dev/taichi#191]
I'm on windows 10 x64.  
prerequisites:  
vs2017  
cmake latest  
python3.6

**Comment by lanybass** [comment]
and, there is an error:
```
CMake suite maintained and supported by Kitware (kitware.com/cmake).
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: psutil in c:\users\yunwang\appdata\roaming\python\python36\site-packages (5.6.2)
Current directory: E:\githubdown\taichi\taichi
Taichi source detected.
Existing taichi runtimes detected.
Executing command: git submodule update --init --recursive
Warning: Windows environment variable persistent edits are not supported
Warning: Windows environment variable persistent edits are not supported
Warning: Windows environment variable persistent edits are not supported
Warning: Windows environment variable persistent edits are not supported
PYTHONPATH=E:\githubdown\taichi\taichi/python/;
Executing command: echo $PYTHONPATH
$PYTHONPATH
DLL load failed: 找不到指定的模块。

Is taichi\external\lib correctly set to branch msvc or mingw?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\githubdown\taichi\taichi\python\taichi\__init__.py", line 1, in <module>
    from taichi.main import main
  File "E:\githubdown\taichi\taichi\python\taichi\main.py", line 6, in <module>
    from taichi.tools.video import make_video, interpolate_frames
  File "E:\githubdown\taichi\taichi\python\taichi\tools\video.py", line 3, in <module>
    import taichi.core as core
  File "E:\githubdown\taichi\taichi\python\taichi\core\__init__.py", line 1, in <module>
    from .util import tc_core, build, format, update, install_package, load_module, start_memory_monitoring
  File "E:\githubdown\taichi\taichi\python\taichi\core\util.py", line 296, in <module>
    raise e
  File "E:\githubdown\taichi\taichi\python\taichi\core\util.py", line 290, in <module>
    import taichi_core as tc_core
ImportError: DLL load failed: 找不到指定的模块。
  Error: installation failed.
```
I can find taichi_core.dll in taichi\runtimes\Release  
and taichi_core.pyd in taichi\outputs\tmp\task-*\  

I've checked the branch lib of is msvc.

**Comment by lanybass** [comment]
ok .Resolved. Just copy all dll files from taichi\external\lib\ to the .pyd's dir

**Comment by victoryang00** [comment]
still have issue here.

**Comment by victoryang00** [comment]
Add some 坑 during the compiling stage.
1. Use [llvm9](https://download.csdn.net/download/dbyoung/11175973?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522158447595219726869040765%2522%252C%2522scm%2522%253A%252220140713.130062587..%2522%257D&request_id=158447595219726869040765&biz_id=1&utm_source=distribute.pc_search_result.none-task) rather than llvm8. You have to change the corresponding cmake file.
2. Change the MSVC Runtime Library into `\MD` after cmake. You can either open the vs window or modify the vsxproj file。 or you can set the environment in cmake in taichi_core.cmake
3. set the `LLVM_ENABLE_ABI_BREAKING_CHECKS` to 0 in the include path of llvm.

That's all, It's a beautiful project applying jit-llvm for optimization!
