### ISSUE TITLE
Will there be a M1 Mac support?

### ISSUE THREAD

**Issue by JamesQFreeman** [taichi-dev/taichi#2097]

**Comment by k-ye** [comment]
Thanks. Currently there are two problems regarding M1: 1) we don't have a M1 build bot , and 2) `numpy` is not working on M1 yet. Sorry about that!

**Comment by wyq977** [comment]
I have recently tested on a m1 mac mini with miniforge installed and the installing taichi doesnt seems to works straight-forward like i expected

conda: 4.9.2
python: 
<details>
  <summary>Log</summary>
  
```bash
$ python3 -m pip install taichi
ERROR: Could not find a version that satisfies the requirement taichi
ERROR: No matching distribution found for taichi
^CTraceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/__main__.py", line 24, in <module>
    sys.exit(_main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 226, in _main
    self.handle_pip_version_check(options)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 151, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py", line 160, in pip_self_version_check
    best_candidate = finder.find_best_candidate("pip").best_candidate
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 872, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 815, in find_all_candidates
    package_links = self.process_project_url(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 786, in process_project_url
    package_links = self.evaluate_links(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 768, in evaluate_links
    candidate = self.get_install_candidate(link_evaluator, link)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 749, in get_install_candidate
    is_candidate, result = link_evaluator.evaluate_link(link)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 225, in evaluate_link
    supports_python = _check_link_requires_python(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 74, in _check_link_requires_python
    is_compatible = check_requires_python(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_internal/utils/packaging.py", line 37, in check_requires_python
    requires_python_specifier = specifiers.SpecifierSet(requires_python)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_vendor/packaging/specifiers.py", line 671, in __init__
    split_specifiers = [s.strip() for s in specifiers.split(",") if s.strip()]
  File "/opt/homebrew/Caskroom/miniforge/base/envs/taichipip/lib/python3.8/site-packages/pip/_vendor/packaging/specifiers.py", line 671, in <listcomp>
    split_specifiers = [s.strip() for s in specifiers.split(",") if s.strip()]
```
</details>

**Comment by yuanming-hu** [comment]
Thanks for reporting - we are setting up an Apple M1 build bot soon, but before that you can build from scratch: https://taichi.readthedocs.io/en/latest/dev_install.html#developer-installation

**Comment by wyq977** [comment]
Hi, thx for the prompt reply.

I read the dev installing guide and I assume that one needs to build LLVM from source 
> `# If you are building on Apple M1, use -DLLVM_TARGETS_TO_BUILD="AArch64"`

Just a question out of curisoity, r u guys hosting a CI pipeline or using services like  travis or github ci because I see plenty decide to look for ci provider after [travis changed pricing](https://github.com/opencv/opencv-python/issues/422)

**Comment by wyq977** [comment]
Checked out [llvm](https://github.com/llvm/llvm-project) today. Found out that they make quite a few adjustment to add arm macos or m1/a12/apple silicon(name handling is a bit confusing...)

Like in [llvm/include/llvm/ADT/Triple.h](https://github.com/llvm/llvm-project/commits/152df3add156b68aca7bfb06b62ea85fa127f3b1/llvm/include/llvm/ADT/Triple.h)

`isAArch64`

Also in [MachO.cpp](https://github.com/llvm/llvm-project/commits/152df3add156b68aca7bfb06b62ea85fa127f3b1/llvm/lib/BinaryFormat/MachO.cpp)

`getARM64SubType `

I thought of just changing a few lines in Triple.h to suppress change but it looks like changes are quite scatter around in lots of commits... But mostly are just in llvm/include/llvm/ADT/Triple.h and lib/ExecutionEngine/JITLink/MachO.cpp (llvm/BinaryFormat/MachO.h later)

**Comment by xchern** [comment]
I have succeed with miniforge (https://github.com/conda-forge/miniforge), it packs a numpy built for m1.

And this is my built binary wheel for taichi (https://github.com/xchern/taichi/releases/tag/v0.7.20-apple-silicon-alpha).

**Comment by k-ye** [comment]
Supported now :-)
