### ISSUE TITLE
arch=ti.gpu doesn't work for ctypes

### ISSUE THREAD

**Issue by JerryYan97** [taichi-dev/taichi#2121]
**Describe the bug**
arch=ti.cpu works good for ctypes external funcs, but ti.gpu doesn't work.

**To Reproduce**
This is modified based on the sample code here: https://github.com/taichi-dev/taichi/blob/master/misc/demo_external_func.py.

```py
import taichi as ti
import os
import ctypes

ti.init(arch=ti.gpu)

N = 1024
x = ti.field(ti.i32, shape=N)
y = ti.field(ti.i32, shape=N)
z = ti.field(ti.i32, shape=N)

source = '''
extern "C" {
    void add_and_mul(float a, float b, float *c, float *d, int *e) {
        *c = a + b;
        *d = a * b;
        *e = int(a * b + a);
    }
    void pow_int(int a, int b, int *c) {
        int ret = 1;
        for (int i = 0; i < b; i++)
            ret = ret * a;
        *c = ret;
    }
}
'''

with open('a.cpp', 'w') as f:
    f.write(source)

os.system("g++ a.cpp -o a.so -fPIC -shared")

so = ctypes.CDLL("./a.so")


@ti.kernel
def call_ext() -> ti.i32:
    a = 2.0
    b = 3.0
    c = 0.0
    d = 0.0
    e = 3
    ti.external_func_call(func=so.add_and_mul, args=(a, b), outputs=(c, d, e))
    p = 0
    ti.external_func_call(func=so.pow_int, args=(int(c + d), e), outputs=(p, ))
    return p


# Wrap the external function to make it easier to use
@ti.func
def pow_int_wrapper(a, b):
    p = 0
    ti.external_func_call(func=so.pow_int,
                          args=(int(a), int(b)),
                          outputs=(p, ))
    return p


@ti.kernel
def call_parallel():
    for i in range(N):
        z[i] = pow_int_wrapper(x[i], y[i])


assert call_ext() == 11**8

for i in range(N):
    x[i] = i
    y[i] = 3

call_parallel()
for i in range(N):
    assert z[i] == i**3

os.remove('a.cpp')
os.remove('a.so')

```

**Log/Screenshots**

```
/usr/bin/python3.8 /home/jiaruiyan/self_study/Taichi_GNN/test_ground2.py
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-wqkp_nly
[Taichi] version 0.7.10, llvm 10.0.0, commit 0f0205fc, linux, python 3.8.5
[Taichi] Starting on arch=cuda
[Taichi] materializing...
[E 12/25/20 14:49:13.417] [statements.inc.h:visit@46] Not supported.


***********************************
* Taichi Compiler Stack Traceback *
***********************************
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::IRVisitor::visit(taichi::lang::ExternalFuncCallStmt*)
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::visit(taichi::lang::Block*)
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVMCUDA::visit(taichi::lang::OffloadedStmt*)
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::visit(taichi::lang::Block*)
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::emit_to_module()
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::gen()
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenCUDA::codegen()
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::KernelCodeGen::compile()
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Program::compile_to_backend_executable(taichi::lang::Kernel&, taichi::lang::OffloadedStmt*)
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Program::compile(taichi::lang::Kernel&)
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Kernel::compile()
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Kernel::operator()(taichi::lang::Kernel::LaunchContextBuilder&)
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x4ee784) [0x7f61163b8784]
/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x3e7144) [0x7f61162b1144]
/usr/bin/python3.8: PyCFunction_Call
/usr/bin/python3.8: _PyObject_MakeTpCall
/usr/bin/python3.8: ) [0x50a978]
/usr/bin/python3.8: PyObject_Call
/usr/bin/python3.8: ) [0x59d47c]
/usr/bin/python3.8: _PyObject_MakeTpCall
/usr/bin/python3.8: _PyEval_EvalFrameDefault
/usr/bin/python3.8: _PyEval_EvalCodeWithName
/usr/bin/python3.8: _PyFunction_Vectorcall
/usr/bin/python3.8: PyObject_Call
/usr/bin/python3.8: _PyEval_EvalFrameDefault
/usr/bin/python3.8: _PyEval_EvalCodeWithName
/usr/bin/python3.8: _PyFunction_Vectorcall
/usr/bin/python3.8: ) [0x59d17f]
/usr/bin/python3.8: PyObject_Call
/usr/bin/python3.8: _PyEval_EvalFrameDefault
/usr/bin/python3.8: _PyEval_EvalCodeWithName
/usr/bin/python3.8: _PyFunction_Vectorcall
/usr/bin/python3.8: _PyEval_EvalFrameDefault
/usr/bin/python3.8: _PyEval_EvalCodeWithName
/usr/bin/python3.8: PyEval_EvalCode
/usr/bin/python3.8: ) [0x67bc91]
/usr/bin/python3.8: ) [0x67bd0f]
/usr/bin/python3.8: PyRun_FileExFlags
/usr/bin/python3.8: PyRun_SimpleFileExFlags
/usr/bin/python3.8: Py_RunMain
/usr/bin/python3.8: Py_BytesMain
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
/usr/bin/python3.8: _start

Internal error occurred. Check out this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "/home/jiaruiyan/self_study/Taichi_GNN/test_ground2.py", line 65, in <module>
    assert call_ext() == 11**8
  File "/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/lang/kernel.py", line 571, in wrapped
    return primal(*args, **kwargs)
  File "/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/lang/kernel.py", line 500, in __call__
    return self.compiled_functions[key](*args)
  File "/home/jiaruiyan/.local/lib/python3.8/site-packages/taichi/lang/kernel.py", line 458, in func__
    t_kernel(launch_ctx)
RuntimeError: [statements.inc.h:visit@46] Not supported.

Process finished with exit code 1

```

**Comment by k-ye** [comment]
HI,

1. I don't think you can just call a C function (compiled from `gcc`) in CUDA. 
2. Taichi's CUDA backend doesn't support external functions. (This API isn't well documented, sorry about the confusion)
