### ISSUE TITLE
Support for cuda 11.2?

### ISSUE THREAD

**Issue by squarefk** [taichi-dev/taichi#2155]
```

➜  ~ nvidia-smi 
Wed Jan 13 11:20:36 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 166...  Off  | 00000000:01:00.0  On |                  N/A |
| 23%   40C    P8     9W / 120W |    243MiB /  5942MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       897      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A    225739      G   /usr/lib/xorg/Xorg                139MiB |
|    0   N/A  N/A    225856      G   /usr/bin/gnome-shell               54MiB |
|    0   N/A  N/A    232035      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A    232180      G   /usr/lib/firefox/firefox            1MiB |
+-----------------------------------------------------------------------------+
➜  ~ python3 fractal.py 
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-_43m7nzh
[Taichi] version 0.7.12, llvm 10.0.0, commit 8d452801, linux, python 3.8.5
[Taichi] Starting on arch=cuda
[E 01/13/21 11:20:42.205] [cuda_driver.h:operator()@80] CUDA Error CUDA_ERROR_UNKNOWN: unknown error while calling init (cuInit)


***********************************
* Taichi Compiler Stack Traceback *
***********************************
/home/squarefk/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
/home/squarefk/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CUDADriverFunction<int>::operator()(int)
/home/squarefk/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CUDAContext::CUDAContext()
/home/squarefk/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CUDAContext::get_instance()
/home/squarefk/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::RuntimeCUDA::detected()
/home/squarefk/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Program::Program(taichi::lang::Arch)
/home/squarefk/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x570ef9) [0x7f36eb77cef9]
/home/squarefk/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x3efb94) [0x7f36eb5fbb94]
python3(PyCFunction_Call+0x59) [0x5f4249]
python3(_PyObject_MakeTpCall+0x296) [0x5f46d6]
python3() [0x50a953]
python3(PyObject_Call+0x62) [0x5f3d42]
python3() [0x59cb04]
python3() [0x5a7bf7]
/home/squarefk/.local/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x3ea4cb) [0x7f36eb5f64cb]
python3(_PyObject_MakeTpCall+0x296) [0x5f46d6]
python3(_PyEval_EvalFrameDefault+0x5de6) [0x570936]
python3(_PyFunction_Vectorcall+0x1b6) [0x5f7146]
python3(_PyEval_EvalFrameDefault+0x849) [0x56b399]
python3(_PyEval_EvalCodeWithName+0x26a) [0x56955a]
python3(_PyFunction_Vectorcall+0x393) [0x5f7323]
python3(_PyEval_EvalFrameDefault+0x1901) [0x56c451]
python3(_PyEval_EvalCodeWithName+0x26a) [0x56955a]
python3(PyEval_EvalCode+0x27) [0x68c4a7]
python3() [0x67bc91]
python3() [0x67bd0f]
python3(PyRun_FileExFlags+0x9b) [0x67bdcb]
python3(PyRun_SimpleFileExFlags+0x17e) [0x67de4e]
python3(Py_RunMain+0x212) [0x6b6032]
python3(Py_BytesMain+0x2d) [0x6b63bd]
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
python3(_start+0x2e) [0x5fa4de]

Internal error occurred. Check out this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "fractal.py", line 4, in <module>
    ti.init(arch=ti.gpu)
  File "/home/squarefk/.local/lib/python3.8/site-packages/taichi/lang/__init__.py", line 216, in init
    ti.get_runtime().create_program()
  File "/home/squarefk/.local/lib/python3.8/site-packages/taichi/lang/impl.py", line 215, in create_program
    self.prog = taichi_lang_core.Program()
RuntimeError: [cuda_driver.h:operator()@80] CUDA Error CUDA_ERROR_UNKNOWN: unknown error while calling init (cuInit)
➜  ~ 



```

**Comment by yuanming-hu** [comment]
Thanks for reporting but I don't think we will have time for this before the SIGGRAPH deadline. Note that most systems (including PyTorch) do not even support CUDA 11.2 yet. My suggestion is to stick to CUDA 11.0/11.1.

**Comment by archibate** [comment]
Hi, I can confirm my end running mpm88 happily with no error on CUDA 11.2.
