### ISSUE TITLE
Video Manager could not be used

### ISSUE THREAD

**Issue by coffeiersama** [taichi-dev/taichi#2168]
**Describe the bug**
I am trying to use the video manager to output gif file but it keeps showing ' FileNotFoundError: [Errno 2] No such file or directory: 'palette.png''

the whole docs are:
```
Traceback (most recent call last):
  File "animComparator.py", line 100, in <module>
    video_manager.make_video(gif=True, mp4=True)
  File "/home/donyan/Downloads/Anaconda/ENTER/envs/taichi/lib/python3.6/site-packages/taichi/tools/video.py", line 127, in make_video
    self.get_output_filename('.gif'), self.framerate)
  File "/home/donyan/Downloads/Anaconda/ENTER/envs/taichi/lib/python3.6/site-packages/taichi/tools/video.py", line 53, in mp4_to_gif
    os.remove(palette_name)
FileNotFoundError: [Errno 2] No such file or directory: 'palette.png'
```

I have also tried the export video example in the example folder at taichi Github, it still told me no palette.png, do I need to install something on my system to fix this?

**Comment by k-ye** [comment]
Most likely you didn't install `ffmpeg`, or it's not in your `$PATH`?

Unfortunately, this part of code was written to terminate early when the subprocess has failed:

https://github.com/taichi-dev/taichi/blob/d1061750485a7f31bb3b0f824182f1c497c70051/python/taichi/tools/video.py#L45-L53
