### ISSUE TITLE
[Example] mnist_download_data 503 error

### ISSUE THREAD

**Issue by arisliang** [taichi-dev/taichi#2236]
**Describe the bug**
mnist_download_data encounter 503 error, unable to download mnist data.

**To Reproduce**
```
ti example mnist_download_data
```

**Log/Screenshots**
```
(taichi) C:\taichi_cache>ti example mnist_download_data
[Taichi] mode=release
[Taichi] version 0.7.15, llvm 10.0.0, commit cff542ce, win, python 3.8.8

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://taichi.rtfd.io/en/stable
GitHub: https://github.com/taichi-dev/taichi
Forum:  https://forum.taichi.graphics

Running example mnist_download_data ...
Downloading train-images-idx3-ubyte.gz...
Traceback (most recent call last):
  File "c:\users\arisl\anaconda3\envs\taichi\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\arisl\anaconda3\envs\taichi\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\arisl\anaconda3\envs\taichi\Scripts\ti.exe\__main__.py", line 7, in <module>
  File "c:\users\arisl\anaconda3\envs\taichi\lib\site-packages\taichi\main.py", line 1095, in main
    return cli()
  File "c:\users\arisl\anaconda3\envs\taichi\lib\site-packages\taichi\main.py", line 27, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\arisl\anaconda3\envs\taichi\lib\site-packages\taichi\main.py", line 88, in __call__
    return getattr(self, args.command)(sys.argv[2:])
  File "c:\users\arisl\anaconda3\envs\taichi\lib\site-packages\taichi\main.py", line 216, in example
    runpy.run_path(target, run_name='__main__')
  File "c:\users\arisl\anaconda3\envs\taichi\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\users\arisl\anaconda3\envs\taichi\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\users\arisl\anaconda3\envs\taichi\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\arisl\anaconda3\envs\taichi\lib\site-packages\taichi\examples\mnist_download_data.py", line 49, in <module>
    init()
  File "C:\Users\arisl\anaconda3\envs\taichi\lib\site-packages\taichi\examples\mnist_download_data.py", line 37, in init
    download_mnist()
  File "C:\Users\arisl\anaconda3\envs\taichi\lib\site-packages\taichi\examples\mnist_download_data.py", line 18, in download_mnist
    request.urlretrieve(base_url + name[1], name[1])
  File "c:\users\arisl\anaconda3\envs\taichi\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "c:\users\arisl\anaconda3\envs\taichi\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\arisl\anaconda3\envs\taichi\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\arisl\anaconda3\envs\taichi\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "c:\users\arisl\anaconda3\envs\taichi\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\users\arisl\anaconda3\envs\taichi\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "c:\users\arisl\anaconda3\envs\taichi\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by wyq977** [comment]
I think the server just might be out of capacity from time to time. You can try re-download it again.

I ran into the same problem upon trying but was able to run fine on a second trial. As far as i can see, no bugs on the example side.

**Comment by wyq977** [comment]
yeah its probably at the server end, i tried download directly using browser and still hangs from time to time...

**Comment by arisliang** [comment]
Unfortunately, I tried a couple of times, non succeeded.

**Comment by FantasyVR** [comment]
@arisliang I got the same errors sometimes. But it works when I try more times. I think it has nothing to do with me the script `mnist_download_data`. I think @wyq977  is right. The server is the reason the script fails.


> I think the server just might be out of capacity from time to time. You can try re-download it again.
> 
> I ran into the same problem upon trying but was able to run fine on a second trial. As far as i can see, no bugs on the example side.
