### ISSUE TITLE
AttributeError: module 'taichi' has no attribute 'TaichiOperations'

### ISSUE THREAD

**Issue by jcn16** [taichi-dev/taichi#2275]
**Describe the bug**
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-bkpzifl0
[Taichi] version 0.7.16, llvm 10.0.0, commit bca037cf, linux, python 3.7.0
[TaiGLSL] version 0.0.10

platform is Ubuntu 18.05

**To Reproduce**

```py
# sample code here
```

**Log/Screenshots**
Traceback (most recent call last):
  File "/home/jcn/桌面/Nerf/render_twindom/render_multi.py", line 2, in <module>
    import taichi_three as t3
  File "/home/jcn/anaconda3/envs/pifuhd/lib/python3.7/site-packages/taichi_three/__init__.py", line 13, in <module>
    import taichi_glsl as ts
  File "/home/jcn/anaconda3/envs/pifuhd/lib/python3.7/site-packages/taichi_glsl/__init__.py", line 24, in <module>
    from .classes import *
  File "/home/jcn/anaconda3/envs/pifuhd/lib/python3.7/site-packages/taichi_glsl/classes.py", line 5, in <module>
    class Complex(tl.TaichiClass, ti.TaichiOperations):
AttributeError: module 'taichi' has no attribute 'TaichiOperations'
```
$ python my_sample_code.py
[Taichi] mode=release
[Taichi] version 0.6.29, llvm 10.0.0, commit b63f6663, linux, python 3.8.3
...
```

**Additional comments**

**Comment by yaolyu** [comment]
I updated Taichi  today and met the same problem.

**Comment by aith** [comment]
I'm also receiving this problem- on Ubuntu 20.04

**Comment by RexHuang** [comment]
same problem

**Comment by k-ye** [comment]
@archibate  and I have just made a new release to `taichi_glsl`. Please upgrade to `v0.0.11` to see if your problem is fixed, thanks!
