### ISSUE TITLE
gui.set_image is incompatible with advanced_optimization=False

### ISSUE THREAD

**Issue by xeTaiz** [taichi-dev/taichi#2446]
**Describe the bug**
When setting `ti.init(advanced_optimization=False)`, then the GUI's `set_image()` function runs into hard to read assertion errors.

**To Reproduce**
```py
import taichi as ti
ti.init(arch=ti.cpu, advanced_optimization=False)

pixels = ti.Vector.field(3, dtype=ti.f32, shape=(400, 400))

gui = ti.GUI("Test", res=(400, 400), fast_gui=False)
while True:
    gui.set_image(pixels)
    gui.show()
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python test_gui.py
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-a3ua0fx1
[Taichi] version 0.7.21, llvm 10.0.0, commit 15465fb6, linux, python 3.9.5
[Taichi] Starting on arch=x64
[Taichi] materializing...
[E 06/21/21 14:47:17.012] [codegen_llvm.cpp:visit@325] Assertion failure: from != to


***********************************
* Taichi Compiler Stack Traceback *
***********************************
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::visit(taichi::lang::UnaryOpStmt*)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::visit(taichi::lang::Block*)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::visit(taichi::lang::IfStmt*)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::visit(taichi::lang::Block*)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVMCPU::create_offload_range_for(taichi::lang::OffloadedStmt*)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVMCPU::visit(taichi::lang::OffloadedStmt*)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::visit(taichi::lang::Block*)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::emit_to_module()
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVM::gen()
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenCPU::codegen()
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::KernelCodeGen::compile()
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Program::compile_to_backend_executable(taichi::lang::Kernel&, taichi::lang::OffloadedStmt*)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Program::compile(taichi::lang::Kernel&)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Kernel::compile()
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Kernel::operator()(taichi::lang::Kernel::LaunchContextBuilder&)
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so(+0x37594a) [0x7fbc9e15094a]
/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so(+0x360ebe) [0x7fbc9e13bebe]
python(+0x146e64) [0x560edb2e1e64]
python(_PyObject_MakeTpCall+0x37f) [0x560edb2dbe4f]
python(+0xd4bd3) [0x560edb26fbd3]
python(_PyObject_Call+0x1b8) [0x560edb2db788]
python(+0xa5efa) [0x560edb240efa]
python(_PyObject_MakeTpCall+0x37f) [0x560edb2dbe4f]
python(_PyEval_EvalFrameDefault+0x4a7) [0x560edb367937]
python(+0x186d2b) [0x560edb321d2b]
python(_PyFunction_Vectorcall+0x1e7) [0x560edb322697]
python(_PyObject_Call+0x1b8) [0x560edb2db788]
python(_PyEval_EvalFrameDefault+0x2350) [0x560edb3697e0]
python(+0x186b32) [0x560edb321b32]
python(_PyFunction_Vectorcall+0x1e7) [0x560edb322697]
python(_PyObject_FastCallDictTstate+0x6a) [0x560edb31260a]
python(+0x1779d5) [0x560edb3129d5]
python(_PyObject_Call+0x214) [0x560edb2db7e4]
python(_PyEval_EvalFrameDefault+0x2350) [0x560edb3697e0]
python(+0x186d2b) [0x560edb321d2b]
python(_PyFunction_Vectorcall+0x1e7) [0x560edb322697]
python(+0xff3be) [0x560edb29a3be]
python(_PyFunction_Vectorcall+0x413) [0x560edb3228c3]
python(+0xff1a4) [0x560edb29a1a4]
python(+0x186b32) [0x560edb321b32]
python(PyEval_EvalCodeEx+0x4c) [0x560edb3d1ddc]
python(PyEval_EvalCode+0x1b) [0x560edb322b5b]
python(+0x236e8b) [0x560edb3d1e8b]
python(+0x267215) [0x560edb402215]
python(+0x112677) [0x560edb2ad677]
python(PyRun_SimpleFileExFlags+0x1bf) [0x560edb406cef]
python(Py_RunMain+0x378) [0x560edb4073b8]
python(Py_BytesMain+0x39) [0x560edb4075b9]
/usr/lib/libc.so.6: __libc_start_main
python(+0x1f4a64) [0x560edb38fa64]

Internal error occurred. Check out this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "/run/media/dome/SSD/Repositories/Differender/src/test_gui.py", line 8, in <module>
    gui.set_image(pixels)
  File "/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/misc/gui.py", line 197, in set_image
    vector_to_image(img, self.img)
  File "/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/lang/kernel_impl.py", line 634, in wrapped
    return primal(*args, **kwargs)
  File "/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/lang/kernel_impl.py", line 562, in __call__
    return self.compiled_functions[key](*args)
  File "/home/dome/anaconda3/envs/taichi/lib/python3.9/site-packages/taichi/lang/kernel_impl.py", line 516, in func__
    t_kernel(launch_ctx)
RuntimeError: [codegen_llvm.cpp:visit@325] Assertion failure: from != to
```

**Additional comments**
I found this issue to persist on for different `ti.init()` `arch` arguments.
Similarly the `fast_gui` argument has no effect on it

**Comment by xumingkuan** [comment]
Thanks for reporting this bug and it should be fixed in #2451 :)
