### ISSUE TITLE
ImportError: libz3.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by shwnyao** [taichi-dev/taichi#2452]
**Describe the bug**
OS: Ubuntu 20.04
python version: 3.8 64bit
pip version: 21.1.2
libtinfo5 already installed

It fails at `import taichi as ti` and shows import error

**To Reproduce**
```
$ python3
>>> import taichi as ti
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
~/taichi$ python3
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tachi as ti
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tachi'
>>> import taichi as ti
[Taichi] mode=release
Share object taichi_core import failed, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.core import *
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/__init__.py", line 1, in <module>
    from taichi.core.logging import *
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/logging.py", line 4, in <module>
    from taichi.core import util
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/util.py", line 171, in <module>
    import_ti_core()
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/util.py", line 48, in import_ti_core
    raise e from None
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/util.py", line 36, in import_ti_core
    import taichi_core as core
ImportError: libz3.so.4: cannot open shared object file: No such file or directory
Consider installing libtinfo5: sudo apt-get install libtinfo5
```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

```
$ ti diagnose
[Taichi] mode=release
Share object taichi_core import failed, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "/home/ros/.local/bin/ti", line 5, in <module>
    from taichi.main import main
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.core import *
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/__init__.py", line 1, in <module>
    from taichi.core.logging import *
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/logging.py", line 4, in <module>
    from taichi.core import util
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/util.py", line 171, in <module>
    import_ti_core()
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/util.py", line 48, in import_ti_core
    raise e from None
  File "/home/ros/.local/lib/python3.8/site-packages/taichi/core/util.py", line 36, in import_ti_core
    import taichi_core as core
ImportError: libz3.so.4: cannot open shared object file: No such file or directory
Consider installing libtinfo5: sudo apt-get install libtinfo5
```

**Comment by shwnyao** [comment]
Reverting to the previous version pip install taichi==0.7.16 fixed the issue.

**Comment by k-ye** [comment]
https://howtoinstall.co/en/libz3-dev?

**Comment by shwnyao** [comment]
Yup that works. How did I not see that...
Thanks anyways!
