### ISSUE TITLE
Access error associate with taichi_cache

### ISSUE THREAD

**Issue by yjhp1016** [taichi-dev/taichi#2561]
Hi, I tried to run Taichi on my windows machine, but got an permission error for folder taichi_cache, I guess this can be easily solved by run as administrator, but for my case I don't have administrator access for this machine, I think it will be very handy to make the code able to run without administrator access.

Here is the details of the error:
 (base) C:\Users\J0424810\Work\Tools\Taichi>python fractal.py
[Taichi] mode=release
Traceback (most recent call last):
  File "fractal.py", line 1, in <module>
    import taichi as ti
  File "C:\Users\J0424810\AppData\Local\Continuum\anaconda3\lib\site-packages\taichi\__init__.py", line 1, in <module>
    from taichi.core import *
  File "C:\Users\J0424810\AppData\Local\Continuum\anaconda3\lib\site-packages\taichi\core\__init__.py", line 1, in <module>
    from taichi.core.logging import *
  File "C:\Users\J0424810\AppData\Local\Continuum\anaconda3\lib\site-packages\taichi\core\logging.py", line 4, in <module>
    from taichi.core import util
  File "C:\Users\J0424810\AppData\Local\Continuum\anaconda3\lib\site-packages\taichi\core\util.py", line 179, in <module>
    os.makedirs(ti_core.get_repo_dir(), exist_ok=True)
  File "C:\Users\J0424810\AppData\Local\Continuum\anaconda3\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'C:/taichi_cache/'

**Comment by k-ye** [comment]
Thanks for reporting this! We should fix the hardcoded paths... https://github.com/taichi-dev/taichi/blob/7e54f56d305f370f773264864f7fcf117470ddf1/taichi/common/core.cpp#L46-L54

**Comment by R366Y** [comment]
Hi, I solved the problem creating the directory "C:/taichi_cache". Instead of having an hardcoded directory on Windows,  you should create a new one in C:\Users\<user name>. That should solve also the problem with permissions.

**Comment by R366Y** [comment]
@yjhp1016 , when I said 

> you should create a new one in C:\Users. That should solve also the problem with permissions.

I was addressing Taichi developers, sorry for misunderstanding. 

As I said, the only thing you can do is to create "C:/taichi_cache"  manually until this bug is fixed.  You said you don't have admin access to your machine therefore you cannot create the aforementioned directory. I think you have to wait this bug being fixed then.

**Comment by k-ye** [comment]
@R366Y thanks! Would you like to open a PR to fix this?

**Comment by R366Y** [comment]
Hi @k-ye , 
I don't know if I have time this week to patch the bug. 
But if somebody else wanna take this up , there is an hint how to do it :

> The standard location for Windows application to store their (permanent) application data is referenced by the %APPDATA% (current user) or %ALLUSERSPROFILE% (all users) environment variables.

I suggest to use Python's _pathilb_ : 

- Check if the cache directory exists at installation or at the first run.
- If it doesn't , create a cache directory under %APPDATA% e.g. %APPDATA%\taichi\cache
