### ISSUE TITLE
Supporting chained assignment e.g. ``a = b = 0`` in ti.kernel 

### ISSUE THREAD

**Issue by Ricahrd-Li** [taichi-dev/taichi#2659]
**Concisely describe the proposed feature**
I'd like to support chained assignment like ``a = b = 0`` in ti.kernel 

**Describe the solution you'd like (if any)**
Thinking now. 

**Additional comments**
current error:
```python
>>> import taichi as ti 
[Taichi] mode=release
[Taichi] preparing sandbox at /var/folders/n_/mhc67_bn7vx8gyv83h7w29_c0000gn/T/taichi-61l517c2
[Taichi] version 0.7.24, llvm 10.0.0, commit 25778773, osx, python 3.8.3
>>> @ti.kernel 
... def func():
...     a = b = 0
... 
>>> func()
[Taichi] materializing...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 635, in wrapped
    return primal(*args, **kwargs)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 562, in __call__
    key = self.ensure_compiled(*args)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 553, in ensure_compiled
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 391, in materialize
    visitor.visit(tree)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/transformer.py", line 53, in visit
    self.pass_Preprocess.visit(tree)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/transformer.py", line 650, in visit_Module
    self.generic_visit(node)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/transformer.py", line 168, in generic_visit
    value = self.visit(value)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/transformer.py", line 742, in visit_FunctionDef
    self.generic_visit(node)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/transformer.py", line 168, in generic_visit
    value = self.visit(value)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/Users/lizhehao/opt/anaconda3/lib/python3.8/site-packages/taichi/lang/transformer.py", line 202, in visit_Assign
    assert (len(node.targets) == 1)
AssertionError
```

**Comment by gaocegege** [comment]
BTW, you may also need to consider how to support chained assignments and unpack assignments together like this: 

```
@ti.kernel
def func():
    (a, b) = (c, d) = (1, 2)
```

**Comment by gaocegege** [comment]
Hi @k-ye 

Is this issue related to https://github.com/taichi-dev/taichi/pull/3037/ ?

**Comment by k-ye** [comment]
>  I saw that we do not use build_stmt anymore.

Hey @gaocegege , it's better to get this feature in first. #3037 is much more experimental and a long-term effort, and it should preserve all the features when ready.

**Comment by gaocegege** [comment]
Gotcha. I used to worry that this feature will be useless after #3037 is merged. Thanks for your reply.

**Comment by gaocegege** [comment]
@Ricahrd-Li I can provide one possible solution here. https://github.com/taichi-dev/taichi/pull/3062

If you are still working on it, you can refer to the PR and file a new one. I will close mine.

Thanks.

**Comment by Ricahrd-Li** [comment]
Thanks! @gaocegege Currently I am not working on this issue, thanks a lot for your work!

**Comment by gaocegege** [comment]
Thanks, I will try to address it.
