### ISSUE TITLE
"examples/features/sparse/taichi_bitmasked.py" no longer works

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#2936]
**Describe the bug**
https://github.com/taichi-dev/taichi/blob/master/examples/features/sparse/taichi_bitmasked.py crashes with `AttributeError: 'FieldsBuilder' object has no attribute 'deactivate_all'`

**Minimal Script Reproduce**
```py
import taichi as ti
ti.init()

x = ti.field(ti.f32)
ti.root.bitmasked(ti.i, 1).place(x)

ti.root.deactivate_all()
```

**Error Log**

```
>>> p taichi_bitmasked.py
[Taichi] version 0.7.32, llvm 10.0.0, commit 2f1b5821, linux, python 3.8.10
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "taichi_bitmasked.py", line 7, in <module>
    ti.root.deactivate_all()
  File "/home/yuanming/repos/taichi/python/taichi/lang/impl.py", line 497, in __getattr__
    return getattr(_root_fb, item)
AttributeError: 'FieldsBuilder' object has no attribute 'deactivate_all'
```

**Comment by ljcc0930** [comment]
To my thought, `deactivate_all` should be implemented in `SNodeTree`? @k-ye
