### ISSUE TITLE
`ti.get_addr` is not working for `ti.ndarray`

### ISSUE THREAD

**Issue by ljcc0930** [taichi-dev/taichi#2942]
```py
a = ti.ndarray(dtype=ti.f32, shape=(3, 3))
ti.get_addr(a, [0, 0]) # error
```
Traceback:
```
Traceback (most recent call last):
  File "utils.py", line 95, in <module>
    get_field_info(a)
  File "utils.py", line 82, in get_field_info
    info.data = get_field_addr(field)
  File "utils.py", line 40, in get_field_addr
    addr = get_field_addr_ND(x)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 671, in wrapped
    return primal(*args, **kwargs)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 598, in __call__
    key = self.ensure_compiled(*args)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 589, in ensure_compiled
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 455, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 450, in taichi_ast_generator
    compiled()
  File "utils.py", line 31, in get_field_addr_ND
    return ti.get_addr(x,[0 for _ in x.shape])
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/ops.py", line 962, in get_addr
    return Expr(_ti_core.expr_get_addr(f.snode.ptr, make_expr_group(indices)))
AttributeError: 'ScalarNdarray' object has no attribute 'snode'
```

**Comment by ljcc0930** [comment]
Temporary solution: `a.arr.data_ptr()`

**Comment by strongoier** [comment]
> Temporary solution: `a.arr.data_ptr()`

Yes this is the current way to get the pointer to the underlying storage (torch for now). @qiao-bo is working on a new memory allocator to replace torch. We will determine a proper interface of getting address later.

**Comment by k-ye** [comment]
For now, can we just make `get_attr` support ND-array?

**Comment by strongoier** [comment]
> For now, can we just make `get_attr` support ND-array?

We can do that but this may make `ti.get_addr()` more confusing for users. `ti.get_addr()` itself is a function which can ONLY be called inside a Taichi kernel, and translates to a specific IR for its purpose. Therefore the previous way of using it is to manually write a Taichi kernel which only returns a `ti.get_addr()` and run it. However, getting the pointer of a ndarray is a completely different and much easier thing. We should not try to keep the previous practice.

**Comment by k-ye** [comment]
SG, then how about we add a property to ND-Array itself (e.g. `data_ptr`), so that we avoid first migrating to https://github.com/taichi-dev/taichi/issues/2942#issuecomment-919848896, then another migration?

**Comment by strongoier** [comment]
> SG, then how about we add a property to ND-Array itself (e.g. `data_ptr`), so that we avoid first migrating to [#2942 (comment)](https://github.com/taichi-dev/taichi/issues/2942#issuecomment-919848896), then another migration?

Sounds good.

**Comment by strongoier** [comment]
@ljcc0930 After #2947, for Ndarray `a`,  we'll be using `a.data_ptr` to get the address instead of visiting its internal variables.
