### ISSUE TITLE
arch=ti.opengl not working

### ISSUE THREAD

**Issue by ltt1598** [taichi-dev/taichi#3024]
I find the following code not working when choosing `arch=ti.opengl` on Taichi 0.8.0

``` python
import taichi as ti

ti.init(arch=ti.gpu)

tiField = ti.Vector.field(2, dtype=float, shape=2)
tiField[0] = ti.Vector([0,0])
tiField[1] = ti.Vector([1,1])

m=ti.Vector.field(2,dtype=int,shape=9)

@ti.kernel
def foo():
    for P in ti.grouped(m):
        tiField[P][0]=0
        tiField[P][1]=1

foo()

print(tiField[0])
```

The code works with `ti.cpu` and `ti.cuda`, but not for `ti.opengl`. It generates the following error:
```
[Taichi] version 0.8.0, llvm 10.0.0, commit 181c9039, win, python 3.8.10
[Taichi] Starting on arch=opengl
Traceback (most recent call last):
  File "c:\Users\Tiantian\Downloads\WeChat Files\ltt1598\FileStorage\File\2021-09\test(1).py", line 17, in <module>
    foo()
  File "C:\Users\Tiantian\AppData\Local\Programs\Python\Python38\lib\site-packages\taichi\lang\kernel_impl.py", line 678, in wrapped
    return primal(*args, **kwargs)
  File "C:\Users\Tiantian\AppData\Local\Programs\Python\Python38\lib\site-packages\taichi\lang\kernel_impl.py", line 606, in __call__
    return self.compiled_functions[key](*args)
  File "C:\Users\Tiantian\AppData\Local\Programs\Python\Python38\lib\site-packages\taichi\lang\kernel_impl.py", line 563, in func__
    t_kernel(launch_ctx)
RuntimeError: invalid unordered_map<K, T> key
```

It's also worth mentioning that `ti.gpu` falls back to `ti.opengl` on my laptop without a graphics card, producing the same error.

**Comment by bobcao3** [comment]
#3004

Seems like another multi root related issue. Can you try the Vulkan backend? (env TI_ARCH=Vulkan)

**Comment by yihong0618** [comment]
@bobcao3 maybe add warning for short solution? something like.

in lang/field.py
```python
    def __str__(self):
        if impl.inside_kernel():
            return self.__repr__()  # make pybind11 happy, see Matrix.__str__
        if self.snode.ptr is None:
            return '<Field: Definition of this field is incomplete>'
        else:
            if _ti_core.with_opengl():
                _ti_core.warn("This is actually not supported on OpenGL. With OpenGL you can only print stuff and call tachi kernels after all the structures on GPU are defined.")
            return str(self.to_numpy())

```

**Comment by strongoier** [comment]
@yihong0618 The problem is not only related to `print()`, but all reads/writes to Taichi fields. In this issue, the problem comes from
```python
tiField = ti.Vector.field(2, dtype=float, shape=2)
tiField[0] = ti.Vector([0,0])  # Write to Taichi fields. No more fields can be defined in OpenGL now.
tiField[1] = ti.Vector([1,1])

m=ti.Vector.field(2,dtype=int,shape=9)  # Error
```

**Comment by yihong0618** [comment]
> @yihong0618 The problem is not only related to `print()`, but all reads/writes to Taichi fields. In this issue, the problem comes from
> 
> ```python
> tiField = ti.Vector.field(2, dtype=float, shape=2)
> tiField[0] = ti.Vector([0,0])  # Write to Taichi fields. No more fields can be defined in OpenGL now.
> tiField[1] = ti.Vector([1,1])
> 
> m=ti.Vector.field(2,dtype=int,shape=9)  # Error
> ```

yeah, just one case...for the #3004

**Comment by yihong0618** [comment]
Of course. Will do it later maybe tomorrow.~

**Comment by bobcao3** [comment]
#3018
