### ISSUE TITLE
Can't build Taichi dev. environment on Windows 10

### ISSUE THREAD

**Issue by trevinwong** [taichi-dev/taichi#3045]
**Describe the bug**
When running `python setup.py develop-user`, CMake complains about not being able to find the `C` and `CXX` compiler despite my `PATH` including `clang`.

If I manually set the `CMAKE_C_COMPILER` environment variable, CMake complains about it not being able to compile a simple test program. This doesn't happen with `CMAKE_CXX_COMPILER`.

**To Reproduce**
Run `python setup.py develop-user` after following the installation instructions.

For the second situation, run:
```
cmake -D CMAKE_C_COMPILER=C:/clang/bin/clang.exe
cmake -D CMAKE_CXX_COMPILER=C:/clang/bin/clang.exe
```

before running the above command.

**Log/Screenshots**
```
[]
['taichi', 'taichi.aot', 'taichi.core', 'taichi.lang', 'taichi.misc', 'taichi.profiler', 'taichi.snode', 'taichi.tests', 'taichi.tools', 'taichi.ui']
running develop
running egg_info
writing python\taichi.egg-info\PKG-INFO
writing dependency_links to python\taichi.egg-info\dependency_links.txt
writing entry points to python\taichi.egg-info\entry_points.txt
writing requirements to python\taichi.egg-info\requires.txt
writing top-level names to python\taichi.egg-info\top_level.txt
reading manifest file 'python\taichi.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python\taichi\*.md'
warning: no files found matching 'python\taichi\lib\*.so'
warning: no files found matching 'python\taichi\lib\*.pyd'
warning: no files found matching 'python\taichi\lib\*.bc'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching 'ffmpeg' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'python\taichi.egg-info\SOURCES.txt'
running build_ext
---------- Running CMake prepare ----------------------------------------
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:7 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:7 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/trevi/Desktop/Programming/taichi/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/trevi/Desktop/Programming/taichi/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "C:\Users\trevi\Desktop\Programming\taichi\setup.py", line 223, in <module>
    setup(name=project_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\trevi\Desktop\Programming\taichi\setup.py", line 153, in run
    subprocess.check_call(['cmake', cmake_list_dir] + cmake_args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\trevi\\Desktop\\Programming\\taichi', '-DTI_WITH_VULKAN:BOOL=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\trevi\\Desktop\\Programming\\taichi\\build', '-DPYTHON_EXECUTABLE=C:/Users/trevi/AppData/Local/Mic
rosoft/WindowsApps/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/python.exe', '-DTI_VERSION_MAJOR=0', '-DTI_VERSION_MINOR=8', '-DTI_VERSION_PATCH=0', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

For the second situation, the log looks like:
```
$ python setup.py develop --user
[]
['taichi', 'taichi.aot', 'taichi.core', 'taichi.lang', 'taichi.misc', 'taichi.profiler', 'taichi.snode', 'taichi.tests', 'taichi.tools', 'taichi.ui']
running develop
running egg_info
writing python\taichi.egg-info\PKG-INFO
writing dependency_links to python\taichi.egg-info\dependency_links.txt
writing entry points to python\taichi.egg-info\entry_points.txt
writing requirements to python\taichi.egg-info\requires.txt
writing top-level names to python\taichi.egg-info\top_level.txt
reading manifest file 'python\taichi.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python\taichi\*.md'
warning: no files found matching 'python\taichi\lib\*.so'
warning: no files found matching 'python\taichi\lib\*.pyd'
warning: no files found matching 'python\taichi\lib\*.bc'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching 'ffmpeg' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'python\taichi.egg-info\SOURCES.txt'
running build_ext
---------- Running CMake prepare ----------------------------------------
-- The C compiler identification is Clang 10.0.0 with GNU-like command-line
-- The CXX compiler identification is Clang 10.0.0 with GNU-like command-line
-- Detecting C compiler ABI info
CMake Error: Generator: execution of make failed. Make command was: nmake /nologo cmTC_77d2c\fast &&
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/clang/bin/clang.exe
CMake Error: Generator: execution of make failed. Make command was: nmake /nologo cmTC_5c7dc\fast &&
-- Check for working C compiler: C:/clang/bin/clang.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/clang/bin/clang.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/trevi/Desktop/Programming/taichi/CMakeFiles/CMakeTmp

    Run Build Command(s):nmake /nologo cmTC_5c7dc\fast && The system cannot find the file specified
    Generator: execution of make failed. Make command was: nmake /nologo cmTC_5c7dc\fast &&




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/trevi/Desktop/Programming/taichi/CMakeFiles/CMakeOutput.log".
See also "C:/Users/trevi/Desktop/Programming/taichi/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "C:\Users\trevi\Desktop\Programming\taichi\setup.py", line 223, in <module>
    setup(name=project_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\trevi\Desktop\Programming\taichi\setup.py", line 153, in run
    subprocess.check_call(['cmake', cmake_list_dir] + cmake_args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\trevi\\Desktop\\Programming\\taichi', '-DTI_WITH_VULKAN:BOOL=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\trevi\\Desktop\\Programming\\taichi\\build', '-DPYTHON_EXECUTABLE=C:/Users/trevi/AppData/Local/Mic
rosoft/WindowsApps/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/python.exe', '-DTI_VERSION_MAJOR=0', '-DTI_VERSION_MINOR=8', '-DTI_VERSION_PATCH=0', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

**Additional comments**
My `bin` folder for `clang` is: `C:/clang/bin`.
The lines `export CXX=C:/clang/bin/clang.exe` or `export CC=C:/clang/bin/clang.exe` does not help.

The output of `clang -v`:
```
$ clang -v
clang version 10.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\clang\bin
```

**Comment by ailzhang** [comment]
Hi @trevinwong, thanks for reporting the bug! I checked our windows build log and it seems using MSVC, would you mind giving it a try instead? Thanks! 
```
2021-09-29T05:49:11.2390672Z -- The C compiler identification is MSVC 19.29.30133.0
2021-09-29T05:49:12.9652779Z -- The CXX compiler identification is MSVC 19.29.30133.0
2021-09-29T05:49:13.0205064Z -- Detecting C compiler ABI info
2021-09-29T05:49:13.9463839Z -- Detecting C compiler ABI info - done
2021-09-29T05:49:13.9487515Z -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
2021-09-29T05:49:13.9495539Z -- Detecting C compile features
2021-09-29T05:49:13.9504566Z -- Detecting C compile features - done
2021-09-29T05:49:13.9592336Z -- Detecting CXX compiler ABI info
2021-09-29T05:49:14.8218546Z -- Detecting CXX compiler ABI info - done
2021-09-29T05:49:14.8242315Z -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
2021-09-29T05:49:14.8247250Z -- Detecting CXX compile features
2021-09-29T05:49:14.8256520Z -- Detecting CXX compile features - done
```

**Comment by trevinwong** [comment]
Hi, thanks for the quick response. This is what I get:

```
$ python setup.py develop --user
[]
['taichi', 'taichi.aot', 'taichi.core', 'taichi.lang', 'taichi.misc', 'taichi.pr
ofiler', 'taichi.snode', 'taichi.tests', 'taichi.tools', 'taichi.ui']
running develop
running egg_info
writing python\taichi.egg-info\PKG-INFO
writing dependency_links to python\taichi.egg-info\dependency_links.txt
writing entry points to python\taichi.egg-info\entry_points.txt
writing requirements to python\taichi.egg-info\requires.txt
writing top-level names to python\taichi.egg-info\top_level.txt
reading manifest file 'python\taichi.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python\taichi\*.md'
warning: no files found matching 'python\taichi\lib\*.so'
warning: no files found matching 'python\taichi\lib\*.pyd'
warning: no files found matching 'python\taichi\lib\*.bc'
warning: no previously-included files matching '*.pyc' found anywhere in distrib
ution
warning: no previously-included files matching '*.pyo' found anywhere in distrib
ution
warning: no previously-included files matching 'ffmpeg' found anywhere in distri
bution
adding license file 'LICENSE'
writing manifest file 'python\taichi.egg-info\SOURCES.txt'
running build_ext
---------- Running CMake prepare ----------------------------------------
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeTestCCompile
r.cmake:66 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC
/14.29.30133/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/trevi/Desktop/Programming/taichi/build/CMakeFiles/CMake
Tmp

    Run Build Command(s):nmake /nologo cmTC_5c8af\fast &&       "C:\Program File
s (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hos
tx64\x64\nmake.exe"  -f CMakeFiles\cmTC_5c8af.dir\build.make /nologo -L
         CMakeFiles\cmTC_5c8af.dir\build
    Building C object CMakeFiles/cmTC_5c8af.dir/testCCompiler.c.obj
        C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\
x64\cl.exe @C:\Users\trevi\AppData\Local\Temp\nm575B.tmp
    testCCompiler.c
    Linking C executable cmTC_5c8af.exe
        "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFile
s\cmTC_5c8af.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests -- C:\PROGRA~2\MICRO
S~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo @CMa
keFiles\cmTC_5c8af.dir\objects1.rsp @C:\Users\trevi\AppData\Local\Temp\nm577B.tm
p
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_5c8af.dir/manifest.res CMakeFiles
\cmTC_5c8af.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specifiedNMAKE : fatal error U1077: '"C:\Pro
gram Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\
2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\nmake.exe"' : return co
de '0x2'
    Stop.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/trevi/Desktop/Programming/taichi/build/CMakeFiles/CMakeOutput
.log".
See also "C:/Users/trevi/Desktop/Programming/taichi/build/CMakeFiles/CMakeError.
log".
Traceback (most recent call last):
  File "C:\Users\trevi\Desktop\Programming\taichi\setup.py", line 223, in <modul
e>
    setup(name=project_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.203
2.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 153, in s
etup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.203
2.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.203
2.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.203
2.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.203
2.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\develop.py", line 34
, in run
    self.install_for_development()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.203
2.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\develop.py", line 13
6, in install_for_development
    self.run_command('build_ext')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.203
2.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.203
2.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\trevi\Desktop\Programming\taichi\setup.py", line 153, in run
    subprocess.check_call(['cmake', cmake_list_dir] + cmake_args,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.203
2.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\trevi\\Desktop\\Pr
ogramming\\taichi', '-DTI_WITH_VULKAN:BOOL=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTOR
Y=C:\\Users\\trevi\\Desktop\\Programming\\taichi\\build', '-DPYTHON_EXECUTABLE=C
:/Users/trevi/AppData/Local/Microsoft/WindowsApps/PythonSoftwareFoundation.Pytho
n.3.9_qbz5n2kfra8p0/python.exe', '-DTI_VERSION_MAJOR=0', '-DTI_VERSION_MINOR=8',
 '-DTI_VERSION_PATCH=0', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit s
tatus 1.
```

It looks like it's unable to find my `cmake.exe`. 
I've added `C:/Program Files:/CMake/bin` to my `PATH`, however, and I'm able to call `cmake` from the CLI as well, so I'm not sure what the problem is.

**Comment by bobcao3** [comment]
I think it found your cmake.exe but it failed with calling Visual Studio's nmake. I'm not sure how this happens, but maybe you can try to install the full Visual Studio, then remove the build folder in the taichi repo, and then run `python ./setup.py develop` without `--user` flag from PowerShell (instead of CMD)

Since I can't seem to repro this, I just outlined how I usually get it working, hopefully this fixes it for you.

**Comment by trevinwong** [comment]
I got this output:
```
$ ti test
ERROR: usage: ti [options] [file_or_dir] [file_or_dir] [...]
ti: error: unrecognized arguments: -n 8
  inifile: None
  rootdir: C:\Users\trevi\Desktop\Programming\taichi

[Taichi] version 0.8.0, llvm 10.0.0, commit 4d62961f, win, python 3.10.0

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://taichi.rtfd.io/en/stable
GitHub: https://github.com/taichi-dev/taichi
Forum:  https://forum.taichi.graphics


Running Python tests...

Starting 8 testing thread(s)...
>>> Running time: 0.11s
```

**Comment by trevinwong** [comment]
Yeah I switched over to using a regular Python3.9 installation and everything seemed to work a lot better. Practically no errors and I can run the tests, although I wasn't able to finish all of them because nodes were consistently crashing, but still, looks a lot better than using Python3.10.
