### ISSUE TITLE
real types and integer types don't support support the use of __rmul__ for multiplication 

### ISSUE THREAD

**Issue by FlagerLee** [taichi-dev/taichi#3051]
I tried to overwrite \_\_mul\_\_ and \_\_rmul\_\_ methods to support **class * ti.f64** and **ti.f64 * class** operations, but I failed when doing **ti.f64*class** operation. The code is as follows:

```py
import taichi as ti

ti.init(arch=ti.cuda)

@ti.data_oriented
class test:
    def __init__(self):
        self.x = 2
    
    @ti.func
    def __mul__(self, other):
        return self.x * other

    @ti.func    
    def __rmul__(self, other):
        return self.x * other

@ti.kernel
def tst(a: ti.template(), b: ti.f64):
    print(a * b)
    print(b * a)

tst(test(), 4)
```
It will report the error as shown below：

```
[Taichi] version 0.7.32, llvm 10.0.0, commit 6652f94f, win, python 3.7.4
[I 09/30/21 00:22:08.341 11728] [shell.py:_shell_pop_print@35] Graphical python shell detected, using wrapped sys.stdout
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File "E:\test.py", line 23, in <module>
    tst(test(), 4)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel_impl.py", line 671, in wrapped
    return primal(*args, **kwargs)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\shell.py", line 40, in new_call
    ret = old_call(*args, **kwargs)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel_impl.py", line 598, in __call__
    key = self.ensure_compiled(*args)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel_impl.py", line 589, in ensure_compiled
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel_impl.py", line 455, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\kernel_impl.py", line 450, in taichi_ast_generator
    compiled()
  File "E:\test.py", line 21, in tst
    print(b * a)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\common_ops.py", line 32, in __mul__
    return ti.mul(self, other)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\ops.py", line 78, in wrapped
    return imp_foo(a, b)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\ops.py", line 63, in imp_foo
    return foo(x, y)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\ops.py", line 455, in mul
    return _binary_operation(_ti_core.expr_mul, _bt_ops_mod.mul, a, b)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\ops.py", line 173, in _binary_operation
    a, b = wrap_if_not_expr(a), wrap_if_not_expr(b)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\ops.py", line 36, in wrap_if_not_expr
    return Expr(a) if not is_taichi_expr(a) else a
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\expr.py", line 33, in __init__
    self.ptr = impl.make_constant_expr(arg).ptr
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\util.py", line 196, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\FlagerLee\AppData\Local\Programs\Python\Python37\lib\site-packages\taichi\lang\impl.py", line 414, in make_constant_expr
    raise ValueError(f'Invalid constant scalar expression: {type(val)}')
ValueError: Invalid constant scalar expression: <class '__main__.test'>
```

Same thing happened when I tried to change **ti.f64** to **ti.f32**, **ti.u8** and almost all other basic taichi types. Only when I remove b from the parameter list and replace all variable b into constant 4, the program can ouput two 8.0 normally.

**Comment by victoriacity** [comment]
Classes decorated with `@ti.data_oriented` were designed to be containers of global fields (e.g., `self.x=ti.field(...)`), and they currently cannot be passed as `ti.template()` arguments. The error in the above code snippet indicates that the `test` class is an invalid type in Taichi scope.

The reason why the program gives the correct result with a constant `4` is that the compiler has optimized the kernel into printing a constant number 8.0, then the kernel essentially performs no computation and does not access the `test` class after it is compiled.

**Comment by FlagerLee** [comment]
I got it. So do you have any plans for ti.template() to support custom classes? 
In addition, if I define the class in the kernel instead of passing in ti.template(), there will be the same problem. 
```py
import taichi as ti

ti.init(arch=ti.cuda)

@ti.data_oriented
class test:
    def __init__(self):
        self.x = 2
    
    @ti.func
    def __mul__(self, other):
        return self.x * other

    @ti.func    
    def __rmul__(self, other):
        return self.x * other

@ti.kernel
def tst(b: ti.f64):
    a = test()
    print(a * b)
    print(b * a)

tst(4)
```
The same problem will also occur.

**Comment by FlagerLee** [comment]
> I got it. So do you have any plans for ti.template() to support custom classes? In addition, if I define the class in the kernel instead of passing in ti.template(), there will be the same problem.
> 
> ```python
> import taichi as ti
> 
> ti.init(arch=ti.cuda)
> 
> @ti.data_oriented
> class test:
>     def __init__(self):
>         self.x = 2
>     
>     @ti.func
>     def __mul__(self, other):
>         return self.x * other
> 
>     @ti.func    
>     def __rmul__(self, other):
>         return self.x * other
> 
> @ti.kernel
> def tst(b: ti.f64):
>     a = test()
>     print(a * b)
>     print(b * a)
> 
> tst(4)
> ```
> 
> The same problem will also occur.

So is this a bug or a feature?

**Comment by bobcao3** [comment]
I don't think you can create global fields / data_oriented object from within a kernel, so for the second case it might be caused by that.
