### ISSUE TITLE
taichi0.8.1 ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by bismarckkk** [taichi-dev/taichi#3084]
I installed taichi0.8.1 on Ubuntu 18.04LTS, but when I try  
```python
import taichi
```
I got the following error  
```
Share object taichi_core import failed, check this page for possible solutions:
https://docs.taichi.graphics/docs/lang/articles/misc/install
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bismarck/toptimize/taichi/lib/python3.6/site-packages/taichi/__init__.py", line 4, in <module>
    from taichi.core import *
  File "/home/bismarck/toptimize/taichi/lib/python3.6/site-packages/taichi/core/__init__.py", line 1, in <module>
    from taichi.core.logging import *
  File "/home/bismarck/toptimize/taichi/lib/python3.6/site-packages/taichi/core/logging.py", line 4, in <module>
    from taichi.core import util
  File "/home/bismarck/toptimize/taichi/lib/python3.6/site-packages/taichi/core/util.py", line 127, in <module>
    import_ti_core()
  File "/home/bismarck/toptimize/taichi/lib/python3.6/site-packages/taichi/core/util.py", line 45, in import_ti_core
    raise e from None
  File "/home/bismarck/toptimize/taichi/lib/python3.6/site-packages/taichi/core/util.py", line 33, in import_ti_core
    import taichi_core as core
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/bismarck/toptimize/taichi/lib/python3.6/site-packages/taichi/core/../lib/taichi_core.so)
Consider installing libtinfo5: sudo apt-get install libtinfo5
```
Ubuntu 18.04LTS only have GLIBC 2.27.  
I already read #2439, reverting to 0.7.16 can fix it, but when I upgrade to 0.7.23 this problem is still here .

**Comment by qiao-bo** [comment]
Hi, thanks for raising the issue. Indeed Ubuntu 18.04 comes with GLIBC 2.27, and you will get the above error. Can you circumvent this by using a Docker image (i think either 19.04 or 20.04 should work)? or maybe [build the glibc from source](https://www.linuxfromscratch.org/lfs/view/9.0-systemd/chapter05/glibc.html)?

**Comment by bismarckkk** [comment]
thank you, it works in docker. 
I also try to upgrade my GLIBC, but it make my ubuntu broken, make backup before doing it.
