### ISSUE TITLE
ti.atan2 not support i32

### ISSUE THREAD

**Issue by bismarckkk** [taichi-dev/taichi#3092]
This is the sample code  
```python
import taichi as ti

ti.init()


@ti.kernel
def test():
    i = ti.cast(1, ti.i32)
    print(ti.atan2(i, 1))


if __name__ == '__main__':
    test()
```
It got error  
```
[Taichi] version 0.8.1, llvm 10.0.0, commit cc2dd342, win, python 3.8.6
[Taichi] Starting on arch=x64
[I 10/06/21 14:14:16.452 22884] [codegen_llvm.cpp:taichi::lang::CodeGenLLVM::visit@499] 
data_type_name(ret_type): i32
[E 10/06/21 14:14:16.452 22884] [codegen_llvm.cpp:taichi::lang::CodeGenLLVM::visit@500] Not supported.


***********************************
* Taichi Compiler Stack Traceback *
***********************************
0x7ffc3243925a: taichi::print_traceback in taichi_core.pyd
0x7ffc32309959: PyInit_taichi_core in taichi_core.pyd
0x7ffc322ebf8e: PyInit_taichi_core in taichi_core.pyd
0x7ffc322ee3fb: PyInit_taichi_core in taichi_core.pyd
0x7ffc3255876a: taichi::print_traceback in taichi_core.pyd
0x7ffc322ee3fb: PyInit_taichi_core in taichi_core.pyd
0x7ffc322e3c9b: PyInit_taichi_core in taichi_core.pyd
0x7ffc322e4279: PyInit_taichi_core in taichi_core.pyd
0x7ffc32557956: taichi::print_traceback in taichi_core.pyd
0x7ffc322cec3b: PyInit_taichi_core in taichi_core.pyd
0x7ffc3239fad6: PyInit_taichi_core in taichi_core.pyd
0x7ffc323d4db8: PyInit_taichi_core in taichi_core.pyd
0x7ffc323bfd35: PyInit_taichi_core in taichi_core.pyd
0x7ffc323bf713: PyInit_taichi_core in taichi_core.pyd
0x7ffc324524d5: taichi::print_traceback in taichi_core.pyd
0x7ffc3231309b: PyInit_taichi_core in taichi_core.pyd
0x7ffc32451c86: taichi::print_traceback in taichi_core.pyd
0x7ffc324962a6: taichi::print_traceback in taichi_core.pyd
0x7ffc3244f4e5: taichi::print_traceback in taichi_core.pyd
0x7ffc3244ebf7: taichi::print_traceback in taichi_core.pyd
0x7ffc323c0856: PyInit_taichi_core in taichi_core.pyd
0x7ffc3239fab1: PyInit_taichi_core in taichi_core.pyd
0x7ffc323d4db8: PyInit_taichi_core in taichi_core.pyd
0x7ffc323bfd35: PyInit_taichi_core in taichi_core.pyd
0x7ffc323bf713: PyInit_taichi_core in taichi_core.pyd
0x7ffc3225309e: PyInit_taichi_core in taichi_core.pyd
0x7ffc321cf576: PyInit_taichi_core in taichi_core.pyd
0x7ffc3219838d: pybind11::error_already_set::discard_as_unraisable in taichi_core.pyd
0x7ffc932e2af4: PyCFunction_Call in python38.dll
0x7ffc932e413a: PyObject_MakeTpCall in python38.dll
0x7ffc934128eb: Py_gitversion in python38.dll
0x7ffc9331fa6a: PyVectorcall_Call in python38.dll
0x7ffc9331e091: PyObject_Call in python38.dll
0x7ffc9343179f: Py_gitversion in python38.dll
0x7ffc933018f7: PyEval_EvalFrameDefault in python38.dll
0x7ffc932fa278: PyEval_EvalCodeWithName in python38.dll
0x7ffc932fba0f: PyFunction_Vectorcall in python38.dll
0x7ffc9331fa6a: PyVectorcall_Call in python38.dll
0x7ffc9331f8fb: PySequence_GetItem in python38.dll
0x7ffc933024bc: PyEval_EvalFrameDefault in python38.dll
0x7ffc932fa278: PyEval_EvalCodeWithName in python38.dll
0x7ffc932fba0f: PyFunction_Vectorcall in python38.dll
0x7ffc93376424: PyObject_FastCallDict in python38.dll
0x7ffc93375e36: PyObject_Call_Prepend in python38.dll
0x7ffc93375da5: PyModule_GetFilenameObject in python38.dll
0x7ffc9331f977: PySequence_GetItem in python38.dll
0x7ffc933024bc: PyEval_EvalFrameDefault in python38.dll
0x7ffc932fa278: PyEval_EvalCodeWithName in python38.dll
0x7ffc93300601: PyEval_EvalFrameDefault in python38.dll
0x7ffc932fa278: PyEval_EvalCodeWithName in python38.dll
0x7ffc93337edf: PyEval_EvalCodeEx in python38.dll
0x7ffc93337e3d: PyEval_EvalCode in python38.dll
0x7ffc93337a02: PyFuture_FromASTObject in python38.dll
0x7ffc93337991: PyFuture_FromASTObject in python38.dll
0x7ffc93342f6c: PyRun_FileExFlags in python38.dll
0x7ffc9334342b: PyRun_SimpleFileExFlags in python38.dll
0x7ffc934a66cf: PyRun_AnyFileExFlags in python38.dll
0x7ffc934557dd: Py_gitversion in python38.dll
0x7ffc9339b40c: Py_RunMain in python38.dll
0x7ffc9339b295: Py_RunMain in python38.dll
0x7ffc9339accd: Py_Main in python38.dll
0x7ff6cbb61258: Unknown Function in python.exe
0x7ffcfa5c54e0: BaseThreadInitThunk in KERNEL32.DLL
0x7ffcfb96485b: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/docs/lang/articles/misc/install
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    test()
  File "C:\Users\Bismarck\AppData\Local\Programs\Python\Python38\lib\site-packages\taichi\lang\kernel_impl.py", line 669, in wrapped
    return primal(*args, **kwargs)
  File "C:\Users\Bismarck\AppData\Local\Programs\Python\Python38\lib\site-packages\taichi\lang\kernel_impl.py", line 597, in __call__
    return self.compiled_functions[key](*args)
  File "C:\Users\Bismarck\AppData\Local\Programs\Python\Python38\lib\site-packages\taichi\lang\kernel_impl.py", line 554, in func__
    t_kernel(launch_ctx)
RuntimeError: [codegen_llvm.cpp:taichi::lang::CodeGenLLVM::visit@500] Not supported.

Process finished with exit code 1
```
If I use `ti.atan2(1, 1)`, it run normally.  

BTW, the doc of atan2 maybe outdated, I test `ti.atan2(1, 0)` and it got right result which doc say it don't work.

**Comment by bobcao3** [comment]
In C++ atan2 is specified as https://en.cppreference.com/w/cpp/numeric/math/atan2
Which specifies that if i32 inputs are used, they will be cast to double and therefore have a FP return type.

So I think to address this issue, either we need to also specify that inputs to atan2 must be FP, or we need to automatically cast them to FP.

As for why `ti.atan2(1,2)` worked:
Both 1 and 2 are treated as python statements, so the value is evaluated from within Python and therefore actually uses Python's atan2 rule. (https://github.com/taichi-dev/taichi/blob/34451abeb244882b2c82e0a66863144de43259ca/python/taichi/lang/ops.py#L170) Maybe we should also do automatic type casting to conform with most languages' definitions out there?

**Comment by yuanming-hu** [comment]
Bumping this up given multiple users run into this issue during the voxel challenge. @ailzhang could you help ensure this issue gets assigned in the next round of issue triage?
