### ISSUE TITLE
Cannot instantiate SparseSolver

### ISSUE THREAD

**Issue by ma-sadeghi** [taichi-dev/taichi#3168]
**Describe the bug**
Cannot instantiate SparseSolver.

**To Reproduce**
```py
import taichi as ti
solver = ti.SparseSolver(solver_type="LU")
```

**Log/Screenshots**
```bash
$ python my_sample_code.py
[Taichi] version 0.8.2, llvm 10.0.0, commit bfa5c28b, linux, python 3.8.12
Traceback (most recent call last):
  File "taichi_spsolver.py", line 2, in <module>
    solver = ti.SparseSolver(solver_type="LU")
  File "/home/amin/mambaforge/envs/test/lib/python3.8/site-packages/taichi/linalg/sparse_solver.py", line 21, in __init__
    taichi_arch = taichi.lang.impl.get_runtime().prog.config.arch
AttributeError: 'NoneType' object has no attribute 'config'
```

**Comment by ma-sadeghi** [comment]
Great, thanks :)
