### ISSUE TITLE
`build_requires` pylint, pytest and various other dependencies leak into whl

### ISSUE THREAD

**Issue by cloudhan** [taichi-dev/taichi#3173]
`pylint` and `pytest` and various `build_requires` leak into final package.

To reproduce, in a fresh virtual environment, install taichi 0.8.2.
```
(base) cloud@LAPTOP-GU603HR PS C:\Users\cloud
> pip install taichi
Collecting taichi
  Downloading taichi-0.8.2-cp39-cp39-win_amd64.whl (21.6 MB)
     |████████████████████████████████| 21.6 MB 2.2 MB/s
Collecting pybind11>=2.5.0
  Downloading pybind11-2.8.0-py2.py3-none-any.whl (207 kB)
     |████████████████████████████████| 207 kB 3.3 MB/s
Collecting astor
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting numpy
  Using cached numpy-1.21.2-cp39-cp39-win_amd64.whl (14.0 MB)
Collecting sourceinspect>=0.0.4
  Downloading sourceinspect-0.0.4-py3-none-any.whl (3.5 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting dill
  Using cached dill-0.3.4-py2.py3-none-any.whl (86 kB)
Installing collected packages: dill, sourceinspect, pybind11, numpy, colorama, astor, taichi
Successfully installed astor-0.8.1 colorama-0.4.4 dill-0.3.4 numpy-1.21.2 pybind11-2.8.0 sourceinspect-0.0.4 taichi-0.8.2
(base) cloud@LAPTOP-GU603HR PS C:\Users\cloud
> python
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi as ti
[Taichi] version 0.8.2, llvm 10.0.0, commit bfa5c28b, win, python 3.9.5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cloud\miniconda3\lib\site-packages\taichi\__init__.py", line 8, in <module>
    from taichi.main import main
  File "C:\Users\cloud\miniconda3\lib\site-packages\taichi\main.py", line 15, in <module>
    import pylint.lint
ModuleNotFoundError: No module named 'pylint'
>>> ^Z

(base) cloud@LAPTOP-GU603HR PS C:\Users\cloud
> pip install pylint
Collecting pylint
  Downloading pylint-2.11.1-py3-none-any.whl (392 kB)
     |████████████████████████████████| 392 kB 504 kB/s
Collecting typing-extensions>=3.10.0
  Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting platformdirs>=2.2.0
  Downloading platformdirs-2.4.0-py3-none-any.whl (14 kB)
Collecting toml>=0.7.1
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting astroid<2.9,>=2.8.0
  Downloading astroid-2.8.2-py3-none-any.whl (246 kB)
     |████████████████████████████████| 246 kB 384 kB/s
Collecting mccabe<0.7,>=0.6
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting isort<6,>=4.2.5
  Downloading isort-5.9.3-py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 547 kB/s
Requirement already satisfied: colorama in c:\users\cloud\miniconda3\lib\site-packages (from pylint) (0.4.4)
Collecting wrapt<1.13,>=1.11
  Using cached wrapt-1.12.1-cp39-cp39-win_amd64.whl
Collecting lazy-object-proxy>=1.4.0
  Downloading lazy_object_proxy-1.6.0-cp39-cp39-win_amd64.whl (22 kB)
Requirement already satisfied: setuptools>=20.0 in c:\users\cloud\miniconda3\lib\site-packages (from astroid<2.9,>=2.8.0->pylint) (52.0.0.post20210125)
Installing collected packages: wrapt, typing-extensions, lazy-object-proxy, toml, platformdirs, mccabe, isort, astroid, pylint
Successfully installed astroid-2.8.2 isort-5.9.3 lazy-object-proxy-1.6.0 mccabe-0.6.1 platformdirs-2.4.0 pylint-2.11.1 toml-0.10.2 typing-extensions-3.10.0.2 wrapt-1.12.1
(base) cloud@LAPTOP-GU603HR PS C:\Users\cloud
> python
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi as ti
[Taichi] version 0.8.2, llvm 10.0.0, commit bfa5c28b, win, python 3.9.5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cloud\miniconda3\lib\site-packages\taichi\__init__.py", line 8, in <module>
    from taichi.main import main
  File "C:\Users\cloud\miniconda3\lib\site-packages\taichi\main.py", line 16, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
>>> ^Z

(base) cloud@LAPTOP-GU603HR PS C:\Users\cloud
> pip install pytest
Collecting pytest
  Downloading pytest-6.2.5-py3-none-any.whl (280 kB)
     |████████████████████████████████| 280 kB 437 kB/s
Collecting atomicwrites>=1.0
  Downloading atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: toml in c:\users\cloud\miniconda3\lib\site-packages (from pytest) (0.10.2)
Collecting attrs>=19.2.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting packaging
  Downloading packaging-21.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 201 kB/s
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Requirement already satisfied: colorama in c:\users\cloud\miniconda3\lib\site-packages (from pytest) (0.4.4)
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting py>=1.8.2
  Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 1.6 MB/s
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 918 kB/s
Installing collected packages: pyparsing, py, pluggy, packaging, iniconfig, attrs, atomicwrites, pytest
Successfully installed atomicwrites-1.4.0 attrs-21.2.0 iniconfig-1.1.1 packaging-21.0 pluggy-1.0.0 py-1.10.0 pyparsing-2.4.7 pytest-6.2.5
(base) cloud@LAPTOP-GU603HR PS C:\Users\cloud
> python
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi as ti
[Taichi] version 0.8.2, llvm 10.0.0, commit bfa5c28b, win, python 3.9.5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cloud\miniconda3\lib\site-packages\taichi\__init__.py", line 8, in <module>
    from taichi.main import main
  File "C:\Users\cloud\miniconda3\lib\site-packages\taichi\main.py", line 18, in <module>
    import taichi.code_format
  File "C:\Users\cloud\miniconda3\lib\site-packages\taichi\code_format.py", line 10, in <module>
    from git import Repo
ModuleNotFoundError: No module named 'git'
>>> ^Z
```

**Comment by k-ye** [comment]
Thanks! Known problem, will make a new release for this fix
