### ISSUE TITLE
taichi0.8.2 ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found. Win10 WSL2 Ubuntu

### ISSUE THREAD

**Issue by ysh329** [taichi-dev/taichi#3174]
```shell
i$ pip install taichi
Collecting taichi
  Downloading taichi-0.8.2-cp39-cp39-manylinux1_x86_64.whl (26.5 MB)
     |████████████████████████████████| 26.5 MB 577 kB/s
Requirement already satisfied: astor in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi) (0.8.1)
Requirement already satisfied: colorama in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi) (0.4.4)
Requirement already satisfied: numpy in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi) (1.21.2)
Requirement already satisfied: pybind11>=2.5.0 in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi) (2.8.0)
Requirement already satisfied: sourceinspect>=0.0.4 in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi) (0.0.4)
Requirement already satisfied: dill in /home/stayua01/miniforge3/lib/python3.9/site-packages (from sourceinspect>=0.0.4->taichi) (0.3.4)
Installing collected packages: taichi
Successfully installed taichi-0.8.2

$ python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi
Share object taichi_core import failed, check this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/__init__.py", line 3, in <module>
    import taichi.ad as ad
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/ad.py", line 1, in <module>
    from taichi.lang import impl
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/lang/__init__.py", line 10, in <module>
    import taichi.lang.linalg_impl
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/lang/linalg_impl.py", line 1, in <module>
    from taichi.core.util import ti_core as _ti_core
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/__init__.py", line 1, in <module>
    from taichi.core.util import *
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/util.py", line 115, in <module>
    import_ti_core()
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/util.py", line 61, in import_ti_core
    raise e from None
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/util.py", line 50, in import_ti_core
    import taichi_core as core  # pylint: disable=C0415
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so)
Consider installing libtinfo5: sudo apt-get install libtinfo5
```

According to the tip `sudo apt-get install libtinfo5`, same error still exits.

## Env

- Win10 WSL2 Ubuntu18.04
- Python3.9 miniconda

```shell
$ strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_PRIVATE
```

Indeed, 2.29 is not found.

## Log

I read #3084 and #2439.

### Try1: install 0.7.16 verison

Failed to install version 0.7.16 as below, so I installed 0.7.21 but error still exists.

```shell
$ pip install taichi==0.7.16
ERROR: Could not find a version that satisfies the requirement taichi==0.7.16 (from versions: 0.7.21, 0.7.22, 0.7.23, 0.7.24, 0.7.26, 0.7.28, 0.7.29, 0.7.30, 0.7.31, 0.7.32, 0.8.0, 0.8.1, 0.8.2)
ERROR: No matching distribution found for taichi==0.7.16
(base) stayua01@100013000760:~/code/taichi$ pip install taichi==0.7.21
Collecting taichi==0.7.21
  Downloading taichi-0.7.21-cp39-cp39-manylinux1_x86_64.whl (21.5 MB)
     |████████████████████████████████| 21.5 MB 4.5 MB/s
Requirement already satisfied: astor in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi==0.7.21) (0.8.1)
Requirement already satisfied: colorama in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi==0.7.21) (0.4.4)
Requirement already satisfied: pybind11>=2.5.0 in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi==0.7.21) (2.8.0)
Requirement already satisfied: numpy in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi==0.7.21) (1.21.2)
Requirement already satisfied: sourceinspect>=0.0.4 in /home/stayua01/miniforge3/lib/python3.9/site-packages (from taichi==0.7.21) (0.0.4)
Requirement already satisfied: dill in /home/stayua01/miniforge3/lib/python3.9/site-packages (from sourceinspect>=0.0.4->taichi==0.7.21) (0.3.4)
Installing collected packages: taichi
  Attempting uninstall: taichi
    Found existing installation: taichi 0.8.1
    Uninstalling taichi-0.8.1:
      Successfully uninstalled taichi-0.8.1
Successfully installed taichi-0.7.21

$ python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taichi
[Taichi] mode=release
Share object taichi_core import failed, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.core import *
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/__init__.py", line 1, in <module>
    from taichi.core.logging import *
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/logging.py", line 4, in <module>
    from taichi.core import util
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/util.py", line 171, in <module>
    import_ti_core()
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/util.py", line 48, in import_ti_core
    raise e from None
  File "/home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/util.py", line 36, in import_ti_core
    import taichi_core as core
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/stayua01/miniforge3/lib/python3.9/site-packages/taichi/core/../lib/taichi_core.so)
Consider installing libtinfo5: sudo apt-get install libtinfo5
```

Any advice? Try docker? I just worry about the performance about docker in WSL2.

**Comment by ysh329** [comment]
Maybe I'll try Ubuntu20.04 in WSL2.

**Comment by k-ye** [comment]
Thanks for reporting this! Sry our Ubuntu 18.04 build machine has been experiencing problems these days, fixing 😂

**Comment by k-ye** [comment]
Now that https://github.com/taichi-dev/taichi/pull/3291 is in, let's migrate the nightly/official release pipelines before the next official release :-) https://github.com/taichi-dev/taichi/blob/master/.github/workflows/release.yml

**Comment by syguan96** [comment]
How to solve this problem? I have tried 0.8.0 to 0.8.4, and all released versions have this problem. My system is Ubuntu 18.04.

**Comment by qiao-bo** [comment]
> How to solve this problem? I have tried 0.8.0 to 0.8.4, and all released versions have this problem. My system is Ubuntu 18.04.

Hi, sorry that the problem still exists on 18.04. It should be fixed in the next release. For now, can you try to [build from source](https://docs.taichi.graphics/lang/articles/contribution/dev_install) or use a docker image with 20.04 to bypass the issue?

**Comment by syguan96** [comment]
Okay, I will try to build from source. BTW, does the taichi team have a plan to fix this problem?

**Comment by qiao-bo** [comment]
> Okay, I will try to build from source. BTW, does the taichi team have a plan to fix this problem?

Hi, thanks for your understanding. Yes, we are on our way (almost there) to containerize CI/CD. Hopefully it will be fixed in the next release. ;)

**Comment by qiao-bo** [comment]
Hi, we have containerized our CI/CD and the GLIBC 2.29 problem should be fixed. Release 0.8.5 should work on both Ubuntu 18.04 and 20.04. Please let us know if it solved your problem. Thanks!

**Comment by syguan96** [comment]
Hi @qiao-bo, the problem has been solved.  Thank you all for your contribution!

**Comment by qiao-bo** [comment]
@syguan96, you'er welcome. Just let us know if further problem arises.
