### ISSUE TITLE
Failed to install dev version: Running CMake prepare CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

### ISSUE THREAD

**Issue by ysh329** [taichi-dev/taichi#3182]
## Env

- Win10 WSL2 Ubuntu20.04
- miniconda python 3.9

## Log

I followed the doc about install taichi-dev-version: https://docs.taichi.graphics/lang/articles/contribution/dev_install. However, failed with logs as below:

```shell
~/code/taichi$ python3 setup.py develop --user
[]
['taichi', 'taichi.tests', 'taichi.snode', 'taichi.type', 'taichi.ui', 'taichi.lang', 'taichi.linalg', 'taichi.core', 'taichi.profiler', 'taichi.aot', 'taichi.tools', 'taichi.misc', 'taichi.lang.ast']
running develop
running egg_info
writing python/taichi.egg-info/PKG-INFO
writing dependency_links to python/taichi.egg-info/dependency_links.txt
writing entry points to python/taichi.egg-info/entry_points.txt
writing requirements to python/taichi.egg-info/requires.txt
writing top-level names to python/taichi.egg-info/top_level.txt
reading manifest file 'python/taichi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python/taichi/*.md'
warning: no files found matching 'python/taichi/assets/*'
warning: no files found matching 'python/taichi/lib/*.so'
warning: no files found matching 'python/taichi/lib/*.pyd'
warning: no files found matching 'python/taichi/lib/*.bc'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching 'ffmpeg' found anywhere in distribution
writing manifest file 'python/taichi.egg-info/SOURCES.txt'
running build_ext
---------- Running CMake prepare ----------------------------------------
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/stayua01/code/taichi/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/home/stayua01/code/taichi/setup.py", line 223, in <module>
    setup(name=project_name,
  File "/home/stayua01/software/miniconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/stayua01/software/miniconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/stayua01/software/miniconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/stayua01/code/taichi/setup.py", line 153, in run
    subprocess.check_call(['cmake', cmake_list_dir] + cmake_args,
  File "/home/stayua01/software/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/stayua01/code/taichi', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/stayua01/code/taichi/build', '-DPYTHON_EXECUTABLE=/home/stayua01/software/miniconda3/bin/python3', '-DTI_VERSION_MAJOR=0', '-DTI_VERSION_MINOR=8', '-DTI_VERSION_PATCH=2', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

**Comment by ysh329** [comment]
Any adivice? Thanks
