### ISSUE TITLE
Dev version build failed: t is detected that you are using gcc as the compiler.  This is an experimental feature.  Consider adding -DCMAKE_CXX_COMPILER=clang argument

### ISSUE THREAD

**Issue by ysh329** [taichi-dev/taichi#3184]
## Env

1. Win10 WSL2 Ubuntu20.04
2. minicnoda py3.9

## Log

When I follow this doc to build Taichi
https://docs.taichi.graphics/lang/articles/contribution/dev_install#installing-dependencies

```shell
it is detected that you are using gcc as the compiler.  This is an
  experimental feature.  Consider adding -DCMAKE_CXX_COMPILER=clang argument
```

how to switch to llvm compiler, thanks

```shell
:~/code/taichi$ python3 setup.py develop --user
[]
['taichi', 'taichi.tests', 'taichi.snode', 'taichi.type', 'taichi.ui', 'taichi.lang', 'taichi.linalg', 'taichi.core', 'taichi.profiler', 'taichi.aot', 'taichi.tools', 'taichi.misc', 'taichi.lang.ast']
running develop
running egg_info
writing python/taichi.egg-info/PKG-INFO
writing dependency_links to python/taichi.egg-info/dependency_links.txt
writing entry points to python/taichi.egg-info/entry_points.txt
writing requirements to python/taichi.egg-info/requires.txt
writing top-level names to python/taichi.egg-info/top_level.txt
reading manifest file 'python/taichi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python/taichi/*.md'
warning: no files found matching 'python/taichi/assets/*'
warning: no files found matching 'python/taichi/lib/*.so'
warning: no files found matching 'python/taichi/lib/*.pyd'
warning: no files found matching 'python/taichi/lib/*.bc'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching 'ffmpeg' found anywhere in distribution
writing manifest file 'python/taichi.egg-info/SOURCES.txt'
running build_ext
---------- Running CMake prepare ----------------------------------------
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Taichi Version 0.8.2
       Commit 6972a706f7e79e265cec947ff7f0011690fafe67
Using /home/stayua01/software/miniconda3/bin/python3 as python executable.
Python 3.9.5
    version: 3.9
    include: /home/stayua01/software/miniconda3/include/python3.9
    library: /home/stayua01/software/miniconda3/lib/libpython3.9.so
    gitpython version: 3.1.24
    numpy include: /home/stayua01/software/miniconda3/lib/python3.9/site-packages/numpy/core/include
    pybind11 include: /home/stayua01/software/miniconda3/lib/python3.9/site-packages/pybind11/include;/home/stayua01/software/miniconda3/lib/python3.9/site-packages/pybind11/include
Using C++ compiler: /usr/bin/c++
GNU compiler detected. Using std=c++17.
CMake Warning at cmake/TaichiCXXFlags.cmake:30 (message):
  It is detected that you are using gcc as the compiler.  This is an
  experimental feature.  Consider adding -DCMAKE_CXX_COMPILER=clang argument
  to CMake to switch to clang (or MSVC on Windows).
Call Stack (most recent call first):
  CMakeLists.txt:52 (include)


Building for processor x86_64
Setting -march=nehalem for x86_64 processors
Using float32 (single) precision as real
CMake Warning at cmake/TaichiCore.cmake:44 (message):
  external/glad submodule not detected.  Settings TI_WITH_OPENGL to OFF.
Call Stack (most recent call first):
  CMakeLists.txt:53 (include)


-- Found LLVM 10.0.0
-- Using LLVMConfig.cmake in: /home/stayua01/software/taichi-llvm-10.0.0-linux/lib/cmake/llvm
LLVM include dirs /home/stayua01/software/taichi-llvm-10.0.0-linux/include
LLVM library dirs /home/stayua01/software/taichi-llvm-10.0.0-linux/lib
-- TI_WITH_CUDA_TOOLKIT = OFF
CMake Error at cmake/TaichiCore.cmake:264 (add_subdirectory):
  The source directory

    /home/stayua01/code/taichi/external/SPIRV-Cross

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:53 (include)


PYTHON_LIBRARIES: /home/stayua01/software/miniconda3/lib/libpython3.9.so
C++ Flags:  -DTI_ISE_NONE -std=c++17 -fsized-deallocation -Wno-class-memaccess -Wno-comment -Wno-sign-compare -Wall  -march=nehalem -DTI_ARCH_x64 -DTI_PASS_EXCEPTION_TO_PYTHON -DTI_INCLUDED -DTI_WITH_CUDA -DTI_WITH_CC
Build type: Release
python=/home/stayua01/software/miniconda3/bin/python3
-- Configuring incomplete, errors occurred!
See also "/home/stayua01/code/taichi/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/home/stayua01/code/taichi/setup.py", line 223, in <module>
    setup(name=project_name,
  File "/home/stayua01/software/miniconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/stayua01/software/miniconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/stayua01/software/miniconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/stayua01/code/taichi/setup.py", line 153, in run
    subprocess.check_call(['cmake', cmake_list_dir] + cmake_args,
  File "/home/stayua01/software/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/stayua01/code/taichi', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/stayua01/code/taichi/build', '-DPYTHON_EXECUTABLE=/home/stayua01/software/miniconda3/bin/python3', '-DTI_VERSION_MAJOR=0', '-DTI_VERSION_MINOR=8', '-DTI_VERSION_PATCH=2', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

**Comment by strongoier** [comment]
Hi, if you follow https://docs.taichi.graphics/lang/articles/contribution/dev_install#setting-up-taichi-for-development, you will see `# export CXX=/path/to/clang  # Uncomment if clang is not system default compiler.` in the 4th line of the 1st step.
