### ISSUE TITLE
dev installation build from source failed: /usr/bin/ld: cannot find -lz

### ISSUE THREAD

**Issue by ysh329** [taichi-dev/taichi#3293]
## Env

1. Win10 WSL2 Ubuntu20.04
2. minicnoda py3.9

## Log

Execute commands below:

```shell
python3 -m pip install --user -r requirements_dev.txt
export CMAKE_CXX_COMPILER_ID="Clang"
export CMAKE_CXX_COMPILER="/usr/bin/clang++-8"
export CXX="/usr/bin/clang++-8"
export -DCMAKE_CXX_COMPILER=${CXX}
python3 setup.py develop --user
```

Logs as below:

```shell
[ 97%] Building CXX object CMakeFiles/taichi_core.dir/taichi/python/export_ggui.cpp.o
[ 97%] Building CXX object CMakeFiles/taichi_core.dir/taichi/python/export_lang.cpp.o
[ 97%] Building CXX object CMakeFiles/taichi_core.dir/taichi/python/export_math.cpp.o
[ 98%] Building CXX object CMakeFiles/taichi_core.dir/taichi/python/export_misc.cpp.o
[ 98%] Building CXX object CMakeFiles/taichi_core.dir/taichi/python/export_visual.cpp.o
[ 99%] Building CXX object CMakeFiles/taichi_core.dir/taichi/python/interfaces_registry.cpp.o
[ 99%] Building CXX object CMakeFiles/taichi_core.dir/taichi/python/memory_usage_monitor.cpp.o
[100%] Building CXX object CMakeFiles/taichi_core.dir/taichi/python/py_exception_translator.cpp.o
[100%] Building CXX object CMakeFiles/taichi_core.dir/taichi/python/snode_registry.cpp.o
[100%] Linking CXX shared library libtaichi_core.so
/usr/bin/ld: cannot find -lz
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/taichi_core.dir/build.make:690: libtaichi_core.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:242: CMakeFiles/taichi_core.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/home/stayua01/code/taichi/setup.py", line 225, in <module>
    setup(name=project_name,
  File "/home/stayua01/software/miniconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/stayua01/software/miniconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/stayua01/software/miniconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/stayua01/software/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/stayua01/code/taichi/setup.py", line 159, in run
    subprocess.check_call(cmake_cmd, cwd=self.build_temp)
  File "/home/stayua01/software/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.
```

**Comment by ysh329** [comment]
> I also ran into this problem the other day. Could you try `sudo apt install zlib1g-dev`?

Great && Fixed!!!
