### ISSUE TITLE
Out of cuda memory

### ISSUE THREAD

**Issue by DQSSSSS** [taichi-dev/taichi#3356]
**Describe the bug**
Run program that needs 2GB memory, it shows CUDA_ERROR_OUT_OF_MEMORY.

**To Reproduce**
Run code below.

```py
import taichi as ti

ti.init(arch=ti.cuda, device_memory_GB=7, device_memory_fraction=0.9)

x = ti.field(dtype=ti.i16)

ti.root.pointer(ti.i, 1024).dense(ti.i, 1024 * 1024).place(x)
# A sparse array. Each dense block is 2MB in size.

# Populate 1024 * 2MB = 2GB memory
def populate():
  for k in range(1024):
    x[k * 1024 * 1024] = 1

populate()
```

**Log/Screenshots**

```
$ python 1.py
[Taichi] version 0.8.4, llvm 10.0.0, commit 895881b5, win, python 3.8.8
[W 11/02/21 21:31:32.224 3504] ti.init argument "device_memory_GB" overridden by environment variable TI_DEVICE_MEMORY_GB=7
[Taichi] Starting on arch=cuda
[E 11/02/21 21:31:34.168 3504] [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void * *,unsigned __int64>::operator ()@86] CUDA Error CUDA_ERROR_OUT_OF_MEMORY: out of memory while calling malloc (cuMemAlloc_v2)


***********************************
* Taichi Compiler Stack Traceback *
***********************************
0x7ffdb4d9076a: taichi::print_traceback in taichi_core.pyd
0x7ffdb4c5f319: PyInit_taichi_core in taichi_core.pyd
0x7ffdb4ec50ca: taichi::print_traceback in taichi_core.pyd
0x7ffdb4cf7d35: PyInit_taichi_core in taichi_core.pyd
0x7ffdb4b9d781: PyInit_taichi_core in taichi_core.pyd
0x7ffdb4b1d6d6: PyInit_taichi_core in taichi_core.pyd
0x7ffdb4ae6d9b: pybind11::error_already_set::discard_as_unraisable in taichi_core.pyd
0x7ffdd0a0a054: PyCFunction_Call in python38.dll
0x7ffdd09dc4cc: PyObject_MakeTpCall in python38.dll
0x7ffdd0b361db: Py_FatalError in python38.dll
0x7ffdd0a1e306: Py_CheckFunctionResult in python38.dll
0x7ffdd0a208c7: PyEval_EvalFrameDefault in python38.dll
0x7ffdd0a1bbd8: PyEval_EvalCodeWithName in python38.dll
0x7ffdd0a1e946: Py_CheckFunctionResult in python38.dll
0x7ffdd0a20cfe: PyEval_EvalFrameDefault in python38.dll
0x7ffdd0a1bbd8: PyEval_EvalCodeWithName in python38.dll
0x7ffdd0a4822b: PyEval_EvalCodeEx in python38.dll
0x7ffdd0a48189: PyEval_EvalCode in python38.dll
0x7ffdd0a47eb6: PyFuture_FromASTObject in python38.dll
0x7ffdd0a47e45: PyFuture_FromASTObject in python38.dll
0x7ffdd0a97a1f: PyDict_DelItemString in python38.dll
0x7ffdd0a977e0: PyRun_SimpleFileExFlags in python38.dll
0x7ffdd0a976ab: PyRun_SimpleFileExFlags in python38.dll
0x7ffdd0bc5297: PyRun_AnyFileExFlags in python38.dll
0x7ffdd0b6f433: Py_FatalError in python38.dll
0x7ffdd0ac4968: Py_RunMain in python38.dll
0x7ffdd0ac47f1: Py_RunMain in python38.dll
0x7ffdd0ac453e: PyArgv_AsWstrList in python38.dll
0x7ffdd0b188b9: Py_Main in python38.dll
0x7ff7013c1268: Unknown Function in python.exe
0x7ffe36f56ab0: BaseThreadInitThunk in KERNEL32.DLL
0x7ffe37a71dbb: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install
Traceback (most recent call last):
  File "c:/XXX/1.py", line 3, in <module>
    ti.init(arch=ti.cuda, device_memory_GB=7, device_memory_fraction=0.9)
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\lang\__init__.py", line 548, in init
    impl.get_runtime().prog.materialize_runtime()
RuntimeError: [taichi/backends/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void * *,unsigned __int64>::operator ()@86] CUDA Error CUDA_ERROR_OUT_OF_MEMORY: out of memory while calling malloc (cuMemAlloc_v2)

```

**Comment by DQSSSSS** [comment]
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.19       Driver Version: 472.19       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8     6W /  N/A |    134MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by strongoier** [comment]
It seems that you have 4GB CUDA memory in total. What about removing `device_memory_GB=7`?

**Comment by DQSSSSS** [comment]
Sorry I made a stupid mistake, I use the whole GPU memory to calculate instead of the rest memory. Thank you!
