### ISSUE TITLE
Build failed on Macbook Pro with M1X Max CPU

### ISSUE THREAD

**Issue by Zheaoli** [taichi-dev/taichi#3484]
Could not build the taichi code at the master branch. Here's the error message 

```python
/Users/jingcher/Downloads/llvm-10.0.0-m1/bin/llvm-as: runtime_arm64.ll:2540:74: error: expected ')' at end of argument list
define void @Element_get_pcoord(%struct.PhysicalCoordinates* noalias sret(%struct.PhysicalCoordinates) align 4 %0, %struct.Element* %1) #0 {
                                                                         ^
make[2]: *** [CMakeFiles/generate_llvm_runtime_arm64] Error 1
make[1]: *** [CMakeFiles/generate_llvm_runtime_arm64.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/Users/jingcher/taichi/setup.py", line 230, in <module>
    setup(name=project_name,
  File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in setup
    return distutils.core.setup(**attrs)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/homebrew/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/opt/homebrew/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/jingcher/taichi/setup.py", line 163, in run
    subprocess.check_call(cmake_cmd, cwd=self.build_temp)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j10']' returned non-zero exit status 2.
```

The compiler is clang-13 and os version is MacOS 12.0.1

**Comment by ailzhang** [comment]
@Zheaoli we've updated dev install documentation about clang-12 and above not supported yet. clang11 works ;) 
https://docs.taichi.graphics/lang/articles/contribution/dev_install
```
Taichi doesn't support building with clang++-12 and above yet. clang++-10 is highly recommended but if you're on a newer (>=11) macOS, building with clang++-11 also works through brew install llvm@11 and export CXX=/opt/homebrew/opt/llvm@11/bin/clang++.
```

**Comment by frostming** [comment]
I've built successfully on M1 Mac (clang 13)

1. Download prebuilt LLVM
2. brew install `llvm@11` (to `/opt/` prefix for arm build)
3. Set the PATH env var as [this comment](https://github.com/taichi-dev/taichi/issues/3346#issuecomment-964290795)

**Comment by ailzhang** [comment]
Closing via https://github.com/taichi-dev/taichi/issues/3484#issuecomment-967152074
