### ISSUE TITLE
Windows 10: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by weignv** [taichi-dev/taichi#370]
1. OS: Windows 10 Preview Build 
2. Python version: 3.7.6
C:\Python3dot7>python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30)
3. Package install: python -m pip install taichi-nightly
Successfully installed astor-0.8.1 atomicwrites-1.3.0 attrs-19.3.0 colorama-0.4.3 importlib-metadata-1.3.0 more-itertools-8.0.2 numpy-1.18.1 packaging-20.0 pluggy-0.13.1 py-1.8.1 pybind11-2.4.3 pyparsing-2.4.6 pytest-5.3.2 six-1.13.0 taichi-nightly-0.3.20 wcwidth-0.1.8 zipp-0.6.0
4. Repro: Error message when running example:

E:\Experiments\taichi-master\examples>laplace.py
[Release mode]
Traceback (most recent call last):
  File "E:\Experiments\taichi-master\examples\laplace.py", line 1, in <module>
    import taichi as ti
  File "C:\Python3dot7\lib\site-packages\taichi\__init__.py", line 1, in <module>
    from taichi.main import main
  File "C:\Python3dot7\lib\site-packages\taichi\main.py", line 6, in <module>
    from taichi.tools.video import make_video, interpolate_frames, mp4_to_gif, scale_video, crop_video, accelerate_video
  File "C:\Python3dot7\lib\site-packages\taichi\tools\video.py", line 3, in <module>
    import taichi.core as core
  File "C:\Python3dot7\lib\site-packages\taichi\core\__init__.py", line 1, in <module>
    from .util import tc_core, build, format, load_module, start_memory_monitoring, \
  File "C:\Python3dot7\lib\site-packages\taichi\core\util.py", line 158, in <module>
    import_tc_core()
  File "C:\Python3dot7\lib\site-packages\taichi\core\util.py", line 31, in import_tc_core
    import taichi_core as core
ImportError: DLL load failed: The specified module could not be found.

Line 31:

` import taichi_core as core`

**Comment by weignv** [comment]
I had a quick bing search and found that I need to install the VS C++ Redistributable of 2015  [https://www.microsoft.com/en-us/download/details.aspx?id=48145](url) to fix the missing DLLs issue.

**Comment by yuanming-hu** [comment]
Thanks for reporting this. In the latest version, users will be suggested to install VS C++ Redistributable if import fails. Let's see if everybody can resolve this issue on their own from now on.
