### ISSUE TITLE
[GUI] Couldn't use gui.text

### ISSUE THREAD

**Issue by FantasyVR** [taichi-dev/taichi#3769]
**Describe the bug**
When I run the [taichi course code](https://github.com/taichiCourse01/--Deformables/blob/master/fem-explicit.py) using Taichi 0.8.7,  AttributeError occurs. 

**To Reproduce**
Just run the code with: `python fem-explicit.py`.

**Log/Screenshots**
```
[Taichi] version 0.8.8, llvm 10.0.0, commit c7b44724, win, python 3.9.7
[I 12/10/21 06:25:38.209 18328] [shell.py:_shell_pop_print@33] Graphical python shell detected, using wrapped sys.stdout
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\--Deformables\fem-explicit.py", line 285, in <module>
    gui.text(
  File "c:\users\admin\downloads\taichi\python\taichi\ui\gui.py", line 605, in text
    color = ti.core_vec(r, g, b, 1)
  File "c:\users\admin\downloads\taichi\python\taichi\__init__.py", line 36, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'core_vec'
```

**Additional comments**
The source code of `core_vec` is moved to `taichi/python/taichi/tools/util.py`. `gui.py` doesn't import `core_vec` correctly.

**Comment by strongoier** [comment]
Closed by #3770.
