### ISSUE TITLE
 Font file not found:../assets/Go-Regular.ttf

### ISSUE THREAD

**Issue by raymentkong** [taichi-dev/taichi#3867]
**Describe the bug**
[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.7.6
[Taichi] Starting on arch=x64

runing mass_spring_explicit.py(games201,demos of lecture2), report a error.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
# sample code here
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
 File "mass_spring_explicit.py", line 113, in <module>
    gui.text(content=f'C: clear all; Space: pause', pos=(0, 0.95), color=0x0)
  File "E:\miniconda3\lib\site-packages\taichi\ui\gui.py", line 606, in text
    self.canvas.text(content, pos, font_size, color)
RuntimeError: [D:/a/taichi/taichi/taichi/util/image_buffer.cpp:write_text@120] Font file not found: E:\miniconda3\lib\site-packages\taichi\_lib\runtime/../assets/Go-Regular.ttf
...
```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by raymentkong** [comment]
It is a mistake of file path ，need  to redirect file path.
copy Folder contents miniconda3\Lib\site-packages\taichi\assets  to miniconda3\Lib\site-packages\taichi\_lib

**Comment by bjmiao** [comment]
I actually met the same problem. It occurred when I am using a CPU-only laptop to debug some taichi program (so that only ti.cpu backend is possible)

Here is my environment
>[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.9.5
>[Taichi] Starting on arch=x64

And any simple taichi code with `gui.text` can reproduce the problem. Like,

```
import taichi as ti
ti.init(ti.cpu)

gui = ti.GUI("Test", (100, 100))
while gui.running:
    gui.text("Test", pos=(0.5, 0.5))
```

And the error is like
```
[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.9.5
[Taichi] Starting on arch=x64
[E 01/04/22 00:05:35.461 10848] [D:/a/taichi/taichi/taichi/util/image_buffer.cpp:write_text@120] Font file not found: C:\Users\bimia\miniconda3\Lib\site-packages\taichi\_lib\runtime/../assets/Go-Regular.ttf


***********************************
* Taichi Compiler Stack Traceback *
***********************************
0x7ffc11d225a6: Ordinal0 in taichi_core.pyd
0x7ffc11fb7d7e: taichi::print_traceback in taichi_core.pyd
0x7ffc12059716: taichi::print_traceback in taichi_core.pyd
0x7ffc12354673: PyInit_taichi_core in taichi_core.pyd
0x7ffc11ec25a9: taichi::create_instance_raw<taichi::Task> in taichi_core.pyd
0x7ffc6eb0d716: PyArg_CheckPositional in python39.dll
0x7ffc6eb0800d: PyObject_MakeTpCall in python39.dll
0x7ffc6ec3bf0e: PyErr_FormatFromCauseTstate in python39.dll
0x7ffc6eaeb6ff: Py_NewReference in python39.dll
0x7ffc6eb1d8bc: PyEval_EvalFrameDefault in python39.dll
0x7ffc6eaee5c0: PyFunction_Vectorcall in python39.dll
0x7ffc6eae99c4: PyType_GenericAlloc in python39.dll
0x7ffc6eaeb6ff: Py_NewReference in python39.dll
0x7ffc6eb1de49: PyEval_EvalFrameDefault in python39.dll
0x7ffc6eaee5c0: PyFunction_Vectorcall in python39.dll
0x7ffc6eb70a3d: PyEval_EvalCodeWithName in python39.dll
0x7ffc6eb6ecf7: PyEval_EvalCodeEx in python39.dll
0x7ffc6eb6ec55: PyEval_EvalCode in python39.dll
0x7ffc6eb6b542: PyEval_GetBuiltins in python39.dll
0x7ffc6eb6b24e: Py_c_prod in python39.dll
0x7ffc6eb612a3: PyUnicode_CompareWithASCIIString in python39.dll
0x7ffc6eb61804: PyDict_DelItemString in python39.dll
0x7ffc6eb6085b: PyRun_SimpleFileExFlags in python39.dll
0x7ffc6eb60448: PyRun_AnyFileExFlags in python39.dll
0x7ffc6eb5ff5a: PyEval_ReleaseThread in python39.dll
0x7ffc6eb7f7e0: Py_RunMain in python39.dll
0x7ffc6eb7f669: Py_RunMain in python39.dll
0x7ffc6eb7f2a2: Py_Main in python39.dll
0x7ffc6eb7ef39: Py_Main in python39.dll
0x7ff778fe1268: Unknown Function in python.exe
0x7ffcbaa17034: BaseThreadInitThunk in KERNEL32.DLL
0x7ffcbb0e2651: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install
Traceback (most recent call last):
  File "C:\Users\bimia\Documents\codespace\taichi_arcball\test.py", line 6, in <module>
    gui.text("Test", pos=(0.5, 0.5))
  File "C:\Users\bimia\miniconda3\lib\site-packages\taichi\ui\gui.py", line 606, in text
    self.canvas.text(content, pos, font_size, color)
RuntimeError: [D:/a/taichi/taichi/taichi/util/image_buffer.cpp:write_text@120] Font file not found: C:\Users\bimia\miniconda3\Lib\site-packages\taichi\_lib\runtime/../assets/Go-Regular.ttf
```

Like @raymentkong has mentioned, the file path of this font should be `taichi\assets\Go-Regular.ttf` rather than `_lib\runtime/../assets/Go-Regular.ttf`.

The location of the codes related to this issue should be here at [https://github.com/taichi-dev/taichi/blob/fcdcaf9ea940445706e510bf87a1d40e1ac22825/taichi/gui/gui.h#L417](https://github.com/taichi-dev/taichi/blob/fcdcaf9ea940445706e510bf87a1d40e1ac22825/taichi/gui/gui.h#L417), where it uses `{lang::runtime_lib_dir()}/../assets` as the folder of the font. I would make a guess that the path here needs some kind of adaption to Windows platform when using a CPU backend.

**Comment by strongoier** [comment]
Taichi v0.8.9 has just been released. Would you try it out and see if the problem is solved? Thanks!

**Comment by bjmiao** [comment]
Yes, v0.8.9 fixed that problem.
