### ISSUE TITLE
Building from source failed

### ISSUE THREAD

**Issue by DDDOH** [taichi-dev/taichi#3872]
I failed to build taichi and here's the output from the console. My machine is Macbook Pro with Apple M1 Pro, and I use a ubuntu virtual machine with Ubuntu 20.04.2 LTS. I'd like to provide more detailed runtime environment information if needed.

```
/Ubuntu Shared Folders/taichi$ python3 setup.py develop --user
[]
['taichi', 'taichi.ui', 'taichi.tools', 'taichi.types', 'taichi.linalg', 'taichi.snode', 'taichi._lib', 'taichi.lang', 'taichi.profiler', 'taichi.aot', 'taichi._lib.core', 'taichi.lang.ast']
running develop
running egg_info
writing python/taichi.egg-info/PKG-INFO
writing dependency_links to python/taichi.egg-info/dependency_links.txt
writing entry points to python/taichi.egg-info/entry_points.txt
writing requirements to python/taichi.egg-info/requires.txt
writing top-level names to python/taichi.egg-info/top_level.txt
reading manifest file 'python/taichi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python/taichi/*.md'
warning: no files found matching 'python/taichi/_lib/core/*.so'
warning: no files found matching 'python/taichi/_lib/core/*.pyd'
warning: no files found matching 'python/taichi/_lib/runtime/*.bc'
warning: no files found matching 'python/taichi/_lib/runtime/*.dylib'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching 'ffmpeg' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'python/taichi.egg-info/SOURCES.txt'
running build_ext
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
---------- Running CMake prepare ----------------------------------------
Taichi Version 0.8.9
       Commit 65060be5a7a55e274df05ddd8a14fa00b240703c
Using /home/parallels/anaconda3/envs/taichi/bin/python3 as python executable.
Python 3.9.7
    version: 3.9
    include: /home/parallels/anaconda3/envs/taichi/include/python3.9
    library: /home/parallels/anaconda3/envs/taichi/lib/libpython3.9.so
    numpy include: /home/parallels/anaconda3/envs/taichi/lib/python3.9/site-packages/numpy/core/include
    pybind11 include: /home/parallels/.local/lib/python3.9/site-packages/pybind11/include;/home/parallels/.local/lib/python3.9/site-packages/pybind11/include
Using C++ compiler: /usr/bin/c++
GNU compiler detected. Using std=c++17.
CMake Warning at cmake/TaichiCXXFlags.cmake:42 (message):
  It is detected that you are using gcc as the compiler.  This is an
  experimental feature.  Consider adding -DCMAKE_CXX_COMPILER=clang argument
  to CMake to switch to clang (or MSVC on Windows).
Call Stack (most recent call first):
  CMakeLists.txt:63 (include)


Building for processor aarch64
Using float32 (single) precision as real
Building with GLFW
-- Including X11 support
-- Found LLVM 10.0.0
-- Using LLVMConfig.cmake in: /home/parallels/Desktop/taichi-llvm-10.0.0-linux/lib/cmake/llvm
LLVM include dirs /home/parallels/Desktop/taichi-llvm-10.0.0-linux/include
LLVM library dirs /home/parallels/Desktop/taichi-llvm-10.0.0-linux/lib
-- TI_WITH_CUDA_TOOLKIT = OFF
-- SPIRV-Cross: Finding Git version for SPIRV-Cross.
-- SPIRV-Cross: Git hash: 97a438d2
-- Found PythonInterp: /home/parallels/anaconda3/envs/taichi/bin/python3 (found version "3.9.7") 
SPIRV-Cross:  Testing will be disabled for SPIRV-Cross. Could not find glslang or SPIRV-Tools build under external/. To enable testing, run ./checkout_glslang_spirv_tools.sh and ./build_glslang_spirv_tools.sh first.
-- Found PythonInterp: /home/parallels/anaconda3/envs/taichi/bin/python3 (found suitable version "3.9.7", minimum required is "3") 
PYTHON_LIBRARIES: /home/parallels/anaconda3/envs/taichi/lib/libpython3.9.so
C++ Flags:  -DTI_ISE_NONE -std=c++17 -fsized-deallocation -Wno-class-memaccess -Wno-comment -Wno-sign-compare -Wall  -DTI_ARCH_ARM -DTI_PASS_EXCEPTION_TO_PYTHON -DTI_INCLUDED -DTI_WITH_LLVM -DTI_WITH_CUDA -DTI_WITH_METAL -DTI_WITH_OPENGL -DTI_WITH_CC
Build type: Release
Clang executable /usr/bin/clang-10
clang --version: 10.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /media/psf/Ubuntu Shared Folders/taichi/build
---------- Building extensions ----------------------------------------
[  0%] Built target spirv-tools-build-version
[  0%] Built target core_tables
[  1%] Built target enum_string_mapping
[  1%] Built target spirv-tools-header-NonSemanticShaderDebugInfo100
[  1%] Built target spv-tools-spv-amd-sevp
[  1%] Built target spv-tools-spv-amd-stm
[  1%] Built target spv-tools-spv-amd-gs
[  2%] Built target spv-tools-spv-amd-sb
[  2%] Built target spv-tools-debuginfo
[  2%] Built target spv-tools-cldi100
[  2%] Built target spv-tools-shdi100
[  2%] Built target spv-tools-clspvreflection
[  2%] Built target spirv-tools-header-DebugInfo
[  2%] Built target spirv-tools-header-OpenCLDebugInfo100
runtime.cpp:1043:18: error: invalid input constraint 'l' in asm
               : "l"(value), "r"(mask));
                 ^
runtime.cpp:1053:44: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
  asm volatile("activemask.b32 %0;" : "=r"(mask));
                                           ^
runtime.cpp:1053:32: note: use constraint modifier "w"
  asm volatile("activemask.b32 %0;" : "=r"(mask));
                               ^~
                               %w0
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/generate_llvm_runtime_cuda.dir/build.make:70: CMakeFiles/generate_llvm_runtime_cuda] Error 1
make[1]: *** [CMakeFiles/Makefile2:757: CMakeFiles/generate_llvm_runtime_cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Built target generate_llvm_runtime_arm64
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/media/psf/Ubuntu Shared Folders/taichi/setup.py", line 245, in <module>
    setup(name=project_name,
  File "/home/parallels/anaconda3/envs/taichi/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/parallels/anaconda3/envs/taichi/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/parallels/anaconda3/envs/taichi/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/parallels/anaconda3/envs/taichi/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/parallels/anaconda3/envs/taichi/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/parallels/anaconda3/envs/taichi/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/parallels/anaconda3/envs/taichi/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/parallels/anaconda3/envs/taichi/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/psf/Ubuntu Shared Folders/taichi/setup.py", line 166, in run
    subprocess.check_call(cmake_cmd, cwd=self.build_temp)
  File "/home/parallels/anaconda3/envs/taichi/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
```

**Comment by AmesingFlank** [comment]
This looks like the clang version is to high. Perhaps try using clang <= 12 (which comes with xcode 12.x)
