### ISSUE TITLE
Coundn't find Go-Regular.ttf when using gui.text

### ISSUE THREAD

**Issue by FantasyVR** [taichi-dev/taichi#3933]
**Describe the bug**
Related forum topic: https://forum.taichi.graphics/t/fem/2215

**To Reproduce**
Run https://github.com/taichiCourse01/--Deformables/blob/master/fem-explicit.py

**Log/Screenshots**

```
[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.8.10

D:\chengxu\python\python.exe: can't open file 'fem-explicit.py': [Errno 2] No such file or directory
Running time: 0.04s
PS F:\project\taichi> python -m taichi F:\project\taichi\--Deformables-master\fem-explicit.py
[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.8.10

*******************************************
**      Taichi Programming Language      **
*******************************************

[Taichi] version 0.8.8, llvm 10.0.0, commit 7bae9c77, win, python 3.8.10
[Taichi] Starting on arch=x64
[E 12/24/21 20:37:53.025 8708] [D:/a/taichi/taichi/taichi/util/image_buffer.cpp:write_text@120] Font file not found: D:\chengxu\python\Lib\site-packages\taichi\_lib\runtime/../assets/Go-Regular.ttf

Traceback (most recent call last):
  File "F:\project\taichi\--Deformables-master\fem-explicit.py", line 285, in <module>
    gui.text(
  File "D:\chengxu\python\lib\site-packages\taichi\ui\gui.py", line 606, in text
    self.canvas.text(content, pos, font_size, color)
RuntimeError: [D:/a/taichi/taichi/taichi/util/image_buffer.cpp:write_text@120] Font file not found: D:\chengxu\python\Lib\site-packages\taichi\_lib\runtime/../assets/Go-Regular.ttf
```

**Comment by k-ye** [comment]
[Dup](https://github.com/taichi-dev/taichi/issues/3867)
