### ISSUE TITLE
I don't know what's wrong

### ISSUE THREAD

**Issue by chuiliuyiyi** [taichi-dev/taichi#3969]
import taichi as ti
import numpy as np

ti.init(arch=ti.cpu)

@ti.kernel
def rotate(r0: ti.i32 , r1: ti.i32 , r2: ti.i32):
	a = -5
	b = 5
	for aa0 in range(1,2):
		for aa1 in range(1,2):
			for aa2 in range(1,2):
				for t in range(0,32*2):
					t = t/10
					print(t)

rotate(1,4,5)

运行:D:\Program Files\python3.9.5\python3.9.5.exe 新建文本文档.py
[E 01/07/22 15:58:05.368 7924] [taichi/ir/statements.h:taichi::lang::LocalStoreStmt::LocalStoreStmt@588] Assertion failure: dest->is<AllocaStmt>() || (dest->is<PtrOffsetStmt>() && dest->cast<PtrOffsetStmt>()->is_local_ptr())

[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m* Taichi Compiler Stack Traceback *
[0m[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m0x7ff8671e79fa: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff8670ad529: [0m[38;2;255;000;000mPyInit_taichi_core[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff8671ee041: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722a30a: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722c5dc: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722bffb: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722e6c4: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722bffb: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722e6c4: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722bffb: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722e6c4: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722bffb: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722e6c4: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722bffb: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722be4d: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86722bc57: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff8671fcd6f: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff8671fca17: [0m[38;2;255;000;000mtaichi::print_traceback[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86716dd92: [0m[38;2;255;000;000mPyInit_taichi_core[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86714c891: [0m[38;2;255;000;000mPyInit_taichi_core[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff867182078: [0m[38;2;255;000;000mPyInit_taichi_core[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86716d205: [0m[38;2;255;000;000mPyInit_taichi_core[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86716cbb8: [0m[38;2;255;000;000mPyInit_taichi_core[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff866fc37ce: [0m[38;2;255;000;000mPyInit_taichi_core[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff866f47d66: [0m[38;2;255;000;000mPyInit_taichi_core[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff866f1712b: [0m[38;2;255;000;000mpybind11::error_already_set::discard_as_unraisable[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ff86dc98562: [0m[38;2;255;000;000mPyArg_ParseTuple_SizeT[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc806dc: [0m[38;2;255;000;000mPyObject_MakeTpCall[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86ddcdace: [0m[38;2;255;000;000mPy_gitversion[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca2f5c: [0m[38;2;255;000;000mPyVectorcall_Call[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca2d4b: [0m[38;2;255;000;000mPyObject_Call[0m[38;2;255;000;255m in python39.dll
[0m[38;2;2[Taichi] version 0.8.7, llvm 10.0.0, commit 88d81df6, win, python 3.9.5
[Taichi] Starting on arch=x64
55;000;255m0x7ff86ddcf86b: [0m[38;2;255;000;000mPy_gitversion[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc6d5ac: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc65833: [0m[38;2;255;000;000mPyObject_GC_Del[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc67137: [0m[38;2;255;000;000mPyFunction_Vectorcall[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca2f5c: [0m[38;2;255;000;000mPyVectorcall_Call[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca2e3e: [0m[38;2;255;000;000mPyObject_Call[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc6e403: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc65833: [0m[38;2;255;000;000mPyObject_GC_Del[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc67137: [0m[38;2;255;000;000mPyFunction_Vectorcall[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca6873: [0m[38;2;255;000;000mPyObject_FastCallDictTstate[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca62b0: [0m[38;2;255;000;000mPyObject_Call_Prepend[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca620c: [0m[38;2;255;000;000mPyEval_EvalCodeEx[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca2ea7: [0m[38;2;255;000;000mPyObject_Call[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc6e403: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc65833: [0m[38;2;255;000;000mPyObject_GC_Del[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc6c010: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc65833: [0m[38;2;255;000;000mPyObject_GC_Del[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca69e9: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca619b: [0m[38;2;255;000;000mPyEval_EvalCodeEx[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca60f9: [0m[38;2;255;000;000mPyEval_EvalCode[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca5c8e: [0m[38;2;255;000;000mPyDict_GetItemString[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dca5876: [0m[38;2;255;000;000mPyArena_New[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc768db: [0m[38;2;255;000;000mPy_wfopen[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc74d48: [0m[38;2;255;000;000mPy_stat[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc74957: [0m[38;2;255;000;000mPyRun_SimpleFileExFlags[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc742a4: [0m[38;2;255;000;000mPyRun_AnyFileExFlags[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc777ba: [0m[38;2;255;000;000mPyThread_tss_create[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc78eb8: [0m[38;2;255;000;000mPy_RunMain[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc78d41: [0m[38;2;255;000;000mPy_RunMain[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff86dc78a11: [0m[38;2;255;000;000mPy_Main[0m[38;2;255;000;255m in python39.dll
[0m[38;2;255;000;255m0x7ff6da7b1258: [0m[38;2;255;000;000mUnknown Function[0m[38;2;255;000;255m in python3.9.5.exe
[0m[38;2;255;000;255m0x7ff88cb21fe4: [0m[38;2;255;000;000mBaseThreadInitThunk[0m[38;2;255;000;255m in KERNEL32.DLL
[0m[38;2;255;000;255m0x7ff88d36ef91: [0m[38;2;255;000;000mRtlUserThreadStart[0m[38;2;255;000;255m in ntdll.dll
[0m[38;2;255;165;000m
Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install
[0mTraceback (most recent call last):
  File  , line 20, in <module>
    rotate(1,4,5)
  File "D:\Program Files\python3.9.5\lib\site-packages\taichi\lang\kernel_impl.py", line 703, in wrapped
    return primal(*args, **kwargs)
  File "D:\Program Files\python3.9.5\lib\site-packages\taichi\lang\kernel_impl.py", line 632, in __call__
    return self.compiled_functions[key](*args)
  File "D:\Program Files\python3.9.5\lib\site-packages\taichi\lang\kernel_impl.py", line 583, in func__
    t_kernel(launch_ctx)
RuntimeError: [taichi/ir/statements.h:taichi::lang::LocalStoreStmt::LocalStoreStmt@588] Assertion failure: dest->is<AllocaStmt>() || (dest->is<PtrOffsetStmt>() && dest->cast<PtrOffsetStmt>()->is_local_ptr())
输出结束,返回值是[1].

**Comment by FantasyVR** [comment]
There is a simpler code snippet. 
```python
import taichi as ti
ti.init(arch=ti.cpu)

@ti.kernel
def rotate():
    for i in range(10):
        i = i/10 # bug occurs here
        print(i)

rotate()
```

**Comment by turbo0628** [comment]
The value is assigned back to the iterator var. 

You can try to use another local variable instead.

**Comment by chuiliuyiyi** [comment]
Thanks for solving it,
import taichi as ti
ti.init(arch=ti.cpu)

@ti.kernel
def rotate():
    for i0 in range(10):
        i = i0/10 # bug occurs here
        print(i)

rotate()
