### ISSUE TITLE
Call python function in taichi scope raise TypeError: float() argument must be a string or a number, not 'Expr'

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#4001]
```python
import taichi as ti
ti.init(print_ir=True)

def vec3(*args):
    assert len(args) == 1 or len(args) == 3
    if len(args) == 1:
        x = float(args[0])
        result = ti.Vector([x, x, x])
    else:
        x, y, z = args
        result = ti.Vector([float(x), float(y), float(z)])

    return result


@ti.func
def process(a):
    x, y, z = a
    return vec3(x + 1, y + 1, z + 1)

@ti.kernel
def func():
    a = vec3(1, 2, 3)
    a = process(a)

func()
```

The above code raises Error

```
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    func()
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 715, in wrapped
    return primal(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 643, in __call__
    key = self.ensure_compiled(*args)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 629, in ensure_compiled
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 475, in materialize
    taichi_kernel = _ti_core.create_kernel(taichi_ast_generator,
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 465, in taichi_ast_generator
    transform_tree(tree, ctx)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/transform.py", line 8, in transform_tree
    ASTTransformer()(ctx, tree)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 26, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 23, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 484, in build_Module
    build_stmt(ctx, stmt)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 26, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 23, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 448, in build_FunctionDef
    build_stmts(ctx, node.body)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 1083, in build_stmts
    build_stmt(ctx, stmt)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 26, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 23, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 69, in build_Assign
    build_stmt(ctx, node.value)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 32, in __call__
    raise TaichiCompilationError(msg)
taichi.lang.exception.TaichiCompilationError: On line 24 of file "test.py":
    a = process(a)
        ^^^^^^^^^^
On line 19 of file "test.py":
    return vec3(x + 1, y + 1, z + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a number, not 'Expr'
```

**Comment by lin-hitonami** [comment]
Thanks for reporting! Python functions called within taichi scope may not work as expected because the compiler performs some transformations to taichi kernels and functions. We do not recommend calling python functions in taichi scope. We will add a warning soon to warn users about this.
