### ISSUE TITLE
Misleading Error Message

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#4003]
```python
import taichi as ti
ti.init(arch=ti.gpu)

import numpy as np

# define 10 points as vertices
points = ti.Vector.field(3, ti.f32, shape=(10, 1))
points.from_numpy(np.random.random((10, 1, 3)))

@ti.func
def get_polygon(polygon_indices: ti.template()):
    coords = []
    for ind in ti.static(range(len(polygon_indices))):
        coords.append(points[polygon_indices[ind], 0])

    return coords


@ti.kernel
def main():
    arr = np.array([1, 2, 3, 4], dtype=int)
    get_polygon(arr)


main()
```
The above code reports error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 23, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 80, in build_Assign
    ASTTransformer.build_assign_unpack(ctx, node_target,
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 98, in build_assign_unpack
    return ASTTransformer.build_assign_basic(ctx, node_target, values,
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 129, in build_assign_basic
    var = ti.expr_init(value)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/util.py", line 216, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/impl.py", line 61, in expr_init
    return Expr(_ti_core.expr_var(Expr(rhs).ptr))
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/expr.py", line 33, in __init__
    self.ptr = impl.make_constant_expr(arg).ptr
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/util.py", line 216, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/impl.py", line 444, in make_constant_expr
    return Expr(_ti_core.make_const_expr_f32(val))
TypeError: make_const_expr_f32(): incompatible function arguments. The following argument types are supported:
    1. (arg0: float) -> taichi._lib.core.taichi_core.Expr

Invoked with: array([1, 2, 3, 4])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 30, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 715, in wrapped
    return primal(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 643, in __call__
    key = self.ensure_compiled(*args)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 629, in ensure_compiled
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 475, in materialize
    taichi_kernel = _ti_core.create_kernel(taichi_ast_generator,
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/kernel_impl.py", line 465, in taichi_ast_generator
    transform_tree(tree, ctx)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/transform.py", line 8, in transform_tree
    ASTTransformer()(ctx, tree)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 26, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 23, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 484, in build_Module
    build_stmt(ctx, stmt)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 26, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 23, in __call__
    return method(ctx, node)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 448, in build_FunctionDef
    build_stmts(ctx, node.body)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer.py", line 1083, in build_stmts
    build_stmt(ctx, stmt)
  File "/usr/local/lib/python3.8/dist-packages/taichi/lang/ast/ast_transformer_utils.py", line 32, in __call__
    raise TaichiCompilationError(msg)
taichi.lang.exception.TaichiCompilationError: On line 26 of file "test.py":
    arr = np.array([1, 2, 3, 4], dtype=int)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: make_const_expr_f32(): incompatible function arguments. The following argument types are supported:
    1. (arg0: float) -> taichi._lib.core.taichi_core.Expr

Invoked with: array([1, 2, 3, 4])

```

The error is because  we are creating a numpy array in ti.kernel, should this error message be more clear here?

**Comment by lin-hitonami** [comment]
If I remember correctly, we do not support creating a variable with np.array either right now, but this error message is indeed confusing. I'll fix it soon.
