### ISSUE TITLE
__ZN4llvm10CallbackVH6anchorEv

### ISSUE THREAD

**Issue by g0402559** [taichi-dev/taichi#4213]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
# sample code here
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python my_sample_code.py
[Taichi] mode=release
[Taichi] version 0.6.29, llvm 10.0.0, commit b63f6663, linux, python 3.8.3
...
```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by bobcao3** [comment]
Hello! Can you post the CMakeCache.txt from the build folder? Also please remove the sensitive path or information in that file before you post it.

**Comment by g0402559** [comment]
[CMakeCache.txt](https://github.com/taichi-dev/taichi/files/8011757/CMakeCache.txt)

**Comment by Peterritche** [comment]
Hi all, 
build  taichi code successfully on ubuntu21.10 , but import taichi will show below error. 
import taichi
Share object taichi_core import failed, check this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linaro/ssd/git/taichi/python/taichi/__init__.py", line 3, in <module>
    from taichi._funcs import *
  File "/home/linaro/ssd/git/taichi/python/taichi/_funcs.py", line 3, in <module>
    from taichi.lang import impl, matrix, ops
  File "/home/linaro/ssd/git/taichi/python/taichi/lang/__init__.py", line 3, in <module>
    from taichi._lib import core as _ti_core
  File "/home/linaro/ssd/git/taichi/python/taichi/_lib/__init__.py", line 1, in <module>
    from taichi._lib.utils import ti_core as core
  File "/home/linaro/ssd/git/taichi/python/taichi/_lib/utils.py", line 103, in <module>
    ti_core = import_ti_core()
  File "/home/linaro/ssd/git/taichi/python/taichi/_lib/utils.py", line 54, in import_ti_core
    raise e from None
  File "/home/linaro/ssd/git/taichi/python/taichi/_lib/utils.py", line 43, in import_ti_core
    from taichi._lib.core import \
ImportError: cannot import name 'taichi_core' from 'taichi._lib.core' (/home/linaro/ssd/git/taichi/python/taichi/_lib/core/__init__.py)
>>>

**Comment by bobcao3** [comment]
> Hi all, build taichi code successfully on ubuntu21.10 , but import taichi will show below error. import taichi Share object taichi_core import failed, check this page for possible solutions: https://docs.taichi.graphics/lang/articles/misc/install Traceback (most recent call last): File "", line 1, in File "/home/linaro/ssd/git/taichi/python/taichi/**init**.py", line 3, in from taichi._funcs import * File "/home/linaro/ssd/git/taichi/python/taichi/_funcs.py", line 3, in from taichi.lang import impl, matrix, ops File "/home/linaro/ssd/git/taichi/python/taichi/lang/**init**.py", line 3, in from taichi._lib import core as _ti_core File "/home/linaro/ssd/git/taichi/python/taichi/_lib/**init**.py", line 1, in from taichi._lib.utils import ti_core as core File "/home/linaro/ssd/git/taichi/python/taichi/_lib/utils.py", line 103, in ti_core = import_ti_core() File "/home/linaro/ssd/git/taichi/python/taichi/_lib/utils.py", line 54, in import_ti_core raise e from None File "/home/linaro/ssd/git/taichi/python/taichi/_lib/utils.py", line 43, in import_ti_core from taichi._lib.core import ImportError: cannot import name 'taichi_core' from 'taichi._lib.core' (/home/linaro/ssd/git/taichi/python/taichi/_lib/core/**init**.py)
> 
> > > >

Hello! Does using the taichi from pip work? (Does it only happen when you build it from source?)

**Comment by weiyunfei** [comment]
Hi,
I encountered the same error when run `import taichi` after building taichi from source just now. 

I followed the Developer Installation document during building.

My CmakeCache.txt is [CMakeCache.txt](https://github.com/taichi-dev/taichi/files/8357879/CMakeCache.txt). 

And I find the following outputs when building `taichi.core`.

I'm not sure whether these ignoring files led to an incompleted `taichi.core` module.

```
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMOrcJIT.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMExecutionEngine.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMJITLink.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMOrcError.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMRuntimeDyld.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMPasses.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMCodeGen.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMipo.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMBitWriter.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMTarget.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMScalarOpts.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMInstCombine.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMLinker.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMAggressiveInstCombine.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ld: warning: ld: warning: ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMIRReader.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMInstrumentation.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMVectorize.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMTransformUtils.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMAsmParser.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMObject.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMAnalysis.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMBitReader.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMMCParser.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMMC.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMDebugInfoCodeView.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMDebugInfoMSF.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMTextAPI.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMProfileData.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMBinaryFormat.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMCore.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMRemarks.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMBitstreamReader.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64

ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMSupport.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/weiyunfei/.local/bin/llvm-10.0.0-m1/lib/libLLVMDemangle.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
[100%] Built target taichi_core
```

**Comment by bobcao3** [comment]
@weiyunfei Hello, are you using a M1 mac? If so, please check whether you are using the M1 native console?

**Comment by weiyunfei** [comment]
> @weiyunfei Hello, are you using a M1 mac? If so, please check whether you are using the M1 native console?

If the the M1 native console means the builtin Terminal of M1 mac, I have both tried the M1 native console and ITERM2. And I got the same results. This is my building log with `python3 setup.py develop --user`. 
[build.log](https://github.com/taichi-dev/taichi/files/8359305/build.log)

**Comment by Peterritche** [comment]
ALL：
源码编译taichi执行example出现如下的错误，有啥可能？



./taichi_cpp_examples

[E 07/05/22 11:14:31.972 5980] ***@***.*** A bit-vectorized struct-for must loop over a bit array with a dense parent

**Comment by strongoier** [comment]
@Peterritche See https://github.com/taichi-dev/taichi/issues/4376#issuecomment-1178566400.
