### ISSUE TITLE
Confusing error message when having break in the outermost loop

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#4223]
**Describe the bug**
For this program,
```python
import taichi as ti
ti.init()

@ti.kernel
def foo():
    for j in range(100):
        break

foo()
```
The error message is like
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    foo()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test38/lib/python3.8/site-packages/taichi-0.8.12-py3.8-macosx-11.0-arm64.egg/taichi/lang/kernel_impl.py", line 736, in wrapped
    return primal(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test38/lib/python3.8/site-packages/taichi-0.8.12-py3.8-macosx-11.0-arm64.egg/taichi/lang/kernel_impl.py", line 667, in __call__
    return self.compiled_functions[key](*args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test38/lib/python3.8/site-packages/taichi-0.8.12-py3.8-macosx-11.0-arm64.egg/taichi/lang/kernel_impl.py", line 619, in func__
    t_kernel(launch_ctx)
RuntimeError: [ir.h:as@225] Assertion failure: is<T>()
```

**Comment by erizmr** [comment]
It looks like we only support break in `while` loop according to line 137 in `lower_ast.cpp`.

**Comment by lin-hitonami** [comment]
> It looks like we only support break in `while` loop according to line 137 in `lower_ast.cpp`.

Inner `for` loops with `break` are converted into `while` statements according to line 232 in `lower_ast.cpp`.
