### ISSUE TITLE
Function with ext_arr as arguements

### ISSUE THREAD

**Issue by xuhao1** [taichi-dev/taichi#4256]
**Describe the bug**

Currently, ti.func use ext_arr as arguments will raise an error.

**To Reproduce**

```python
 @ti.func
    def create_triangles(self, tsdf, i, j, k, step, isolevel, triangle_idx, edgeTable, triTable):
        #Marching...
        cubeindex = int(0)
        c = 0
  @ti.kernel
    def generate_mesh_kernel(self, occupy: ti.template(), tsdf: ti.template(), step:ti.i32, edgeTable: ti.ext_arr(), triTable: ti.ext_arr()):
        isolevel = 0
        triangle_idx = 0
        for i, j, k in tsdf:
            if occupy[i, j, k] and occupy[i + step, j + step, k + step]:
                self.create_triangles(tsdf, i, j, k, step, isolevel, triangle_idx, edgeTable, triTable)
        self.num_triangles[None] = triangle_idx

...
```
I set edgeTable and triTable as ext_arr(), and the raise
```
taichi.lang.exception.TaichiTypeError: On line 98 of file "/home/xuhao/Develop/TaichiSLAM/taichi_slam/mapping/marching_cube_mesher.py":
                self.create_triangles(tsdf, i, j, k, step, isolevel,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
triangle_idx, edgeTable, triTable)
^^^^^^^^^^^^^^^^^^^^^^^
On line 54 of file "/home/xuhao/Develop/TaichiSLAM/taichi_slam/mapping/marching_cube_mesher.py":
    def create_triangles(self, tsdf, i, j, k, step, isolevel, triangle_idx,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
edgeTable, triTable):
^^^^^^^^^^^^^^^^^
        #Marching...
        ^^^^^^^^^^^^
Invalid constant scalar data type: <class 'taichi.lang.any_array.AnyArray'>

```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
(base) ➜  TaichiSLAM git:(main) ✗ python taichislam_node.py
[Taichi] version 0.8.11, llvm 10.0.0, commit 9d0973e5, linux, python 3.8.5
[Taichi] Starting on arch=x64
 ...
Traceback (most recent call last):
  File "taichislam_node.py", line 337, in <module>
    taichislamnode.update()
  File "taichislam_node.py", line 224, in update
    self.taichimapping_depth_callback(self.cur_pose, self.depth_msg, self.rgb_array)
  File "taichislam_node.py", line 259, in taichimapping_depth_callback
    self.mesher.generate_mesh(mapping.occupy, mapping.TSDF, 1)
  File "/home/xuhao/Develop/TaichiSLAM/taichi_slam/mapping/marching_cube_mesher.py", line 102, in generate_mesh
    self.generate_mesh_kernel(occupy, tsdf, step, edgeTable, triTable)
  File "/home/xuhao/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 798, in __call__
    return self._primal(self._kernel_owner, *args, **kwargs)
  File "/home/xuhao/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 664, in __call__
    key = self.ensure_compiled(*args)
  File "/home/xuhao/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 651, in ensure_compiled
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/home/xuhao/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 471, in materialize
    taichi_kernel = _ti_core.create_kernel(taichi_ast_generator,
  File "/home/xuhao/anaconda3/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 461, in taichi_ast_generator
    transform_tree(tree, ctx)
  File "/home/xuhao/anaconda3/lib/python3.8/site-packages/taichi/lang/ast/transform.py", line 6, in transform_tree
    ASTTransformer()(ctx, tree)
  File "/home/xuhao/anaconda3/lib/python3.8/site-packages/taichi/lang/ast/ast_transformer_utils.py", line 27, in __call__
    raise e.with_traceback(None)
taichi.lang.exception.TaichiTypeError: On line 98 of file "/home/xuhao/Develop/TaichiSLAM/taichi_slam/mapping/marching_cube_mesher.py":
                self.create_triangles(tsdf, i, j, k, step, isolevel,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
triangle_idx, edgeTable, triTable)
^^^^^^^^^^^^^^^^^^^^^^^
On line 54 of file "/home/xuhao/Develop/TaichiSLAM/taichi_slam/mapping/marching_cube_mesher.py":
    def create_triangles(self, tsdf, i, j, k, step, isolevel, triangle_idx,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
edgeTable, triTable):
^^^^^^^^^^^^^^^^^
        #Marching...
        ^^^^^^^^^^^^
Invalid constant scalar data type: <class 'taichi.lang.any_array.AnyArray'>

```

**Additional comments**

**Comment by strongoier** [comment]
Could you try
```python
@ti.func
def create_triangles(self, tsdf, i, j, k, step, isolevel, triangle_idx, edgeTable: ti.template(), triTable: ti.template()):
```
According to https://docs.taichi.graphics/lang/articles/basic/syntax#advanced-arguments-1, we can use `ti.template()` in `@ti.func` parameter annotations to pass arguments by reference. And for now `ext_arr` can only be passed by reference.
