### ISSUE TITLE
Better compilation error information for invalid snode size

### ISSUE THREAD

**Issue by BillXu2000** [taichi-dev/taichi#4350]
**Concisely describe the proposed feature**
Invalid snode size will cause an assertion failure in snode.cpp now.
```
RuntimeError: [snode.cpp:create_node@53] Assertion failure: sizes[i] > 0
```
Error with exact line number in python code might be more informative for users.

**Describe the solution you'd like (if any)**
Add snode size error detection and error information in python code.

**Additional comments**
example code:
```python
import taichi as ti
ti.init()
a = ti.field(dtype=int, shape=0)

@ti.kernel
def fun():
    print(a[0])
fun(0)
```

error log:
```
[Taichi] version 0.9.0, llvm 10.0.0, commit d6943eb0, linux, python 3.8.5
[Taichi] Starting on arch=x64
[E 02/21/22 14:05:10.904 404408] [snode.cpp:create_node@53] Assertion failure: sizes[i] > 0


***********************************
* Taichi Compiler Stack Traceback *
***********************************
/home/bx2k/git/taichi/python/taichi/_lib/core/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
/home/bx2k/git/taichi/python/taichi/_lib/core/taichi_core.so: taichi::lang::SNode::create_node(std::vector<taichi::lang::Axis, std::allocator<taichi::lang::Axis> >, std::vector<int, std::allocator<int> >, taichi::lang::SNodeType, bool)
/home/bx2k/git/taichi/python/taichi/_lib/core/taichi_core.so: taichi::lang::SNode::dense(std::vector<taichi::lang::Axis, std::allocator<taichi::lang::Axis> > const&, std::vector<int, std::allocator<int> > const&, bool)
/home/bx2k/git/taichi/python/taichi/_lib/core/taichi_core.so(+0xa3c1ef) [0x7f47f79ca1ef]
/home/bx2k/git/taichi/python/taichi/_lib/core/taichi_core.so(+0x96899e) [0x7f47f78f699e]
python3(PyCFunction_Call+0x59) [0x5f2fb9]
python3(_PyObject_MakeTpCall+0x296) [0x5f3446]
python3() [0x50aa8b]
python3(_PyEval_EvalFrameDefault+0x5757) [0x56ef97]
python3(_PyFunction_Vectorcall+0x1b6) [0x5f5e56]
python3(_PyEval_EvalFrameDefault+0x8f6) [0x56a136]
python3() [0x50a23e]
python3(_PyEval_EvalFrameDefault+0x5757) [0x56ef97]
python3(_PyEval_EvalCodeWithName+0x26a) [0x56822a]
python3(_PyFunction_Vectorcall+0x393) [0x5f6033]
python3(PyObject_Call+0x1f7) [0x5f2b87]
python3(_PyEval_EvalFrameDefault+0x1f70) [0x56b7b0]
python3(_PyEval_EvalCodeWithName+0x26a) [0x56822a]
python3(_PyFunction_Vectorcall+0x393) [0x5f6033]
python3(_PyEval_EvalFrameDefault+0x18d5) [0x56b115]
python3(_PyEval_EvalCodeWithName+0x26a) [0x56822a]
python3(PyEval_EvalCode+0x27) [0x68c1e7]
python3() [0x67d5a1]
python3() [0x67d61f]
python3(PyRun_FileExFlags+0x9b) [0x67d6db]
python3(PyRun_SimpleFileExFlags+0x17e) [0x67da6e]
python3(Py_RunMain+0x212) [0x6b6132]
python3(Py_BytesMain+0x2d) [0x6b64bd]
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
python3(_start+0x2e) [0x5f927e]

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    a = ti.field(dtype=int, shape=0)
  File "/home/bx2k/git/taichi/python/taichi/lang/util.py", line 226, in wrapped
    return func(*args, **kwargs)
  File "/home/bx2k/git/taichi/python/taichi/lang/impl.py", line 612, in field
    root.dense(index_nd(dim), shape).place(x, offset=offset)
  File "/home/bx2k/git/taichi/python/taichi/_snode/fields_builder.py", line 72, in dense
    return self.root.dense(indices, dimensions)
  File "/home/bx2k/git/taichi/python/taichi/lang/snode.py", line 36, in dense
    self.ptr.dense(axes, dimensions,
RuntimeError: [snode.cpp:create_node@53] Assertion failure: sizes[i] > 0
```

**Comment by qiao-bo** [comment]
@lin-hitonami, did we fix this already?

**Comment by lin-hitonami** [comment]
> @lin-hitonami, did we fix this already?

Not yet.
