### ISSUE TITLE
0.9.0 broke @ti.pyfunc

### ISSUE THREAD

**Issue by whorfin** [taichi-dev/taichi#4414]
**Describe the bug**
@ti.pyfunc no longer exists, but taichi still refers to it and seems to need it

**To Reproduce**
```py
import math
import taichi as ti

ti.init()

@ti.pyfunc
def fmod(a, b):
    return a-ti.floor(a/b)*b

print(fmod(97,3))
```

**Log/Screenshots**
```
$ python broke.py
[Taichi] version 0.9.0, llvm 10.0.0, commit 0c432a37, win, python 3.9.7
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "C:\Users\whorfin\Documents\taichi\broke.py", line 6, in <module>
    @ti.pyfunc
  File "C:\Users\whorfin\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\__init__.py", line 62, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'pyfunc'

```

Amusingly, if I change the `@ti.pyfunc` to `@ti.func`, I get this:
```
[Taichi] version 0.9.0, llvm 10.0.0, commit 0c432a37, win, python 3.9.7
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File ""C:\Users\whorfin\Documents\taichi\broke.py", line 10, in <module>
    print(fmod(97,3))
  File "C:\Users\whorfin\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\lang\kernel_impl.py", line 58, in decorated
    return fun.__call__(*args)
  File "C:\Users\whorfin\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\lang\kernel_imp
l.py", line 157, in __call__
    raise TaichiSyntaxError(
taichi.lang.exception.TaichiSyntaxError: Taichi functions cannot be called from Python-scope. Use @ti.pyfunc if you wish to call Taichi functions from both Python-scope and Taichi-scope.
```

So I wondered if something had changed but not been documented, but this message seems to clearly indicate that `@ti.pyfunc` is still required?

**Comment by strongoier** [comment]
cc: @lin-hitonami

**Comment by whorfin** [comment]
Thank you for the clear explanation and recommended solution, this solved my problem.
