### ISSUE TITLE
0.9.0 removed ti.mod, update docs?

### ISSUE THREAD

**Issue by whorfin** [taichi-dev/taichi#4425]
**Describe the bug**
More 0.8.8 code broken by 0.9.0

```py
import math
import taichi as ti

ti.init()

@ti.func
def test(a, b):
    print(ti.mod(a,b))

@ti.kernel
def cal():
    test(97, 3)

cal()
```

```
# on 0.8.8 this worked:
$ python test-mod.py
[Taichi] version 0.8.8, latest version 0.9.0, llvm 10.0.0, commit 7bae9c77, win, python 3.9.7
[Taichi] Starting on arch=x64
1
# on 0.9.0 it is broken:
$ python test-mod.py
[Taichi] version 0.9.0, llvm 10.0.0, commit 0c432a37, win, python 3.9.7
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "C:\Users\whorfin\Documents\test-mod.py", line 14, in <module>
    cal()
  File "C:\Users\whorfin\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\lang\kernel_impl.py", line 732, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiCompilationError:
On line 12 of file "C:\Users\whorfin\Documents\test-mod.py", in cal:
    test(97, 3)
    ^^^^^^^^^^^
On line 8 of file "C:\Users\whorfin\Documents\test-mod.py", in test:
    print(ti.mod(a,b))
          ^^^^^^
Traceback (most recent call last):
  File "C:\Users\whorfin\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\lang\ast\ast_transformer_utils.py", line 20, in __call__
    return method(ctx, node)
  File "C:\Users\whorfin\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\lang\ast\ast_transformer.py", line 533, in build_Attribute
    node.ptr = getattr(node.value.ptr, node.attr)
  File "C:\Users\whorfin\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\__init__.py", l
ine 62, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'mod'
```
Should this go in [Taichi v0.9 API changes](https://docs.google.com/spreadsheets/d/1FMECCsPMVDjzFN9p3Xy2e4CaA-ru9-lIHb1if-7zgLY/edit#gid=0)?

**Comment by qiao-bo** [comment]
cc @strongoier

**Comment by strongoier** [comment]
Users can always simply write `a % b` just as in Python. `ti.mod()` was previously an accidentally-exposed internal API, so we decided to hide it.  @lin-hitonami Shall we record these changes in [Taichi v0.9 API changes](https://docs.google.com/spreadsheets/d/1FMECCsPMVDjzFN9p3Xy2e4CaA-ru9-lIHb1if-7zgLY/edit#gid=0) as well?

**Comment by lin-hitonami** [comment]
Yes, I think so too.

**Comment by strongoier** [comment]
> Yes, I think so too.

Could you help record them? You know them best I guess :-)

**Comment by lin-hitonami** [comment]
> > Yes, I think so too.
> 
> Could you help record them? You know them best I guess :-)

Updated.
