### ISSUE TITLE
Cannot reuse anonymous variables to receive multiple return values with different types

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#4459]
**Describe the bug**
Cannot reuse anonymous variables to receive multiple return values with different types.

**To Reproduce**

```py
import taichi as ti

ti.init()

@ti.func
def foo():
    return 1, ti.Vector([1])


@ti.kernel
def bar():
    _, _ = foo()

bar()
```

```bash
Traceback (most recent call last):
  File "a.py", line 14, in <module>
    bar()
  File "/Users/yuanming/Library/Python/3.8/lib/python/site-packages/taichi/lang/kernel_impl.py", line 732, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiSyntaxError:
On line 12 of file "a.py", in bar:
    _, _ = foo()
    ^^^^^^^^^^^^
cannot augassign taichi class <class 'taichi.lang.matrix.Matrix'> to scalar expr
```

**Comment by yuanming-hu** [comment]
This can possibly be fixed by minor updates to the AST transformation process. Welcome contribution!
