### ISSUE TITLE
Vulkan的相关问题

### ISSUE THREAD

**Issue by MengMeng3399** [taichi-dev/taichi#4495]
![($N`$MC%JOLUKQ`QVFBU`U5](https://user-images.githubusercontent.com/86776127/157420917-e5dff201-4b4e-4575-80dc-f64144efdd33.png)

怎么解决怎么问题？？

**Comment by k-ye** [comment]
Could you follow the bug report template and fill in more details please, thanks

**Comment by MengMeng3399** [comment]
**Describe the bug：**
Issues related to Vulkan's use

**To Reproduce：**
the examples provided in [examples/ggui_examples](https://github.com/taichi-dev/taichi/tree/master/python/taichi/examples/ggui_examples)

**Log/Screenshots**

```
> C:\Programe\project-2\venv\Scripts\python.exe C:/Programe/project-2/src/Multiple_fluid/3D_Study.py
[Taichi] version 0.9.1, llvm 10.0.0, commit e2e0e669, win, python 3.8.5
[Taichi] Starting on arch=vulkan
[I 03/09/22 20:01:08.523 3756] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:pick_physical_device@340] Found Vulkan Device 0 (Intel(R) UHD Graphics 630)
[I 03/09/22 20:01:08.523 3756] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device_creator.cpp:create_logical_device@406] Vulkan Device "Intel(R) UHD Graphics 630" supports Vulkan 0 version 1.2.151
[E 03/09/22 20:01:18.569 3756] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device.cpp:submit@1456] Vulkan Error : -4 : failed to submit command buffer


***********************************
* Taichi Compiler Stack Traceback *
***********************************
0x7ffab7795056: taichi::Logger::error in taichi_core.pyd
0x7ffab7b4b39f: taichi::lang::vulkan::VkRuntime::add_root_buffer in taichi_core.pyd
0x7ffab7b24e69: taichi::lang::vulkan::VkRuntime::synchronize in taichi_core.pyd
0x7ffab787ff7b: taichi::lang::Program::synchronize in taichi_core.pyd
0x7ffab788bfe9: taichi::lang::Program::get_llvm_program_impl in taichi_core.pyd
0x7ffab77fa860: taichi::ui::vulkan::SwapChain::surface in taichi_core.pyd
0x7ffab7cadcad: PyInit_taichi_core in taichi_core.pyd
0x7ffab7b8059d: PyInit_taichi_core in taichi_core.pyd
0x7ffabdb41bc4: PyCFunction_Call in python38.dll
0x7ffabdb431fa: PyObject_MakeTpCall in python38.dll
0x7ffabdc77cfe: Py_gitversion in python38.dll
0x7ffabdb592b8: PyEval_EvalCodeWithName in python38.dll
0x7ffabdb5aa7f: PyFunction_Vectorcall in python38.dll
0x7ffabdb769de: PyVectorcall_Call in python38.dll
0x7ffabdb7686f: PySequence_GetItem in python38.dll
0x7ffabdb61700: PyEval_EvalFrameDefault in python38.dll
0x7ffabdb5fad3: PyEval_EvalFrameDefault in python38.dll
0x7ffabdb5a99d: PyFunction_Vectorcall in python38.dll
0x7ffabdb769de: PyVectorcall_Call in python38.dll
0x7ffabdb7686f: PySequence_GetItem in python38.dll
0x7ffabdb61700: PyEval_EvalFrameDefault in python38.dll
0x7ffabdb592b8: PyEval_EvalCodeWithName in python38.dll
0x7ffabdb5aa7f: PyFunction_Vectorcall in python38.dll
0x7ffabdb77997: PyNumber_Long in python38.dll
0x7ffabdb75d23: PyArg_Parse_SizeT in python38.dll
0x7ffabdb5e792: PyEval_EvalFrameDefault in python38.dll
0x7ffabdb5a99d: PyFunction_Vectorcall in python38.dll
0x7ffabdb769de: PyVectorcall_Call in python38.dll
0x7ffabdb7686f: PySequence_GetItem in python38.dll
0x7ffabdb61700: PyEval_EvalFrameDefault in python38.dll
0x7ffabdb592b8: PyEval_EvalCodeWithName in python38.dll
0x7ffabdb61027: PyEval_EvalFrameDefault in python38.dll
0x7ffabdb5a99d: PyFunction_Vectorcall in python38.dll
0x7ffabdb769de: PyVectorcall_Call in python38.dll
0x7ffabdb7686f: PySequence_GetItem in python38.dll
0x7ffabdb61700: PyEval_EvalFrameDefault in python38.dll
0x7ffabdb592b8: PyEval_EvalCodeWithName in python38.dll
0x7ffabdb5aa7f: PyFunction_Vectorcall in python38.dll
0x7ffabdb77997: PyNumber_Long in python38.dll
0x7ffabdb75d23: PyArg_Parse_SizeT in python38.dll
0x7ffabdb5e792: PyEval_EvalFrameDefault in python38.dll
0x7ffabdb5d8dd: PyEval_EvalFrameDefault in python38.dll
0x7ffabdb592b8: PyEval_EvalCodeWithName in python38.dll
0x7ffabdbaf4c7: PyEval_EvalCodeEx in python38.dll
0x7ffabdbaf425: PyEval_EvalCode in python38.dll
0x7ffabdbaed06: PyFuture_FromASTObject in python38.dll
0x7ffabdbaec95: PyFuture_FromASTObject in python38.dll
0x7ffabdbbd830: PyRun_FileExFlags in python38.dll
0x7ffabdbbdcef: PyRun_SimpleFileExFlags in python38.dll
0x7ffabdd072f7: PyRun_AnyFileExFlags in python38.dll
0x7ffabdc8bc4b: Py_gitversion in python38.dll
0x7ffabdbbc9bc: Py_RunMain in python38.dll
0x7ffabdbbc845: Py_RunMain in python38.dll
0x7ffabdbbc7f1: Py_Main in python38.dll
0x7ff620761258: Unknown Function in python.exe
0x7ffb172f7034: BaseThreadInitThunk in KERNEL32.DLL
0x7ffb182c2651: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install
[E 03/09/22 20:01:18.688 3756] [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device.cpp:submit@1456] Vulkan Error : -4 : failed to submit command buffer


***********************************
* Taichi Compiler Stack Traceback *
***********************************
Traceback (most recent call last):
  File "C:/Programe/project-2/src/Multiple_fluid/3D_Study.py", line 80, in <module>
    init_scene()
  File "C:/Programe/project-2/src/Multiple_fluid/3D_Study.py", line 26, in init_scene
    x[i, j] = ti.Vector([
  File "C:\Programe\project-2\venv\lib\site-packages\taichi\lang\util.py", line 226, in wrapped
    return func(*args, **kwargs)
  File "C:\Programe\project-2\venv\lib\site-packages\taichi\lang\matrix.py", line 1263, in __setitem__
    self[key]._set_entries(value)
  File "C:\Programe\project-2\venv\lib\site-packages\taichi\lang\util.py", line 226, in wrapped
    return func(*args, **kwargs)
  File "C:\Programe\project-2\venv\lib\site-packages\taichi\lang\matrix.py", line 412, in _set_entries
    self[i, j] = value[i][j]
  File "C:\Programe\project-2\venv\lib\site-packages\taichi\lang\util.py", line 226, in wrapped
    return func(*args, **kwargs)
  File "C:\Programe\project-2\venv\lib\site-packages\taichi\lang\matrix.py", line 393, in __setitem__
    self._set_entry(i, j, item)
  File "C:\Programe\project-2\venv\lib\site-packages\taichi\lang\matrix.py", line 255, in _set_entry
    self.entries[idx].accessor.setter(e, *self.entries[idx].key)
  File "C:\Programe\project-2\venv\lib\site-packages\taichi\lang\field.py", line 301, in setter
    snode.write_float(key, value)
RuntimeError: [D:/a/taichi/taichi/taichi/backends/vulkan/vulkan_device.cpp:submit@1456] Vulkan Error : -4 : failed to submit command buffer
0x7ffab7795056: ?error@Logger@taichi@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z in taichi_core.pyd
0x7ffab7b4b39f: ?add_root_buffer@VkRuntime@vulkan@lang@taichi@@QEAAX_K@Z in taichi_core.pyd
0x7ffab7b24e69: ?synchronize@VkRuntime@vulkan@lang@taichi@@QEAAXXZ in taichi_core.pyd
0x7ffab7881edc: ?finalize@Program@lang@taichi@@QEAAXXZ in taichi_core.pyd
0x7ffab788432f: ??1Program@lang@taichi@@QEAA@XZ in taichi_core.pyd
0x7ffab7ca33cb: PyInit_taichi_core in taichi_core.pyd
0x7ffab7b862eb: PyInit_taichi_core in taichi_core.pyd
0x7ffab7b8603e: PyInit_taichi_core in taichi_core.pyd
0x7ffabdb361f9: _PyObject_GetDictPtr in python38.dll
0x7ffabdb8f5e8: PyDict_Clear in python38.dll
0x7ffabdb8dddc: PyObject_ClearWeakRefs in python38.dll
0x7ffabdb91f8d: _PyDict_MaybeUntrack in python38.dll
0x7ffabdc48491: _PyGC_CollectNoFail in python38.dll
0x7ffabdbad08b: PyImport_Cleanup in python38.dll
0x7ffabdbd3a12: Py_FinalizeEx in python38.dll
0x7ffabdbbc84a: Py_RunMain in python38.dll
0x7ffabdbbc7f1: Py_Main in python38.dll
0x7ff620761258: Unknown Function in python.exe
0x7ffb172f7034: BaseThreadInitThunk in KERNEL32.DLL
0x7ffb182c2651: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install
[E 03/09/22 20:01:18.753 3756] Received signal 22 (SIGABRT)


***********************************
* Taichi Compiler Stack Traceback *
***********************************
0x7ffab78ec60a: ?get_llvm_program_impl@Program@lang@taichi@@QEAAPEAVLlvmProgramImpl@23@XZ in taichi_core.pyd
0x7ffb15d21881: raise in ucrtbase.dll
0x7ffb15d22851: abort in ucrtbase.dll
0x7ffb15d21f9f: terminate in ucrtbase.dll
0x7ff620761f62: Unknown Function in python.exe
0x7ffb15a8b857: UnhandledExceptionFilter in KERNELBASE.dll
0x7ffb183151b0: memset in ntdll.dll
0x7ffb182fc766: __C_specific_handler in ntdll.dll
0x7ffb183120cf: __chkstk in ntdll.dll
0x7ffb182c1454: RtlRaiseException in ntdll.dll
0x7ffb182c11a5: RtlRaiseException in ntdll.dll
0x7ffb159b4f69: RaiseException in KERNELBASE.dll
0x7ffb089c6210: _CxxThrowException in VCRUNTIME140.dll
0x7ffab7795084: ?error@Logger@taichi@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z in taichi_core.pyd
0x7ffab7b4b39f: ?add_root_buffer@VkRuntime@vulkan@lang@taichi@@QEAAX_K@Z in taichi_core.pyd
0x7ffab7b24e69: ?synchronize@VkRuntime@vulkan@lang@taichi@@QEAAXXZ in taichi_core.pyd
0x7ffab7881edc: ?finalize@Program@lang@taichi@@QEAAXXZ in taichi_core.pyd
0x7ffab788432f: ??1Program@lang@taichi@@QEAA@XZ in taichi_core.pyd
0x7ffab7ca33cb: PyInit_taichi_core in taichi_core.pyd
0x7ffab7b862eb: PyInit_taichi_core in taichi_core.pyd
0x7ffab7b8603e: PyInit_taichi_core in taichi_core.pyd
0x7ffabdb361f9: _PyObject_GetDictPtr in python38.dll
0x7ffabdb8f5e8: PyDict_Clear in python38.dll
0x7ffabdb8dddc: PyObject_ClearWeakRefs in python38.dll
0x7ffabdb91f8d: _PyDict_MaybeUntrack in python38.dll
0x7ffabdc48491: _PyGC_CollectNoFail in python38.dll
0x7ffabdbad08b: PyImport_Cleanup in python38.dll
0x7ffabdbd3a12: Py_FinalizeEx in python38.dll
0x7ffabdbbc84a: Py_RunMain in python38.dll
0x7ffabdbbc7f1: Py_Main in python38.dll
0x7ff620761258: Unknown Function in python.exe
0x7ffb172f7034: BaseThreadInitThunk in KERNEL32.DLL
0x7ffb182c2651: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/lang/articles/misc/install

```

**Comment by k-ye** [comment]
Hmm, I saw that you were running `Multiple_fluid/3D_Study.py`, which is not from the GGUI examples. Were you able to run any of the GGUI example, though?

> Vulkan Device "Intel(R) UHD Graphics 630" supports Vulkan 0 version 1.2.151

Also it picked the integrated card, could be a driver issue.

@bobcao3 I think we should add a mode to enable/disable the Vulkan validation layer at runtime.

**Comment by MengMeng3399** [comment]
GGUI ：Can run 2D, not 3D

**Comment by MengMeng3399** [comment]
Vulkan version 1.2.151 was not found on the official website， It cannot run even if a lower version is installed

**Comment by AmesingFlank** [comment]
Does `examples/mass_spring_3d_ggui.py` work?
Also, could you please run `vulkaninfo` and paste the output here?
