### ISSUE TITLE
GGUI not supported on Linux with v0.9.2

### ISSUE THREAD

**Issue by xuhao1** [taichi-dev/taichi#4671]
**Describe the bug**
After updating to taichi 0.9.2, the GGUI does not work anymore.

**To Reproduce**
```
python fem128_ggui.py
[Taichi] version 0.9.2, llvm 10.0.0, commit 7a4d73cd, linux, python 3.8.5
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File "fem128_ggui.py", line 96, in <module>
    window = ti.ui.Window('FEM128', (512, 512))
  File "/home/xuhao/anaconda3/lib/python3.8/site-packages/taichi/ui/window.py", line 21, in __init__
    check_ggui_availability()
  File "/home/xuhao/anaconda3/lib/python3.8/site-packages/taichi/ui/utils.py", line 67, in check_ggui_availability
    raise Exception("GGUI Not Available")
Exception: GGUI Not Available
```

Vulkan environment is properly installed.
```
$ vkvia
VIA_INFO:    SDK Found! - Will attempt to run tests
VIA_INFO:       Attempting to run vkcube in 
VIA_INFO:           Command-line: vkcube --c 100 --suppress_popups
/usr/bin/vkcube
Selected GPU 0: NVIDIA GeForce RTX 3080, type: 2
VIA_INFO:           Command-line: vkcube --c 100 --suppress_popups --validate
/usr/bin/vkcube
Selected GPU 0: NVIDIA GeForce RTX 3080, type: 2
SUCCESS: Vulkan analysis completed properly using Vulkan 1.2

```

**Comment by xuhao1** [comment]
@strongoier 
I try again and it does not work either
```
(base) ➜  TaichiSLAM git:(main) ✗ pip install taichi --force-reinstall
Collecting taichi
  Using cached taichi-0.9.2-cp38-cp38-manylinux2014_x86_64.whl (25.5 MB)
Collecting astunparse; python_version < "3.9"
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting sourceinspect>=0.0.4
  Using cached sourceinspect-0.0.4-py3-none-any.whl (3.5 kB)
Collecting numpy
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting astor
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting six<2.0,>=1.6.1
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting wheel<1.0,>=0.23.0
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting dill
  Using cached dill-0.3.4-py2.py3-none-any.whl (86 kB)
Installing collected packages: six, wheel, astunparse, colorama, dill, sourceinspect, numpy, astor, taichi
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: wheel
    Found existing installation: wheel 0.37.1
    Uninstalling wheel-0.37.1:
      Successfully uninstalled wheel-0.37.1
  Attempting uninstall: astunparse
    Found existing installation: astunparse 1.6.3
    Uninstalling astunparse-1.6.3:
      Successfully uninstalled astunparse-1.6.3
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.4
    Uninstalling colorama-0.4.4:
      Successfully uninstalled colorama-0.4.4
  Attempting uninstall: dill
    Found existing installation: dill 0.3.4
    Uninstalling dill-0.3.4:
      Successfully uninstalled dill-0.3.4
  Attempting uninstall: sourceinspect
    Found existing installation: sourceinspect 0.0.4
    Uninstalling sourceinspect-0.0.4:
      Successfully uninstalled sourceinspect-0.0.4
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.3
    Uninstalling numpy-1.22.3:
      Successfully uninstalled numpy-1.22.3
  Attempting uninstall: astor
    Found existing installation: astor 0.8.1
    Uninstalling astor-0.8.1:
      Successfully uninstalled astor-0.8.1
  Attempting uninstall: taichi
    Found existing installation: taichi 0.9.2
    Uninstalling taichi-0.9.2:
      Successfully uninstalled taichi-0.9.2
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow-gpu 2.4.0 requires numpy~=1.19.2, but you'll have numpy 1.22.3 which is incompatible.
tensorflow-gpu 2.4.0 requires six~=1.15.0, but you'll have six 1.16.0 which is incompatible.
Successfully installed astor-0.8.1 astunparse-1.6.3 colorama-0.4.4 dill-0.3.4 numpy-1.22.3 six-1.16.0 sourceinspect-0.0.4 taichi-0.9.2 wheel-0.37.1

```

**Comment by strongoier** [comment]
This confirms my guess. `pip` finds the `manylinux2014` wheel which only contains CPU and CUDA support.
Is it possible to upgrade your `pip` version?

**Comment by xuhao1** [comment]
@strongoier Thanks a lot! updating pip works, it install taichi-0.9.2-cp38-cp38-manylinux_2_27_x86_64.whl (27.5 MB) now and GGUI works.
