### ISSUE TITLE
When a new field is created and filled in, the old field is deleted. "ti.init(arch=ti.opengl)"

### ISSUE THREAD

**Issue by compik710** [taichi-dev/taichi#4890]
When a new field is created and filled in, the old field is deleted.
Only when i use "ti.init(arch=ti.opengl)"
[Taichi] version 1.0.1, llvm 10.0.0, linux, python 3.10.4

For example i run next code:
```
import numpy
import taichi as ti
ti.init(arch=ti.opengl)

arr1 = numpy.full((10,10), 1, dtype=numpy.float32)

fil1 = ti.field(ti.f32, (10,10))
fil1.from_numpy(arr1)
print(fil1[0,0])
```
And received:
```
$ python3 test6.py 
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.10.4
[Taichi] Starting on arch=opengl
1.0
```

But when I added the creation of another field like this:
```
import numpy
import taichi as ti
ti.init(arch=ti.opengl)

arr1 = numpy.full((10,10), 1, dtype=numpy.float32)

fil1 = ti.field(ti.f32, (10,10))
fil1.from_numpy(arr1)


fil2 = ti.field(ti.f32, (10,10)) # <-- this line
print(fil1[0,0])
```
I got:
```
$ python3 test6.py 
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.10.4
[Taichi] Starting on arch=opengl
Traceback (most recent call last):
  File "/home/iokusin/taichi_test/test6.py", line 12, in <module>
    print(fil1[0,0])
  File "/home/iokusin/.local/lib/python3.10/site-packages/taichi/lang/util.py", line 226, in wrapped
    return func(*args, **kwargs)
  File "/home/iokusin/.local/lib/python3.10/site-packages/taichi/lang/field.py", line 292, in __getitem__
    return self.host_accessors[0].getter(*self._pad_key(key))
  File "/home/iokusin/.local/lib/python3.10/site-packages/taichi/lang/field.py", line 305, in getter
    return snode.read_float(key)
IndexError: _Map_base::at
```

This issue only occurs when using "ti.init(arch=ti.opengl)", if you use the processor, it's ok:
```
$ python3 test6.py 
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.10.4
[Taichi] Starting on arch=x64
1.0
```

Maybe it's a bug?

**Comment by bobcao3** [comment]
OpenGL does not support multiple SNode tree. You can try the Vulkan backend instead.

**Comment by bobcao3** [comment]
Moved to #4040

**Comment by compik710** [comment]
ok......... thanks
