### ISSUE TITLE
meet some problems of Voxel Challenge

### ISSUE THREAD

**Issue by zhaoliu143880** [taichi-dev/taichi#4898]
Environment:
`[Taichi] version 1.0.0, llvm 10.0.0, commit 6a15da85, win, python 3.7.9
[Taichi] Starting on arch=vulkan`
Question description:
When I run example1.py which is provided on my Windows with pycharm, I always get errors. （I have upgraded taichi toV1.0.1） ,

```
from scene import Scene
import taichi as ti
from taichi.math import *

scene = Scene(exposure=10)
scene.set_floor(-0.05, (1.0, 1.0, 1.0))


@ti.kernel
def initialize_voxels():
    n = 50
    for i, j in ti.ndrange(n, n):
        if min(i, j) == 0 or max(i, j) == n - 1:
            scene.set_voxel(vec3(i, 0, j), 2, vec3(0.9, 0.1, 0.1))
        else:
            scene.set_voxel(vec3(i, 0, j), 1, vec3(0.9, 0.1, 0.1))

            if ti.random() < 0.04:
                height = int(ti.random() * 20)

                for k in range(1, height):
                    scene.set_voxel(vec3(i, k, j), 1, vec3(0.0, 0.5, 0.9))
                if height:
                    scene.set_voxel(vec3(i, height, j), 2, vec3(1, 1, 1))


initialize_voxels()

scene.finish()

```

This is the address   of the activity and the folders it provides
https://github.com/taichi-dev/community/blob/main/events/voxel-challenge/reference-zh_cn.md

`***********************************
* Taichi Compiler Stack Traceback *
***********************************
Traceback (most recent call last):
  File "C:/Users/无由心/Desktop/suiji-main/example1.py", line 29, in <module>
    scene.finish()
  File "C:\Users\无由心\Desktop\suiji-main\scene.py", line 181, in finish
    canvas.set_image(img)
  File "C:\Users\无由心\Desktop\venv\lib\site-packages\taichi\ui\canvas.py", line 33, in set_image
    self.canvas.set_image(info)
RuntimeError: C:\Users\无由心\Desktop\venv\lib\site-packages\taichi/shaders/SetImage_vk_vert.spv failed to open file!
0x7ffc4628629a: taichi::lang::Program::get_llvm_program_impl in taichi_core.pyd
0x7ffcc7770ef5: seh_filter_exe in ucrtbase.dll
0x7ff69d302338: Unknown Function in python.exe
0x7ffca2b5c090: _C_specific_handler in VCRUNTIME140.dll
0x7ffcc98720cf: _chkstk in ntdll.dll
0x7ffcc9821454: RtlRaiseException in ntdll.dll
0x7ffcc9870bfe: KiUserExceptionDispatcher in ntdll.dll
0x7ffc466b18f5: PyInit_taichi_core in taichi_core.pyd
0x7ffc463f6945: taichi::ui::vulkan::Gui::cleanup in taichi_core.pyd
0x7ffc4640010c: taichi::ui::vulkan::SwapChain::write_image in taichi_core.pyd
0x7ffc46540806: PyInit_taichi_core in taichi_core.pyd
0x7ffc4652742b: PyInit_taichi_core in taichi_core.pyd
0x7ffc4652716e: PyInit_taichi_core in taichi_core.pyd
0x7ffc71476c7f: PyObject_ClearWeakRefs in python37.dll
0x7ffc71476821: PyTuple_New in python37.dll
0x7ffc71476c7f: PyObject_ClearWeakRefs in python37.dll
0x7ffc71476821: PyTuple_New in python37.dll
0x7ffc71476c7f: PyObject_ClearWeakRefs in python37.dll
0x7ffc71476821: PyTuple_New in python37.dll
0x7ffc7149c994: PySet_NextEntry in python37.dll
0x7ffc7149cb4f: PyDict_Clear in python37.dll
0x7ffc7149cac9: PySet_NextEntry in python37.dll
0x7ffc7149c6c7: PySet_NextEntry in python37.dll
0x7ffc7149dd5c: PyWeakref_GetObject in python37.dll
0x7ffc714bb99f: PyGC_CollectNoFail in python37.dll
0x7ffc714998ed: PyImport_Cleanup in python37.dll
0x7ffc714a815a: Py_FinalizeEx in python37.dll
0x7ffc714a09e0: Py_Main in python37.dll
0x7ffc714a09b6: Py_Main in python37.dll
0x7ff69d30126d: Unknown Function in python.exe
0x7ffcc8f47034: BaseThreadInitThunk in KERNEL32.DLL
0x7ffcc9822651: RtlUserThreadStart in ntdll.dll

Internal error occurred. Check out this page for possible solutions:
https://docs.taichi.graphics/lang/articles/install

进程已结束，退出代码为 -1
`

**Comment by neozhaoliang** [comment]
![2022-04-30 19-20-56屏幕截图](https://user-images.githubusercontent.com/23307174/166103498-434c25f5-d377-455e-9fd6-0a8de2c9ec5b.png)

The problem seems due to the "/"s in the paths.  I grepped these patterns in the repo, @AmesingFlank would you please have a look at it?

**Comment by AmesingFlank** [comment]
unix style path shouldn't be a problem on windows.

I'm a bit concerned about the Chinese charactors in the path "无由心" though, as the shader paths use string instead of wide string.

Could you please try removing these charactors? @zhaoliu143880

**Comment by neozhaoliang** [comment]
But the error message shows there are both / and \ in the shader path, I'm not sure if this is still valid.

**Comment by zhaoliu143880** [comment]
可以细说一下如何修改吗，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhao ***@***.***&gt;; 
发送时间: 2022年4月30日(星期六) 晚上7:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taichi-dev/taichi] meet some problems of Voxel Challenge (Issue #4898)





 

 
The problem seems due to the "/"s in the paths.  I grepped these patterns in the repo, @AmesingFlank would you please have a look at it?

**Comment by AmesingFlank** [comment]
> @AmesingFlank But the error message shows there are both / and \ in the shader path, I'm not sure if this is still valid.

This should be fine.

**Comment by AmesingFlank** [comment]
> @AmesingFlank But the error message shows there are both / and \ in the shader path, I'm not sure if this is still valid.

不要让taichi安装目录里有中文，试下把venv放到d盘？

**Comment by ailzhang** [comment]
@zhaoliu143880 Did switching to an English user name fix this? Thanks!
