### ISSUE TITLE
`MatrixNdarray` shape must be a tuple

### ISSUE THREAD

**Issue by FantasyVR** [taichi-dev/taichi#5040]
**Describe the bug**
When setting the shape of `MatrixNdarray` with an integer, an error occurs.

**To Reproduce**

```py
import taichi as ti

ti.init(arch=ti.cpu)


A = ti.MatrixNdarray(n=10, m=3, dtype=ti.f32, shape=10,layout=ti.Layout.AOS)
# A = ti.MatrixNdarray(n=10, m=3, dtype=ti.f32, shape=(10,),layout=ti.Layout.AOS) # works

A.fill(1.0)
```

**Log/Screenshots**

```
$ python test.py 
[Taichi] version 1.0.3, llvm 10.0.0, commit 6f36c5c7, linux, python 3.8.11
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    A = ti.MatrixNdarray(n=10, m=3, dtype=ti.f32, shape=10,layout=ti.Layout.AOS)
  File "/home/py/code/taichi/python/taichi/lang/matrix.py", line 1695, in __init__
    arr_shape = (n, m) + shape if layout == Layout.SOA else shape + (n, m)
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'
```

**Comment by strongoier** [comment]
Hmm.. I don't think it's a bug. `MatrixNdarray` is an implementation class, and it indeed requires shape to be a tuple. The correct user API is `ti.Matrix.ndarray`.

**Comment by FantasyVR** [comment]
Thanks. I  miss using the API. I will just close this issue.
