### ISSUE TITLE
Error when run 'ti example diff_sph' on M1 chip macbook

### ISSUE THREAD

**Issue by Mmmofan** [taichi-dev/taichi#5183]
**Describe the bug**
运行`ti example diff_sph`报错，手动将`${taichi}/examples/autodiff/diff_sph/diff_sph.py`里arch改为ti.cpu则可以运行，但交互操作似乎仍然不work（如space无法暂停等），同样的Python环境在windows下可以正常运行（arch=ti.gpu, GPU device: RTX3060Ti）

**To Reproduce**
Device: MacbookPro with M1-pro
Pyenv:
 - python==3.10.0
 - taichi==1.0.4
 - numpy==1.22.4
 - matplotlib==3.5.2
Others:
 - llvm 10.0.0
 - clang++ 11.1.0

```shell
ti example diff_sph
```

**Log/Screenshots**
```
[Taichi] Starting on arch=metal
/Users/fmo/Pyenv/py3env/lib/python3.10/site-packages/taichi/__init__.py:69: DeprecationWarning: ti.ext_arr is deprecated. Please use ti.types.ndarray instead.
  warnings.warn(
Model at /Users/fmo/Pyenv/py3env/lib/python3.10/site-packages/taichi/examples/autodiff/diff_sph loaded. 
Particle num: 2055
[W 06/15/22 19:31:54.497 2626227] [type_check.cpp:type_check_store@36] [$397] Global store may lose precision: f32 <- f64
On line 177 of file "/Users/fmo/Pyenv/py3env/lib/python3.10/site-packages/taichi/_kernels.py", in ext_arr_to_matrix:
                    mat[I][p] = arr[I, p]
                    ^^^^^^^^^^^^^^^^^^^^^

[W 06/15/22 19:31:54.497 2626227] [type_check.cpp:type_check_store@36] [$408] Global store may lose precision: f32 <- f64
On line 177 of file "/Users/fmo/Pyenv/py3env/lib/python3.10/site-packages/taichi/_kernels.py", in ext_arr_to_matrix:
                    mat[I][p] = arr[I, p]
                    ^^^^^^^^^^^^^^^^^^^^^

[W 06/15/22 19:31:54.497 2626227] [type_check.cpp:type_check_store@36] [$419] Global store may lose precision: f32 <- f64
On line 177 of file "/Users/fmo/Pyenv/py3env/lib/python3.10/site-packages/taichi/_kernels.py", in ext_arr_to_matrix:
                    mat[I][p] = arr[I, p]
                    ^^^^^^^^^^^^^^^^^^^^^

[E 06/15/22 19:31:54.499 2626227] [kernel_utils.cpp:KernelContextAttributes@88] Metal kernel only supports <= 32-bit data, got double
...
```

**Comment by erizmr** [comment]
这个是因为metal后端不支持f64，我们会更新一版，适应metal后端

**Comment by erizmr** [comment]
Hi, @Mmmofan, example 已经更新啦，麻烦你再试试M1看可不可以运行？

**Comment by Mmmofan** [comment]
> Hi, @Mmmofan, example 已经更新啦，麻烦你再试试M1看可不可以运行？

Hi, 我自己拉了最新的taichi代码自己编译了下，运行会报GGUI is not available的错（可以正常运行`ti example pbf2d`），下面是具体的信息：

taichi code branch: master
hash: 5c81ac95d548c2537c16b5b8ddf557df508347cc

Envs:
```
$ echo $CXX                                       
/opt/homebrew/opt/llvm@11/bin/clang++
$ llvm-config --version                   
10.0.0
$ which python3    
/Users/fmo/Pyenv/ti-dev/bin/python3
```

Compiling log:
```
Configuring Project
  Working directory:
    /Users/fmo/Workspace/taichi/_skbuild/macosx-12.0-arm64-3.10/cmake-build
  Command:
    cmake /Users/fmo/Workspace/taichi -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/Users/fmo/Workspace/taichi/_skbuild/macosx-12.0-arm64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.4 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/Users/fmo/Pyenv/ti-dev/lib/python3.10/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/Users/fmo/Pyenv/ti-dev/bin/python3 -DPython3_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -DPython3_LIBRARY:PATH=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib -DPython3_NumPy_INCLUDE_DIRS:PATH=/Users/fmo/Pyenv/ti-dev/lib/python3.10/site-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/Users/fmo/Pyenv/ti-dev/bin/python3 -DPython_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -DPython_LIBRARY:PATH=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib -DPython_NumPy_INCLUDE_DIRS:PATH=/Users/fmo/Pyenv/ti-dev/lib/python3.10/site-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/Users/fmo/Pyenv/ti-dev/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -DPYTHON_LIBRARY:PATH=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/Users/fmo/Pyenv/ti-dev/lib/python3.10/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/Users/fmo/Pyenv/ti-dev/lib/python3.10/site-packages/ninja/data/bin/ninja -DTI_VERSION_MAJOR=1 -DTI_VERSION_MINOR=0 -DTI_VERSION_PATCH=4 -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64

-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is Clang 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/opt/llvm@11/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Taichi Version 1.0.4
       Commit 5c81ac95d548c2537c16b5b8ddf557df508347cc
-- Python: Using /Users/fmo/Pyenv/ti-dev/bin/python3 as the interpreter
    version: 3.10.4
    include: /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10
    library: /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib
    numpy include: /Users/fmo/Pyenv/ti-dev/lib/python3.10/site-packages/numpy/core/include
-- Found PythonInterp: /Users/fmo/Pyenv/ti-dev/bin/python3 (found version "3.10.4") 
-- Found PythonLibs: /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Success
-- Found pybind11: /Users/fmo/Pyenv/ti-dev/lib/python3.10/site-packages/pybind11/include (found version "2.9.2")
Using C++ compiler: /opt/homebrew/opt/llvm@11/bin/clang++
Clang compiler detected. Using std=c++17.
Building for processor arm64
Using float32 (single) precision as real

...bla bla bla

-- Found LLVM 10.0.0
-- Using LLVMConfig.cmake in: /Users/fmo/Workspace/llvm-10.0.0-m1/lib/cmake/llvm
LLVM include dirs /Users/fmo/Workspace/llvm-10.0.0-m1/include
LLVM library dirs /Users/fmo/Workspace/llvm-10.0.0-m1/lib
-- TI_WITH_CUDA_TOOLKIT = OFF
-- Found PythonInterp: /Users/fmo/Pyenv/ti-dev/bin/python3 (found suitable version "3.10.4", minimum required is "3") 
PYTHON_LIBRARIES: /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib
C++ Flags:  -DTI_ISE_NONE -std=c++17 -fsized-deallocation -Wno-deprecated-declarations -Wall  -Werror  -Wno-ignored-attributes  -Wno-nullability-completeness  -Wno-unused-private-field  -Wno-unneeded-internal-declaration  -DTI_ARCH_ARM -DTI_PASS_EXCEPTION_TO_PYTHON -DTI_INCLUDED -DTI_WITH_LLVM -DTI_WITH_METAL
Build type: Release
Clang executable using host compiler /opt/homebrew/opt/llvm@11/bin/clang++
/opt/homebrew/opt/llvm@11/bin/clang++ --version: 11.1.0
-- Compiling LLVM byte code file for arch arm64
-- Configuring done

...bla bla bla

end
```

Runtime log:
```
Running example diff_sph ...
[W 06/18/22 00:41:11.347 3411434] [misc.py:adaptive_arch_select@723] Arch=[<Arch.cuda: 5>] is not supported, falling back to CPU
[Taichi] Starting on arch=arm64
/Users/fmo/Workspace/taichi/python/taichi/__init__.py:71: DeprecationWarning: ti.ext_arr is deprecated. Please use ti.types.ndarray instead.
  warnings.warn(
Model at /Users/fmo/Workspace/taichi/python/taichi/examples/autodiff/diff_sph loaded. 
Particle num: 2055
/Users/fmo/Workspace/taichi/python/taichi/__init__.py:71: DeprecationWarning: ti.any_arr is deprecated. Please use ti.types.ndarray instead.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/fmo/Pyenv/ti-dev/bin/ti", line 33, in <module>
    sys.exit(load_entry_point('taichi', 'console_scripts', 'ti')())
  File "/Users/fmo/Workspace/taichi/python/taichi/_main.py", line 888, in main
    return cli()
  File "/Users/fmo/Workspace/taichi/python/taichi/_main.py", line 30, in wrapper
    result = func(*args, **kwargs)
  File "/Users/fmo/Workspace/taichi/python/taichi/_main.py", line 91, in __call__
    return getattr(self, args.command)(sys.argv[2:])
  File "/Users/fmo/Workspace/taichi/python/taichi/_main.py", line 314, in example
    runpy.run_path(target, run_name='__main__')
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/fmo/Workspace/taichi/python/taichi/examples/autodiff/diff_sph/diff_sph.py", line 562, in <module>
    window = ti.ui.Window("Diff SPH", screen_res, show_window=show_window)
  File "/Users/fmo/Workspace/taichi/python/taichi/ui/window.py", line 22, in __init__
    check_ggui_availability()
  File "/Users/fmo/Workspace/taichi/python/taichi/ui/utils.py", line 138, in check_ggui_availability
    raise GGUINotAvailableException("GGUI is not available.")
taichi.ui.utils.GGUINotAvailableException: GGUI is not available.
```

我尝试把diff_sph.py里的arch改为ti.cpu，还是报相同的错误。

**Comment by erizmr** [comment]
@Mmmofan 如果是build from source，要使用GGUI，需要安装vulkan sdk，编译的时候要加参数`-DTI_WITH_VULKAN:BOOL=ON`，可以参考这个链接：https://docs.taichi.graphics/docs/dev_install#install-optional-dependencies ；
`pip install taichi` 安装的Release版本，GGUI可以不装vulkan sdk直接在 cpu, cuda, vulkan后端运行 （metal后端不支持GGUI）

**Comment by Mmmofan** [comment]
> @Mmmofan 如果是build from source，要使用GGUI，需要安装vulkan sdk，编译的时候要加参数`-DTI_WITH_VULKAN:BOOL=ON`，可以参考这个链接：https://docs.taichi.graphics/docs/dev_install#install-optional-dependencies ； `pip install taichi` 安装的Release版本，GGUI可以不装vulkan sdk直接在 cpu, cuda, vulkan后端运行 （metal后端不支持GGUI）

请问下build from source的话对Vulkan版本有要求吗？我尝试安装了最新的Vulkan，但在设置环境时有提示“This script is now using VK_ADD_LAYER_PATH instead of VK_LAYER_PATH”，然后编译的时候有Vulkan相关报错：
```
CMake Error at cmake/TaichiCore.cmake:399 (find_library):
  Could not find MOLTEN_VK using the following names: libMoltenVK.dylib
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)
```

**Comment by Mmmofan** [comment]
> @Mmmofan 如果是build from source，要使用GGUI，需要安装vulkan sdk，编译的时候要加参数`-DTI_WITH_VULKAN:BOOL=ON`，可以参考这个链接：https://docs.taichi.graphics/docs/dev_install#install-optional-dependencies ； `pip install taichi` 安装的Release版本，GGUI可以不装vulkan sdk直接在 cpu, cuda, vulkan后端运行 （metal后端不支持GGUI）

我重新装了Vulkan，编译后diff_sph可以正常运行了（功能一切正常）。
