### ISSUE TITLE
run 'ti gallery' and bump into problems

### ISSUE THREAD

**Issue by zzz6519003** [taichi-dev/taichi#5300]
```
➜  react git:(main) ✗ ti gallery  
Traceback (most recent call last):
  File "/usr/local/bin/ti", line 6, in <module>
    from taichi._main import main
  File "/Library/Python/3.7/site-packages/taichi/__init__.py", line 3, in <module>
    from taichi._funcs import *
  File "/Library/Python/3.7/site-packages/taichi/_funcs.py", line 3, in <module>
    from taichi.lang import impl, matrix, ops
  File "/Library/Python/3.7/site-packages/taichi/lang/__init__.py", line 1, in <module>
    from taichi.lang import impl, simt
  File "/Library/Python/3.7/site-packages/taichi/lang/impl.py", line 6, in <module>
    from taichi._lib import core as _ti_core
  File "/Library/Python/3.7/site-packages/taichi/_lib/__init__.py", line 1, in <module>
    from taichi._lib.utils import ti_core as core
  File "/Library/Python/3.7/site-packages/taichi/_lib/utils.py", line 102, in <module>
    ti_core = import_ti_core()
  File "/Library/Python/3.7/site-packages/taichi/_lib/utils.py", line 58, in import_ti_core
    core.set_lib_dir(locale_encode(lib_dir))
  File "/Library/Python/3.7/site-packages/taichi/_lib/utils.py", line 65, in locale_encode
    return path.encode(locale.getdefaultlocale()[1])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/locale.py", line 568, in getdefaultlocale
    return _parse_localename(localename)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

```

**Comment by erizmr** [comment]
cc: @neozhaoliang

**Comment by sjwsl** [comment]
Try appending
```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
in your `~/.bashrc` and run
```bash
$ source ~/.bashrc
```

**Comment by neozhaoliang** [comment]
@zzz6519003  Does the solution by @sjwsl  fix your problem?
