### ISSUE TITLE
Can't use `int()` in `ti.func` #539

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#538]
**Describe the bug**
Can't use `int()` in `ti.func`.

**Log/Screenshots**
```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-rylc7s6m
[Taichi] sandbox prepared
[Taichi] version 0.5.3, cpu only, commit 29228a93, python 3.8.1
Traceback (most recent call last):
  File "536.my.py", line 14, in <module>
    func()
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 350, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 248, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 245, in taichi_ast_generator
    compiled()
  File "536.my.py", line 12, in func
    a = foo(t)
  File "536.my.py", line 7, in foo
    return int(x)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Expr'
```

**To Reproduce**
```py
import taichi as ti

ti.init(arch=ti.x64, print_ir=True)

@ti.func
def foo(x):
  return int(x)

@ti.kernel
def func():
  t = 233
  a = foo(t)

func()
```

However, `int()` works in `ti.kernel`:
```py
import taichi as ti

ti.init(arch=ti.x64, print_ir=True)

@ti.kernel
def func():
  t = 233
  a = int(t)

func()
```

Am I expected to use `ti.cast(x, ti.i32)` here? Why is it behaving different in `ti.kernel` and `ti.func`?

**Comment by archibate** [comment]
Seems `print()` is also not transformed to `ti.ti_print`.

**Comment by archibate** [comment]
```
Before preprocessing:
def foo(t):
  print(t)

After preprocessing:
def foo(t_by_value__):
  t = ti.expr_init(t_by_value__)
  ti.ti_print(t)

Before preprocessing:
@ti.kernel
def func():
    t = 233
    print(t)
    foo(t)

After preprocessing:
def func():
  t = ti.expr_init(233)
  ti.ti_print(t)
  foo(t)

<taichi.lang.expr.Expr object at 0x7faa38c41d60>
[debug] t = 233
```

**Comment by archibate** [comment]
Solved, opening PR now.

**Comment by archibate** [comment]
Fixed, closing now.
