### ISSUE TITLE
Release tests tracking issue

### ISSUE THREAD

**Issue by feisuzhu** [taichi-dev/taichi#5445]
This issue tracks broken examples and requests for inclusion.

**Comment by feisuzhu** [comment]
Subject: `ti example` 38
Taichi version: 1.0.4 & master
ti.init: opengl / vulkan

```
Traceback (most recent call last):
  File "/home/proton/dev/taichi/env/bin/ti", line 33, in <module>
    sys.exit(load_entry_point('taichi', 'console_scripts', 'ti')())
  File "/home/proton/dev/taichi/python/taichi/_main.py", line 899, in main
    return cli()
  File "/home/proton/dev/taichi/python/taichi/_main.py", line 31, in wrapper
    result = func(*args, **kwargs)
  File "/home/proton/dev/taichi/python/taichi/_main.py", line 92, in __call__
    return getattr(self, args.command)(sys.argv[2:])
  File "/home/proton/dev/taichi/python/taichi/_main.py", line 327, in example
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/proton/dev/taichi/python/taichi/examples/graph/mpm88_graph.py", line 193, in <module>
    main()
  File "/home/proton/dev/taichi/python/taichi/examples/graph/mpm88_graph.py", line 163, in main
    g_init.run({'x': F_x, 'v': F_v, 'J': F_J})
  File "/home/proton/dev/taichi/python/taichi/graph/_graph.py", line 95, in run
    self._compiled_graph.run(arg_ptrs, arg_ints, arg_floats, arg_doubles)
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: taichi._lib.core.taichi_core.CompiledGraph, arg0: dict) -> None

Invoked with: <taichi._lib.core.taichi_core.CompiledGraph object at 0x7ff47f39e630>, {'x': <taichi._lib.core.taichi_core.Ndarray object at 0x7ff3f891d070>, 'v': <taichi._lib.core.taichi_core.Ndarray object at 0x7ff3f891d1b0>, 'J': <taichi._lib.core.taichi_core.Ndarray object at 0x7ff3f891d270>}, {}, {}, {}
```

**Comment by feisuzhu** [comment]
Subject: ti example 56
Taichi version: master
ti.init: opengl / vulkan

```
Running example taichi_bitmasked ...
[Taichi] Starting on arch=opengl
[I 07/18/22 16:28:07.611 159668] [spirv_codegen.cpp:generate_listgen_kernel@1771] ListGen 1 * 65536
[E 07/18/22 16:28:07.612 159668] [spirv_ir_builder.cpp:add@954] Assertion failure: a.stype.id == b.stype.id


Traceback (most recent call last):
  File "/home/proton/dev/taichi/env/bin/ti", line 33, in <module>
    sys.exit(load_entry_point('taichi', 'console_scripts', 'ti')())
  File "/home/proton/dev/taichi/python/taichi/_main.py", line 899, in main
    return cli()
  File "/home/proton/dev/taichi/python/taichi/_main.py", line 31, in wrapper
    result = func(*args, **kwargs)
  File "/home/proton/dev/taichi/python/taichi/_main.py", line 92, in __call__
    return getattr(self, args.command)(sys.argv[2:])
  File "/home/proton/dev/taichi/python/taichi/_main.py", line 327, in example
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/proton/dev/taichi/python/taichi/examples/features/sparse/taichi_bitmasked.py", line 52, in <module>
    main()
  File "/home/proton/dev/taichi/python/taichi/examples/features/sparse/taichi_bitmasked.py", line 45, in main
    paint_active_pixels(color)
  File "/home/proton/dev/taichi/python/taichi/lang/kernel_impl.py", line 915, in wrapped
    return primal(*args, **kwargs)
  File "/home/proton/dev/taichi/python/taichi/lang/kernel_impl.py", line 842, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "/home/proton/dev/taichi/python/taichi/lang/kernel_impl.py", line 773, in func__
    raise e from None
  File "/home/proton/dev/taichi/python/taichi/lang/kernel_impl.py", line 770, in func__
    t_kernel(launch_ctx)
RuntimeError: [spirv_ir_builder.cpp:add@954] Assertion failure: a.stype.id == b.stype.id
```

**Comment by feisuzhu** [comment]
Subject: difftaichi/diffmpm3d.py
Taichi version: master
ti.init: metal

```
[I 220921 15:01:40 run:197] Running repos/difftaichi/examples/diffmpm3d.py...
[Taichi] Starting on arch=metal
/Users/github/miniforge3/envs/3.8/lib/python3.8/site-packages/taichi/__init__.py:71: DeprecationWarning: ti.ext_arr is deprecated. Please use ti.types.ndarray instead.
  warnings.warn(
n_particles 30495
n_solid 30495
2022-09-21 15:01:41.984 python3[46766:8755685] Error Domain=MTLLibraryErrorDomain Code=3 "Compilation failed: 

program_source:1464:33: error: constexpr variable 'stride' must be initialized by a constant expression
  constant static constexpr int stride = elem_stride * n;
                                ^        ~~~~~~~~~~~~~~~
program_source:1464:54: note: value 3221225472 is outside the range of representable values of type 'int'
  constant static constexpr int stride = elem_stride * n;
                                                     ^
program_source:1819:33: error: constexpr variable 'stride' must be initialized by a constant expression
  constant static constexpr int stride = 0 + S1::stride + S3::stride + S5::stride + S7::stride + S10::stride + S36::stride + S44::stride + S46::stride + S48::stride + S50::stride + S52::stride;
                                ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:1819:98: note: initializer of 'stride' is not a constant expression
  constant static constexpr int stride = 0 + S1::stride + S3::stride + S5::stride + S7::stride + S10::stride + S36::stride + S44::stride + S46::stride + S48::stride + S50::stride + S52::stride;
                                                                                                 ^
program_source:1464:33: note: declared here
  constant static constexpr int stride = elem_stride * n;
                                ^
program_source:1827:33: error: constexpr variable 'elem_stride' must be initialized by a constant expression
  constant static constexpr int elem_stride = S0_ch::stride;
                                ^             ~~~~~~~~~~~~~
program_source:1827:47: note: initializer of 'stride' is not a constant expression
  constant static constexpr int elem_stride = S0_ch::stride;
                                              ^
program_source:1819:33: note: declared here
  constant static constexpr int stride = 0 + S1::stride + S3::stride + S5::stride + S7::stride + S10::stride + S36::stride + S44::stride + S46::stride + S48::stride + S50::stride + S52::stride;
                                ^
program_source:1828:33: error: constexpr variable 'stride' must be initialized by a constant expression
  constant static constexpr int stride = elem_stride * n;
                                ^        ~~~~~~~~~~~~~~~
program_source:1828:42: note: initializer of 'elem_stride' is not a constant expression
  constant static constexpr int stride = elem_stride * n;
                                         ^
program_source:1827:33: note: declared here
  constant static constexpr int elem_stride = S0_ch::stride;
                                ^
program_source:1884:184: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
[[maybe_unused]] void mtl_init_random_seeds( device uint32_t *rand_seeds, const uint thread_position_in_grid, const uint threads_per_grid) { for (int ii = thread_position_in_grid; ii < threads_per_grid; ++ii) { rand_seeds[ii] += ii; } }
                                                                                                                                                                                    ~~ ^ ~~~~~~~~~~~~~~~~
program_source:1897:16: warning: unused variable 'print_alloc_'
  device auto* print_alloc_ = reinterpret_cast<device PrintMsgAllocator*>(print_assert_addr + 300);
               ^
program_source:1895:21: warning: unused variable 'rand_state_'
  device RandState* rand_state_ = reinterpret_cast<device RandState*>(runtime_->rand_seeds + (linear_loop_idx_ % 65536));
                    ^
program_source:1893:16: warning: unused variable 'mem_alloc_'
  device auto *mem_alloc_ = reinterpret_cast<device MemoryAllocator *>(runtime_ + 1);
               ^
" UserInfo={NSLocalizedDescription=Compilation failed: 

program_source:1464:33: error: constexpr variable 'stride' must be initialized by a constant expression
  constant static constexpr int stride = elem_stride * n;
                                ^        ~~~~~~~~~~~~~~~
program_source:1464:54: note: value 3221225472 is outside the range of representable values of type 'int'
  constant static constexpr int stride = elem_stride * n;
                                                     ^
program_source:1819:33: error: constexpr variable 'stride' must be initialized by a constant expression
  constant static constexpr int stride = 0 + S1::stride + S3::stride + S5::stride + S7::stride + S10::stride + S36::stride + S44::stride + S46::stride + S48::stride + S50::stride + S52::stride;
                                ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:1819:98: note: initializer of 'stride' is not a constant expression
  constant static constexpr int stride = 0 + S1::stride + S3::stride + S5::stride + S7::stride + S10::stride + S36::stride + S44::stride + S46::stride + S48::stride + S50::stride + S52::stride;
                                                                                                 ^
program_source:1464:33: note: declared here
  constant static constexpr int stride = elem_stride * n;
                                ^
program_source:1827:33: error: constexpr variable 'elem_stride' must be initialized by a constant expression
  constant static constexpr int elem_stride = S0_ch::stride;
                                ^             ~~~~~~~~~~~~~
program_source:1827:47: note: initializer of 'stride' is not a constant expression
  constant static constexpr int elem_stride = S0_ch::stride;
                                              ^
program_source:1819:33: note: declared here
  constant static constexpr int stride = 0 + S1::stride + S3::stride + S5::stride + S7::stride + S10::stride + S36::stride + S44::stride + S46::stride + S48::stride + S50::stride + S52::stride;
                                ^
program_source:1828:33: error: constexpr variable 'stride' must be initialized by a constant expression
  constant static constexpr int stride = elem_stride * n;
                                ^        ~~~~~~~~~~~~~~~
program_source:1828:42: note: initializer of 'elem_stride' is not a constant expression
  constant static constexpr int stride = elem_stride * n;
                                         ^
program_source:1827:33: note: declared here
  constant static constexpr int elem_stride = S0_ch::stride;
                                ^
program_source:1884:184: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
[[maybe_unused]] void mtl_init_random_seeds( device uint32_t *rand_seeds, const uint thread_position_in_grid, const uint threads_per_grid) { for (int ii = thread_position_in_grid; ii < threads_per_grid; ++ii) { rand_seeds[ii] += ii; } }
                                                                                                                                                                                    ~~ ^ ~~~~~~~~~~~~~~~~
program_source:1897:16: warning: unused variable 'print_alloc_'
  device auto* print_alloc_ = reinterpret_cast<device PrintMsgAllocator*>(print_assert_addr + 300);
               ^
program_source:1895:21: warning: unused variable 'rand_state_'
  device RandState* rand_state_ = reinterpret_cast<device RandState*>(runtime_->rand_seeds + (linear_loop_idx_ % 65536));
                    ^
program_source:1893:16: warning: unused variable 'mem_alloc_'
  device auto *mem_alloc_ = reinterpret_cast<device MemoryAllocator *>(runtime_ + 1);
               ^
}
```
