### ISSUE TITLE
Pass list as vector inputs to kernels

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#5620]
**To reproduce**
```py
import taichi as ti

ti.init()

vec2 = ti.types.vector(2, ti.f32)

@ti.kernel
def test(a: vec2):
    print(a)

test(a=[1, 2])
```

Output:
```
[Taichi] version 1.0.4, llvm 10.0.0, commit 2827db2c, linux, python 3.8.10
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    test(a=[1, 2])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 915, in wrapped
    return primal(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 842, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 722, in func__
    if not isinstance(v[a, b], (int, float)):
TypeError: list indices must be integers or slices, not tuple
```

The user must write 
```

**Comment by ailzhang** [comment]
this looks alright as long as we implicit construct the argument of specified type from the list (which we already supported), wdyt? @lin-hitonami
