### ISSUE TITLE
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vi0dine** [taichi-dev/taichi#566]
Hi I have a problem running fractal.py from tutorial. When I'm using taichi-nightly without CUDA it works well, but with taichi-nightly-cuda-10-1 I'm getting following error:

`[Taichi] mode=release
Share object taichi_core import failed. If you are on Windows, please consider installing "Microsoft Visual C++ Redistributable" (https://aka.ms/vs/16/release/vc_redist.x64.exe)
Traceback (most recent call last):
  File "/home/vi0dine/PycharmProjects/fractal/fractal.py", line 1, in <module>
    import taichi as ti
  File "/home/vi0dine/PycharmProjects/fractal/venv/lib/python3.7/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.main import main
  File "/home/vi0dine/PycharmProjects/fractal/venv/lib/python3.7/site-packages/taichi/main.py", line 6, in <module>
    from taichi.tools.video import make_video, interpolate_frames, mp4_to_gif, scale_video, crop_video, accelerate_video
  File "/home/vi0dine/PycharmProjects/fractal/venv/lib/python3.7/site-packages/taichi/tools/video.py", line 3, in <module>
    import taichi.core as core
  File "/home/vi0dine/PycharmProjects/fractal/venv/lib/python3.7/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import tc_core, build, format, load_module, start_memory_monitoring, \
  File "/home/vi0dine/PycharmProjects/fractal/venv/lib/python3.7/site-packages/taichi/core/util.py", line 176, in <module>
    import_tc_core()
  File "/home/vi0dine/PycharmProjects/fractal/venv/lib/python3.7/site-packages/taichi/core/util.py", line 35, in import_tc_core
    raise e
  File "/home/vi0dine/PycharmProjects/fractal/venv/lib/python3.7/site-packages/taichi/core/util.py", line 31, in import_tc_core
    import taichi_core as core
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
`

Env:
- Ubuntu 18.04
- Nvidia MX230
- CUDA Toolkit 10.1
- CuDNN 7.5

Thanks in advance.

**Comment by yuanming-hu** [comment]
Hi @vi0dine, could you add the folder containing `libcudart.so.10.1` to your `LD_LIBRARY_PATH`?
