### ISSUE TITLE
"Count primes" gives different results on cpu and gpu

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#5935]
The following code computes the number of primes <= n. For `n = 10, 000, 000` the results on CPU and GPU are the same, but for `n = `100, 000, 000` the result returned by GPU is one more than the true answer (which is returned by the CPU backend):

```python
"""Count the number of primes below a given bound.
"""
use_taichi = True  # set False to use native python


def is_prime(n: int):
    result = True
    for k in range(2, int(n**0.5) + 1):
        if n % k == 0:
            result = False
            break
    return result


def count_primes(n: int) -> int:
    count = 0
    for k in range(2, n):
        if is_prime(k):
            count += 1

    return count


if use_taichi:
    import taichi as ti
    ti.init(arch=ti.gpu)
    is_prime = ti.func(is_prime)
    count_primes = ti.kernel(count_primes)

import time

info = "use taichi" if use_taichi else "use python"
start = time.perf_counter()
print(count_primes(100000000))
print(f"time elapsed {info}: {time.perf_counter() - start}/s")
```

On the `Vulkan` and `OpenGL` backends, the above code gives 5761456, which is one bigger than the result returned by the CPU (5761455,  the correct answer).

**Comment by yuanming-hu** [comment]
Maybe it's the accuracy of `n**0.5`? If you change that to a while loop:
```
   k = 2
   while k * k <= n:
        if n % k == 0:
            result = False
            break
        k += 1
```
Does the problem still occur?

**Comment by neozhaoliang** [comment]
@yuanming-hu  Thanks for this solution! The suggested approach crashes on Vulkan backend:

```
MESA-INTEL: error: ../src/intel/vulkan/genX_query.c:428: query timeout (VK_ERROR_DEVICE_LOST)
[E 09/02/22 12:29:51.403 72211] [vulkan_device.cpp:submit@1698] Vulkan Error : -4 : failed to submit command buffer


Traceback (most recent call last):
  File "test.py", line 36, in <module>
    print(count_primes(100000000))
  File "/home/zhao/taichi/python/taichi/lang/kernel_impl.py", line 931, in wrapped
    return primal(*args, **kwargs)
  File "/home/zhao/taichi/python/taichi/lang/kernel_impl.py", line 858, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "/home/zhao/taichi/python/taichi/lang/kernel_impl.py", line 792, in func__
    runtime_ops.sync()
  File "/home/zhao/taichi/python/taichi/lang/runtime_ops.py", line 8, in sync
    impl.get_runtime().sync()
  File "/home/zhao/taichi/python/taichi/lang/impl.py", line 413, in sync
    self.prog.synchronize()
RuntimeError: [vulkan_device.cpp:submit@1698] Vulkan Error : -4 : failed to submit command buffer
[E 09/02/22 12:29:51.465 72211] [vulkan_device.cpp:submit@1698] Vulkan Error : -4 : failed to submit command buffer


[E 09/02/22 12:29:51.465 72211] [vulkan_device.cpp:submit@1698] Vulkan Error : -4 : failed to submit command buffer


terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
已放弃 (核心已转储)
```
