### ISSUE TITLE
taichi does not handle python class mpz

### ISSUE THREAD

**Issue by daedalus** [taichi-dev/taichi#6052]
Hi, 

I can not get to run code with gmpy2 library, taichi does not like mpz anywhere:

```
from gmpy2 import isqrt, mpz
import taichi as ti
ti.init()
@ti.kernel
def squares(n: mpz):
  S = []
  for i in range(0, n+1):
    S.append(isqrt(mpz(i)))
  return S
print(squares(mpz(100)))
```

It  throws the following traceback:
```
[Taichi] version 1.1.2, llvm 10.0.0, commit f25cf4a2, linux, python 3.9.2
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "/home/dclavijo/code/RsaCtfTool/testMPZ.py", line 9, in <module>
    def squares(n: mpz):
  File "/usr/local/lib/python3.9/dist-packages/taichi/lang/kernel_impl.py", line 959, in kernel
    return _kernel_impl(fn, level_of_class_stackframe=3)
  File "/usr/local/lib/python3.9/dist-packages/taichi/lang/kernel_impl.py", line 887, in _kernel_impl
    primal = Kernel(_func,
  File "/usr/local/lib/python3.9/dist-packages/taichi/lang/kernel_impl.py", line 421, in __init__
    self.extract_arguments()
  File "/usr/local/lib/python3.9/dist-packages/taichi/lang/kernel_impl.py", line 485, in extract_arguments
    raise TaichiSyntaxError(
taichi.lang.exception.TaichiSyntaxError: Invalid type annotation (argument 0) of Taichi kernel: <class 'mpz'>
```

**Comment by bobcao3** [comment]
Taichi does not support using these third party packages inside Taichi scope. Keep in mind, Taichi scope is not the same language as Python.

**Comment by daedalus** [comment]
Does that mean it will not be supported?
