### ISSUE TITLE
The filed in Taichi can only be accessed through the index of I32?

### ISSUE THREAD

**Issue by sanxiadaba** [taichi-dev/taichi#6159]
My system is Win10 and Taichi version is 1.1.3

The filed in Taichi can only be accessed through the index of I32. If default_ip=ti. I64 is set at the beginning, it will fail to access the index below
The following code will report an error
```python
import taichi as ti

ti.init(arch=ti.cpu, default_ip=ti.i64)
n = 1024
val = ti.field(dtype=ti.i64, shape=n)
val.fill(1)


@ti.kernel
def prefix_sum():
    ti.loop_config(serialize=True)
    for i in range(1, 1024):
        val[i] += val[i - 1]


prefix_sum()
print(val)

```
[Taichi] version 1.1.3, llvm 10.0.0, commit 1262a70a, win, python 3.10.7
[Taichi] Starting on arch=x64
C:\Users\001\AppData\Local\Programs\Python\Python310\lib\site-packages\taichi\lang\ast\ast_transformer.py:38: Warning: Casting range_for 
boundary values from i64 to i32, which may cause numerical issues
  warnings.warn(
[I 09/25/22 21:07:25.771 20228] [D:/a/taichi/taichi/taichi/codegen/llvm/llvm_codegen_utils.cpp:check_func_call_signature@134] Function : 
Dense_lookup_element
[I 09/25/22 21:07:25.772 20228] [D:/a/taichi/taichi/taichi/codegen/llvm/llvm_codegen_utils.cpp:check_func_call_signature@135]     Type : 
i8* (i8*, i8*, i32)
[E 09/25/22 21:07:25.773 20228] [D:/a/taichi/taichi/taichi/codegen/llvm/llvm_codegen_utils.cpp:check_func_call_signature@144]   parameter 2 mismatch: required=i32, provided=i64

Traceback (most recent call last):
  File "c:\Code\github\my_python_function\Test\test22.py", line 16, in <module>
    prefix_sum()
  File "C:\Users\001\AppData\Local\Programs\Python\Python310\lib\site-packages\taichi\lang\kernel_impl.py", line 915, in wrapped
    return primal(*args, **kwargs)
  File "C:\Users\001\AppData\Local\Programs\Python\Python310\lib\site-packages\taichi\lang\kernel_impl.py", line 842, in __call__        
    return self.runtime.compiled_functions[key](*args)
  File "C:\Users\001\AppData\Local\Programs\Python\Python310\lib\site-packages\taichi\lang\kernel_impl.py", line 769, in func__
    raise e from None
  File "C:\Users\001\AppData\Local\Programs\Python\Python310\lib\site-packages\taichi\lang\kernel_impl.py", line 766, in func__
    t_kernel(launch_ctx)
RuntimeError: [D:/a/taichi/taichi/taichi/codegen/llvm/llvm_codegen_utils.cpp:check_func_call_signature@144]   parameter 2 mismatch: required=i32, provided=i64

No error will be reported after the transformation

```python
import taichi as ti

ti.init(arch=ti.cpu, default_ip=ti.i64)
n = 1024
val = ti.field(dtype=ti.i64, shape=n)
val.fill(1)


@ti.kernel
def prefix_sum():
    ti.loop_config(serialize=True)
    for i in range(1, 1024):
        val[ti.i32(i)] += val[ti.i32(i - 1)]


prefix_sum()
print(val)

```

**Comment by sanxiadaba** [comment]
ok,thanks your reply



***@***.***
 
From: Zhanlue Yang
Date: 2022-10-11 10:54
To: taichi-dev/taichi
CC: jun; Author
Subject: Re: [taichi-dev/taichi] The filed in Taichi can only be accessed through the index of I32? (Issue #6159)
Closed #6159 as completed via #6276.
―
