### ISSUE TITLE
Failed to cast np.int to int

### ISSUE THREAD

**Issue by giucesar** [taichi-dev/taichi#6186]
**Describe the bug**
When you try to create a pointer block with the argument of the type np.int, it raises an exception. If you simply cast it with int() it works, but it is not easy to diagnose.

**To Reproduce**
```py
import taichi as ti
import numpy as np

ti.init(arch=ti.gpu)

np_int = np.max([0, 1, 2])
block = ti.root.pointer(ti.i, np_int)

```

**Log/Screenshots**

```
[Taichi] version 1.1.3, llvm 10.0.0, commit 1262a70a, osx, python 3.10.6
[Taichi] Starting on arch=metal
Traceback (most recent call last):
  File "/test.py", line 7, in <module>
    block = ti.root.pointer(ti.i, np_int)
  File "/miniconda3/envs/env/lib/python3.10/site-packages/taichi/_snode/fields_builder.py", line 79, in pointer
    return self.root.pointer(indices, dimensions)
  File "//miniconda3/envs/end/lib/python3.10/site-packages/taichi/lang/snode.py", line 52, in pointer
    self.ptr.pointer(axes, dimensions,
TypeError: pointer(): incompatible function arguments. The following argument types are supported:
    1. (self: taichi._lib.core.taichi_python.SNode, arg0: List[taichi._lib.core.taichi_python.Axis], arg1: List[int], arg2: bool) -> taichi._lib.core.taichi_python.SNode


```

**Comment by strongoier** [comment]
Thanks for reporting this! This is indeed a bug and I've submitted #6211 to fix it.
