### ISSUE TITLE
Zero-filling u8 (Vector) fields either gets warning or error

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#6318]
**To Reproduce**

### Case 1

```py
import taichi as ti

ti.init()

img = ti.field(dtype=ti.u8, shape=())


@ti.kernel
def foo():
    img.fill(0)

foo()
```

Output:
```
[Taichi] version 1.1.3, llvm 10.0.0, commit 1262a70a, linux, python 3.8.10
[Taichi] Starting on arch=x64
[W 10/14/22 01:19:36.809 109105] [type_check.cpp:type_check_store@36] [$10] Global store may lose precision: u8 <- i32
File "/home/ubuntu/.local/lib/python3.8/site-packages/taichi/_funcs.py", line 623, in field_fill_taichi_scope:
        F[I] = val
        ^^^^^^^^^^
```

### Case 2

```py
import taichi as ti

ti.init()

img = ti.field(dtype=ti.u8, shape=())


@ti.kernel
def foo():
    img.fill(ti.u8(0))

foo()
```

This one works fine.

### Case 3

```py
import taichi as ti

ti.init()

img = ti.Vector.field(3, dtype=ti.u8, shape=())


@ti.kernel
def foo():
    img.fill(ti.u8(0))


foo()
```

Output:
```
[Taichi] version 1.1.3, llvm 10.0.0, commit 1262a70a, linux, python 3.8.10
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    foo()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 917, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiCompilationError: 
File "test.py", line 10, in foo:
    img.fill(ti.u8(0))
    ^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/taichi/lang/ast/ast_transformer_utils.py", line 25, in __call__
    return method(ctx, node)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/taichi/lang/ast/ast_transformer.py", line 521, in build_Call
    node.ptr = func(*args, **keywords)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/taichi/lang/matrix.py", line 1654, in fill
    assert len(val) == self.n
TypeError: object of type 'Expr' has no len()


```

**Comment by strongoier** [comment]
Here only case 3 is a bug :-) As it has been fixed in #6391, I'll close this issue.
