### ISSUE TITLE
Compilation error triggers segmentation fault

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#6362]
A compilation error in a simple Taichi kernel triggers segmentation fault.

For the following script,

```python
@ti.kernel
def foo():
    a
```

Expected result:
```
Traceback (most recent call last):
  File "test_slice.py", line 16, in <module>
    foo1()
  File "/home/xuyi15/taichi/python/taichi/lang/kernel_impl.py", line 932, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiNameError: 
File "test_slice.py", line 14, in foo1:
    a
    ^
Name "a" is not defined
```

Result on my environment (clang-8++):

```py
free(): double free detected in tcache 2
Segmentation fault (core dumped)
```

The problem appears after #6335. Changing the compiler from clang-8++ to clang-10++ or clang-12++ solves the problem.

**Comment by strongoier** [comment]
#6362 provides a temporary fix but the root cause hasn't been understood yet.
