### ISSUE TITLE
Error while running mpm99/128.py

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#637]
**Describe the bug**
Local vector assigned using `w = [.., ..]` causes a `TypeError: w is Proxy`.

**Log/Screenshots**
```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-jl1drkar
[Taichi] sandbox prepared
[Taichi] version 0.5.7, cpu only, commit 532ea334, python 3.8.2
[W 03/22/20 06:00:36.312] [program.cpp:Program@41] Taichi is not compiled with CUDA.
[W 03/22/20 06:00:36.312] [program.cpp:Program@64] Falling back to x64
Traceback (most recent call last):
  File "examples/mpm99.py", line 96, in <module>
    substep()
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 484, in wrapped
    primal(*args, **kwargs)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 414, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 304, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 301, in taichi_ast_generator
    compiled()
  File "examples/mpm99.py", line 57, in substep
    weight = w[i][0] * w[j][1]
TypeError: unsupported operand type(s) for *: 'Proxy' and 'Proxy'
```

**To Reproduce**
`python examples/mpm99.py`

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**

**Comment by yuanming-hu** [comment]
This was introduced in #625. I believe it's already fixed in #630. Could you please check out the latest `master`?

**Comment by archibate** [comment]
`git pull & ninja -C build`, still same error.

**Comment by archibate** [comment]
You want to test it yourself, and why it's not covered by any test.. We may want `test_local_matrix` for this.

**Comment by archibate** [comment]
Fixed, thanks!
