### ISSUE TITLE
Wrong error message while passing a field into a ndarray

### ISSUE THREAD

**Issue by dio-exploded** [taichi-dev/taichi#6398]
**Describe the bug**
As title. I got an IndexOfBound error instead of telling me that I should not pass a field to a ndarray.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
import taichi as ti

ti.init(arch=ti.vulkan)

@ti.kernel
def foo (arr: ti.types.ndarray(ti.f32, field_dim=2, element_shape=(2,))):
    print(arr.shape[1])

p=ti.Vector.field(n=2, dtype=ti.f32,shape=(1, 1))

foo(p)
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python my_sample_code.py
[Taichi] mode=release
[Taichi] version 0.6.29, llvm 10.0.0, commit b63f6663, linux, python 3.8.3
...
```
```
[Taichi] version 1.1.3, llvm 10.0.0, commit 1262a70a, linux, python 3.9.12
[Taichi] Starting on arch=vulkan
[I 10/21/22 10:47:30.803 86120] [vulkan_device_creator.cpp:pick_physical_device@393] Found Vulkan Device 0 (NVIDIA GeForce RTX 3080)
[I 10/21/22 10:47:30.803 86120] [vulkan_device_creator.cpp:pick_physical_device@393] Found Vulkan Device 1 (llvmpipe (LLVM 12.0.0, 256 bits))
[I 10/21/22 10:47:30.803 86120] [vulkan_device_creator.cpp:find_queue_families@149] Async compute queue 2, graphics queue 0
[I 10/21/22 10:47:30.804 86120] [vulkan_device_creator.cpp:find_queue_families@149] Async compute queue 2, graphics queue 0
[I 10/21/22 10:47:30.804 86120] [vulkan_device_creator.cpp:create_logical_device@461] Vulkan Device "NVIDIA GeForce RTX 3080" supports Vulkan 0 version 1.3.205
Traceback (most recent call last):
  File "/home/taichi/Downloads/a.py", line 11, in <module>
    foo(p)
  File "/home/taichi/miniconda3/lib/python3.9/site-packages/taichi/lang/kernel_impl.py", line 917, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiCompilationError: 
File "/home/taichi/Downloads/a.py", line 7, in foo:
    print(arr.shape[1])
          ^^^^^^^^^^^^
Traceback (most recent call last):
  File "/home/taichi/miniconda3/lib/python3.9/site-packages/taichi/lang/ast/ast_transformer_utils.py", line 25, in __call__
    return method(ctx, node)
  File "/home/taichi/miniconda3/lib/python3.9/site-packages/taichi/lang/ast/ast_transformer.py", line 250, in build_Subscript
    node.ptr = impl.subscript(node.value.ptr,
  File "/home/taichi/miniconda3/lib/python3.9/site-packages/taichi/lang/util.py", line 287, in wrapped
    return func(*args, **kwargs)
  File "/home/taichi/miniconda3/lib/python3.9/site-packages/taichi/lang/impl.py", line 145, in subscript
    return value[_indices[0]]
IndexError: list index out of range

```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by ailzhang** [comment]
@dio-exploded This is a user issue since you pass in field as ndarray. ;) 
For example this works well. 
```
import taichi as ti

ti.init(arch=ti.vulkan)

@ti.kernel
def foo (arr: ti.types.ndarray(ti.f32, field_dim=2, element_shape=(2,))):
    print(arr.shape[1])

p=ti.Vector.ndarray(n=2, dtype=ti.f32,shape=(1, 1))

foo(p)
```
I'm going to close this issue as resolved, but feel free to reopen if you have any followup questions!
