### ISSUE TITLE
taichi.lang.exception.TaichiSyntaxError: Invalid type annotation (argument 0) of Taichi function

### ISSUE THREAD

**Issue by linjing-lab** [taichi-dev/taichi#6778]
**Describe the bug**
Typing error occurs when using the function kernel I constructed, `sortingx` is the package I designed to sort data.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
'''
This is the kernel of sortingx, and I took it out of sortingx.
use `pip install sortingx` to get full typing values.
'''
import random
from sortingx.sorting import Iterable, _T, Optional, Callable, SupportsRichComparison, List
import taichi as ti
ti.init(arch=ti.cpu)

data = [random.randint(0, 100) for _ in range(10000)]

@ti.func
def generate(__iterable: List[_T], key: Optional[Callable[[_T], SupportsRichComparison]]=None) -> List[_T]:
    compare: List[_T] = list(map(key, __iterable)) if key != None else __iterable
    compare: List[_T] = ([[value] for value in compare] if (compare and not isinstance(compare[0], Iterable)) else compare) if key != None else __iterable
    return compare

@ti.func
def core(left: List[_T], right: List[_T], key: Optional[Callable[[_T], SupportsRichComparison]]=None, reverse: bool=False) -> bool:
    if key == None:
        return left < right if reverse else left > right
    for index in range(0, len(left)):
        if left[index] > right[index] and reverse:
            return False
        elif left[index] > right[index] and not reverse:
            return True
        elif left[index] < right[index] and reverse:
            return True
        elif left[index] < right[index] and not reverse:
            return False
    return False

@ti.func
def convert(__iterable: Iterable[_T]) -> List[_T]:
    if isinstance(__iterable, (tuple, str, set, dict)):
        return list(__iterable)
    return __iterable

@ti.kernel
def bubble(__iterable: Iterable[_T], key: Optional[Callable[[_T], SupportsRichComparison]]=None, reverse: bool=False) -> List[_T]:
    '''
    :param __iterable: iterable data.
    :param key: callable function, for example: key=lambda x: x[1], key=lambda x: (x[0], x[1]).
    :param reverse: whether to use descending order. The default is ascending order.
    '''
    __iterable: List[_T] = convert(__iterable)
    compare: List[_T] = generate(__iterable, key)
    for i in range(len(__iterable) - 1):
        flag: bool = False # early stop by adding a bool value named flag
        for j in range(len(__iterable) - i - 1):
            if core(compare[j], compare[j + 1], key, reverse):
                __iterable[j], __iterable[j + 1] = __iterable[j + 1], __iterable[j]
                flag: bool = True
                if key != None:
                    compare[j], compare[j + 1] = compare[j + 1], compare[j]
        if not flag:
            break
    return __iterable

if __name__ == '__main__':
    print(bubble(data))
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python my_sample_code.py
[Taichi] version 1.2.2, llvm 10.0.0, commit 608e4b57, win, python 3.8.12
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "taichi_case.py", line 12, in <module>
    def generate(__iterable: List[_T], key: Optional[Callable[[_T], SupportsRichComparison]]=None) -> List[_T]:
  File "D:\anaconda\lib\site-packages\taichi\lang\kernel_impl.py", line 64, in func
    fun = Func(fn, _classfunc=is_classfunc, is_real_function=is_real_function)
  File "D:\anaconda\lib\site-packages\taichi\lang\kernel_impl.py", line 197, in __init__
    self.extract_arguments()
  File "D:\anaconda\lib\site-packages\taichi\lang\kernel_impl.py", line 321, in extract_arguments
    raise TaichiSyntaxError(
taichi.lang.exception.TaichiSyntaxError: Invalid type annotation (argument 0) of Taichi function: typing.List[~_T]
...
```

**Additional comments**
```
'''
if I just use `list` to typing in kernel function, it also doesn't work.
'''
[Taichi] version 1.2.2, llvm 10.0.0, commit 608e4b57, win, python 3.8.12
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "taichi_case.py", line 12, in <module>
    def generate(__iterable: list, key: Optional[Callable[[_T], SupportsRichComparison]]=None) -> List[_T]:
  File "D:\anaconda\lib\site-packages\taichi\lang\kernel_impl.py", line 64, in func
    fun = Func(fn, _classfunc=is_classfunc, is_real_function=is_real_function)
  File "D:\anaconda\lib\site-packages\taichi\lang\kernel_impl.py", line 197, in __init__
    self.extract_arguments()
  File "D:\anaconda\lib\site-packages\taichi\lang\kernel_impl.py", line 321, in extract_arguments
    raise TaichiSyntaxError(
taichi.lang.exception.TaichiSyntaxError: Invalid type annotation (argument 0) of Taichi function: <class 'list'>
```

**Comment by linjing-lab** [comment]
Now I have corrected my function writing and set the function parameters to global, but such an error has occurred.
```python
import random
# from sortingx.sorting import Iterable, _T, Optional, Callable, SupportsRichComparison, List
import taichi as ti
ti.init(arch=ti.cpu)

data = [random.randint(0, 100) for _ in range(10000)]
key = None
reverse = False

@ti.func
def generate(__iterable, key):
    compare = list(map(key, __iterable)) if key != None else __iterable
    compare = ([[value] for value in compare] if (compare and not isinstance(compare[0], Iterable)) else compare) if key != None else __iterable
    return compare

@ti.func
def core(left, right, key, reverse):
    if key == None:
        return left < right if reverse else left > right
    for index in range(0, len(left)):
        if left[index] > right[index] and reverse:
            return False
        elif left[index] > right[index] and not reverse:
            return True
        elif left[index] < right[index] and reverse:
            return True
        elif left[index] < right[index] and not reverse:
            return False
    return False

@ti.func
def convert(__iterable):
    if isinstance(__iterable, (tuple, str, set, dict)):
        return list(__iterable)
    return __iterable

@ti.kernel
def bubble():
    __iterable = convert(data)
    compare = generate(__iterable, key)
    for i in range(len(__iterable) - 1):
        flag = False # early stop by adding a bool value named flag
        for j in range(len(__iterable) - i - 1):
            if core(compare[j], compare[j + 1], key, reverse):
                __iterable[j], __iterable[j + 1] = __iterable[j + 1], __iterable[j]
                flag = True
                if key != None:
                    compare[j], compare[j + 1] = compare[j + 1], compare[j]
        if not flag:
            break
    return __iterable

if __name__ == '__main__':
    print(bubble())
```
Log:
```
[Taichi] version 1.2.2, llvm 10.0.0, commit 608e4b57, win, python 3.8.12
[Taichi] Starting on arch=x64
demo.py:33: UserWarning: Calling non-taichi function "isinstance". Scope inside the function is not processed by the Taichi AST transformer. The function may not work as expected. Proceed with caution! Maybe you can consider turning it into a @ti.func?
  if isinstance(__iterable, (tuple, str, set, dict)):
Traceback (most recent call last):
  File "demo.py", line 54, in <module>
    print(bubble())
  File "D:\anaconda\lib\site-packages\taichi\lang\kernel_impl.py", line 944, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiSyntaxError:
File "demo.py", line 39, in bubble:
    __iterable = convert(data)
                 ^^^^^^^^^^^^^
File "demo.py", line 34, in convert:
        return list(__iterable)
        ^^^^^^^^^^^^^^^^^^^^^^^
Return inside non-static if/for is not supported
```
Perhaps the `generate` function is too complex?

**Comment by strongoier** [comment]
The main problem here is that for now Taichi cannot operate on complex Python data structures like lists. Taichi operates on its own data structures.
