### ISSUE TITLE
dynamic snode doesn't allocate space for out-of-bound elements, though it's length says it has

### ISSUE THREAD

**Issue by neozhaoliang** [taichi-dev/taichi#6866]
To reproduce:

```python
import taichi as ti
ti.init(debug=True)

x = ti.field(int)
ti.root.dynamic(ti.i, 10).place(x)

@ti.kernel
def test():
    for i in range(100):
        x[i] = i
    print(x.length())  # will print 100
    
for i in range(100):
    print(x[i])
```

In the above code, I defined `x` to be a dynamic snode of length 10, and I appended 100 elements to it in the kernel `test`. The print statement indicates the length of the snode 100, but indeed all elements of indices >=10 are not appended, they are just zeros.

Error message:

```
Traceback (most recent call last):
  File "/home/zhao/test.py", line 15, in <module>
    print(x[i])
  File "/home/zhao/taichi/python/taichi/lang/util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "/home/zhao/taichi/python/taichi/lang/field.py", line 372, in __getitem__
    return self.host_accessors[0].getter(*padded_key)
  File "/home/zhao/taichi/python/taichi/lang/field.py", line 404, in getter
    return snode.read_int(key)
taichi._lib.core.taichi_python.TaichiAssertionError: (kernel=snode_reader_2) Accessing field (S2place<i32>) of size (10) with indices (10)
Traceback (most recent call last):
  File "/home/zhao/test.py", line 15, in <module>
    print(x[i])
  File "/home/zhao/taichi/python/taichi/lang/util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "/home/zhao/taichi/python/taichi/lang/field.py", line 372, in __getitem__
    return self.host_accessors[0].getter(*padded_key)
  File "/home/zhao/taichi/python/taichi/lang/field.py", line 404, in getter
    return snode.read_int(key)
taichi._lib.core.taichi_python.TaichiAssertionError: (kernel=snode_reader_2) Accessing field (S2place<i32>) of size (10) with indices (10)

Traceback (most recent call last):
  File "/home/zhao/test.py", line 15, in <module>
    print(x[i])
  File "/home/zhao/taichi/python/taichi/lang/util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "/home/zhao/taichi/python/taichi/lang/field.py", line 372, in __getitem__
    return self.host_accessors[0].getter(*padded_key)
  File "/home/zhao/taichi/python/taichi/lang/field.py", line 404, in getter
    return snode.read_int(key)
taichi._lib.core.taichi_python.TaichiAssertionError: (kernel=snode_reader_2) Accessing field (S2place<i32>) of size (10) with indices (10)

Traceback (most recent call last):
  File "/home/zhao/test.py", line 15, in <module>
    print(x[i])
  File "/home/zhao/taichi/python/taichi/lang/util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "/home/zhao/taichi/python/taichi/lang/field.py", line 372, in __getitem__
    return self.host_accessors[0].getter(*padded_key)
  File "/home/zhao/taichi/python/taichi/lang/field.py", line 404, in getter
    return snode.read_int(key)
taichi._lib.core.taichi_python.TaichiAssertionError: (kernel=snode_reader_2) Accessing field (S2place<i32>) of size (10) with indices (10)
```

**Comment by neozhaoliang** [comment]
Yes, the code in my original post is problematic. It indeed raises an error in debug mode. I have updated the issue description.

**Comment by FantasyVR** [comment]
I don't know if it is valid to append values to the dynamic nodes using `=` operator. I tried to use the `append` function, it works.

```
import taichi as ti
ti.init(debug=True)

x = ti.field(int)
ti.root.dynamic(ti.i, 10).place(x)

num_loops = 10
@ti.kernel
def test():
    for i in range(num_loops):
        x.append(i)
    print(x.length())  # will print 10

test()
```

But when I set `num_loops=100`, the output is `100` which means the `max_length` arguments of dynamic nodes don't work as expected.

**Comment by neozhaoliang** [comment]
@FantasyVR Thank you for your comment, using `=` should be an error in my code, I have changed that to `append`.

However, the error still pops in the debug mode. This error should not raise, since by design of dynamic snode, `10` is only a pre-allocated size, and once the number of elements appended exceeds this size, a new chunk of `chunk_size` is appended at the end of the pre-allocated array and the snode does grow larger than `10`.

**Comment by lin-hitonami** [comment]
> `10` is only a pre-allocated size

@neozhaoliang `10` is not the pre-allocated size. There is no pre-allocated size for the dynamic SNodes, the memory of size `chunck_size` is first allocated when the first element is inserted.

> But when I set num_loops=100, the output is 100 which means the max_length arguments of dynamic nodes don't work as expected.

`max_length` is expected to be the maximum length of the dynamic SNode, but since we only check whether the access is out-of-bound when `debug=True`, it is an expected behaviour that the program does not raise an error.  @FantasyVR 

> I don't know if it is valid to append values to the dynamic nodes using = operator

If I remember correctly, `x[i] = y` activates (and allocates space for) all the indices from zero to `i`.
