### ISSUE TITLE
Member functions of nested structs cannot be called

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#6917]
Consider this code segment, where the kernel `k` calls a member function of `c1` which is a member of another struct `c2`.
```py
@ti.dataclass
class C1:
    i: int

    @ti.func
    def is0(self):
        return self.i == 0

@ti.dataclass
class C2:
    c1: C1

    @ti.func
    def is0(self):
        return self.c1.is0()

@ti.kernel
def k(j:int):
    c1 = C1(j)
    c2 = C2(c1 = c1)
    print(c1.is0())

k(3)
```
This fails unexpectedly with
```
Traceback (most recent call last):
  File "/Users/dunfanlu/Code/Taichi/taichi/python/taichi/lang/ast/ast_transformer_utils.py", line 25, in __call__
    return method(ctx, node)
  File "/Users/dunfanlu/Code/Taichi/taichi/python/taichi/lang/ast/ast_transformer.py", line 852, in build_Attribute
    node.ptr = getattr(node.value.ptr, node.attr)
  File "/Users/dunfanlu/Code/Taichi/taichi/python/taichi/lang/common_ops.py", line 26, in __getattr__
    raise AttributeError(
AttributeError: 'Struct15' object has no attribute 'is0'
```

**Comment by oliver-batchelor** [comment]
Is this #6652 again?

**Comment by AmesingFlank** [comment]
> Is this #6652 again?

hmm, I don't think it's because I used the same method name. If I use two different names it throws the same error.

**Comment by neozhaoliang** [comment]
Try the current master branch? I don't have this problem on Ubuntu22.04, intel card.

**Comment by neozhaoliang** [comment]
Should be this one: #6949 :P
