### ISSUE TITLE
Bug importing taichi

### ISSUE THREAD

**Issue by aespielberg** [taichi-dev/taichi#701]
Anaconda env, conda 4.8.3 running python3.6.10, taichi nightly 0.5.7 (also tried 0.5.10).  Ubuntu 16.04.  I have a file test.py, line 1 is import taichi as ti, and gives the following result (fails immediately on import).

```
python test.py [Taichi] mode=release
Share object taichi_core import failed. If you are on Windows, please consider installing "Microsoft Visual C++ Redistributable" (https://aka.ms/vs/16/release/vc_redist.x64.exe)
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import taichi as ti
  File "/home/user/anaconda3/envs/my_project/lib/python3.6/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.main import main
  File "/home/user/anaconda3/envs/my_project/lib/python3.6/site-packages/taichi/main.py", line 6, in <module>
    from taichi.tools.video import make_video, interpolate_frames, mp4_to_gif, scale_video, crop_video, accelerate_video
  File "/home/user/anaconda3/envs/my_project/lib/python3.6/site-packages/taichi/tools/video.py", line 3, in <module>
    import taichi.core as core
  File "/home/user/anaconda3/envs/my_project/lib/python3.6/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import tc_core, build, format, load_module, start_memory_monitoring, \
  File "/home/user/anaconda3/envs/my_project/lib/python3.6/site-packages/taichi/core/util.py", line 176, in <module>
    import_tc_core()
  File "/home/user/anaconda3/envs/my_project/lib/python3.6/site-packages/taichi/core/util.py", line 35, in import_tc_core
    raise e
  File "/home/user/anaconda3/envs/my_project/lib/python3.6/site-packages/taichi/core/util.py", line 31, in import_tc_core
    import taichi_core as core
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/user/anaconda3/envs/my_project/lib/python3.6/site-packages/taichi/core/../lib/taichi_core.so)
```

**Comment by archibate** [comment]
Have you tried `apt-get update libc++ libc++abi`?

**Comment by aespielberg** [comment]
I assume you mean upgrade?

I cannot upgrade libc++; E: Broken packages, I'm guessing there's a
dependency problem/conflict there.  libc++abi does not appear to be a
package.

I'll add one more weird detail for context --- this was actually working
earlier today in the 0.5.7 environment, but then later, after a git pull of
my local repo, it for some reason stopped working.

**Comment by aespielberg** [comment]
I fixed the problem, using [this](https://github.com/tensorflow/serving/issues/819#issuecomment-377776784) method

This might be worth including in the installation for 16.04 if possible.
