### ISSUE TITLE
difftaichi/examples/liquid.py can't run on 1.4.0

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#7105]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
# sample code here
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
python liquid.py
[Taichi] version 1.4.0, llvm 15.0.4, commit 9c6acb5f, linux, python 3.10.0
[Taichi] Starting on arch=cuda
/home/lin/anaconda3/envs/p310/lib/python3.10/site-packages/taichi/__init__.py:77: DeprecationWarning: ti.ext_arr is deprecated. Please use ti.types.ndarray instead.
  warnings.warn(
num particles 1000
num particles 2000
num particles 3000
num particles 4000
num particles 5000
num particles 6000
num particles 7000
num particles 8000
num particles 9000
num particles 10000
num particles 11000
num particles 12000
num particles 13000
num particles 14000
num particles 15000
num particles 16000
num particles 17000
num particles 18000
num particles 19000
num particles 20000
num particles 21000
num particles 22000
num particles 23000
num particles 24000
num particles 25000
num particles 26000
num particles 27000
num particles 28000
n_particles 28146
n_solid 15150
:: rand
:: particles
/home/lin/anaconda3/envs/p310/lib/python3.10/site-packages/taichi/__init__.py:77: DeprecationWarning: ti.clear_all_gradients is deprecated. Please use ti.ad.clear_all_gradients instead.
  warnings.warn(
/home/lin/difftaichi/examples/liquid.py:134: UserWarning: Calling non-taichi function "zero_matrix". Scope inside the function is not processed by the Taichi AST transformer. The function may not work as expected. Proceed with caution! Maybe you can consider turning it into a @ti.func?
  cauchy = ti.Matrix(zero_matrix())
Traceback (most recent call last):
  File "/home/lin/difftaichi/examples/liquid.py", line 506, in <module>
    main()
  File "/home/lin/difftaichi/examples/liquid.py", line 447, in main
    l = forward()
  File "/home/lin/difftaichi/examples/liquid.py", line 271, in forward
    p2g(s)
  File "/home/lin/anaconda3/envs/p310/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 957, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiCompilationError: 
File "/home/lin/difftaichi/examples/liquid.py", line 152, in p2g:
                    weight = w[i](0) * w[j](1) * w[k](2)
                             ^^^^^^^
Traceback (most recent call last):
  File "/home/lin/anaconda3/envs/p310/lib/python3.10/site-packages/taichi/lang/ast/ast_transformer_utils.py", line 25, in __call__
    return method(ctx, node)
  File "/home/lin/anaconda3/envs/p310/lib/python3.10/site-packages/taichi/lang/ast/ast_transformer.py", line 549, in build_Call
    node.ptr = func(*args, **keywords)
TypeError: 'Expr' object is not callable
```

**Comment by jim19930609** [comment]
Seems to be an issue with Matrix refactor. Assign to myself for further investigations.

**Comment by strongoier** [comment]
Fixed by https://github.com/taichi-dev/difftaichi/pull/62.
