### ISSUE TITLE
Thread Local Storage Optimisation Bug

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#7263]
There issue provides a minimal repro example for the bug in #7255, and discuss why this is likely a bug with our TLS optimization.

Example:
```py
import taichi as ti
ti.init(ti.cpu, print_ir = True, advanced_optimization = True)

N = 1
p = ti.field(float, N)

@ti.kernel
def k():
    for n in range(N):
        for t in range(2):
            print("outside", p[n])
            for m in range(1):
                print("inside", p[n])
            p[n] = p[n] + 1.0

k()
```
The result printed is
```
outside 0.000000
inside 0.000000
outside 1.000000
inside 0.000000
```
while the expected result is
```
outside 0.000000
inside 0.000000
outside 1.000000
inside 1.000000
```

I suspect this is due to a bug in the TLS optimisation. If we look at the IR, we can see that the reference to `p[n]` in `print("outside", p[n])` and in `p[n] = p[n] + 1.0` are optimised into local storages, while the reference to `p[n]` in `print("inside", p[n])` is still a global read:
```
kernel {
$0 = offloaded range_for(0, 1) grid_dim=0 block_dim=32 
body {
  <f32> $1 = const 1.0
  <i32> $2 = const 1
  <i32> $3 = const 0
  <i32> $4 = loop $0 index 0
  <i32> $5 = const 2
  <f32> $6 = alloca
  <*gen> $7 = get root [S0root][root]
  <*gen> $8 = [S0root][root]::lookup($7, $3) activate = false
  <*gen> $9 = get child [S0root->S1dense] $8
  <*gen> $10 = [S1dense][dense]::lookup($9, $4) activate = false
  <*f32> $11 = get child [S1dense->S2place<f32>] $10
  <f32> $12 = global load $11
  <f32> $13 : local store [$6 <- $12]
  $14 : for in range($3, $5) block_dim=adaptive {
    <f32> $15 = local load [$6]
    print "outside ", $15, "\n"
    $17 : for in range($3, $2) block_dim=adaptive {
      print "inside ", $12, "\n"
    }
    <f32> $19 = add $15 $1
    <f32> $20 : local store [$6 <- $19]
  }
  <f32> $21 = local load [$6]
  $22 : global store [$11 <- $21]
}
}
```

Also, I verified that if `advanced_optimization` is disabled, the program behaves correctly.

cc @strongoier

**Comment by neozhaoliang** [comment]
Here is another similar report:

```python
import taichi as ti
ti.init()
vec3 = ti.math.vec3

@ti.dataclass
class Particle:
    r: vec3

particle = Particle.field(shape=1)

@ti.kernel
def simulate():
    for i in range(1):
        for _ in range(5):
            for __ in range(1):
                print('inside', particle[i].r)
            particle[i].r += vec3(1)
            print('outside', particle[i].r)

simulate()
```

Another (possibly) related bug is, if I use the struct directly instead of putting it into a field, the `atomic_add` operation is not allowed:

```python
import taichi as ti
ti.init()
vec3 = ti.math.vec3

@ti.dataclass
class Particle:
    r: vec3

particle = Particle()

@ti.kernel
def simulate():
    for i in range(1):
        for _ in range(5):
            for __ in range(1):
                print('inside', particle.r)
            particle.r += vec3(1)
            print('outside', particle[i].r)

simulate()
```

The error message is

```

[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "<string>", line 19, in __PYTHON_EL_eval
  File "/home/zhao/workspace/test.py", line 20, in <module>
    simulate()
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 947, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiCompilationError: 
File "/home/zhao/workspace/test.py", line 17, in simulate:
            particle.r += vec3(1)
            ^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/ast/ast_transformer_utils.py", line 26, in __call__
    return method(ctx, node)
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/ast/ast_transformer.py", line 911, in build_AugAssign
    node.ptr = node.target.ptr._augassign(node.value.ptr,
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/common_ops.py", line 272, in _augassign
    self += x
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/common_ops.py", line 184, in __iadd__
    self._atomic_add(other)
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/common_ops.py", line 138, in _atomic_add
    return ops.atomic_add(self, other)
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/ops.py", line 113, in wrapped
    return a._element_wise_writeback_binary(imp_foo, b)
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/matrix.py", line 554, in _element_wise_writeback_binary
    entries = [[foo(self(i, j), other(i, j)) for j in range(self.m)]
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/matrix.py", line 554, in <listcomp>
    entries = [[foo(self(i, j), other(i, j)) for j in range(self.m)]
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/matrix.py", line 554, in <listcomp>
    entries = [[foo(self(i, j), other(i, j)) for j in range(self.m)]
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/ops.py", line 106, in imp_foo
    return foo(x, wrap_if_not_expr(y))
  File "/home/zhao/.local/lib/python3.10/site-packages/taichi/lang/ops.py", line 1243, in atomic_add
    expr.Expr(_ti_core.expr_atomic_add(x.ptr, y.ptr), tb=stack_info()))
AttributeError: 'float' object has no attribute 'ptr'
```

**Comment by strongoier** [comment]
Thanks for reporting this! The bug seems to get introduced from the `CacheLoopInvariantGlobalVars` pass. cc @lin-hitonami 

```
[I 02/02/23 14:04:33.173 3850646] [compile_to_offloads.cpp:operator()@22] [k_c74_0] Atomics demoted I:
kernel {
$0 = offloaded range_for(0, 1) grid_dim=0 block_dim=32 
body {
  <f32> $1 = const 1.0
  <i32> $2 = const 1
  <i32> $3 = const 0
  <i32> $4 = loop $0 index 0
  <*f32> $5 = global ptr [S2place<f32>], index [$4] activate=true
  <i32> $6 = const 2
  $7 : for in range($3, $6) block_dim=adaptive {
    <f32> $8 = global load $5
    print "outside ", $8, "\n"
    $10 : for in range($3, $2) block_dim=adaptive {
      <f32> $11 = global load $5
      print "inside ", $11, "\n"
    }
    <f32> $13 = add $8 $1
    $14 : global store [$5 <- $13]
  }
}
}
[I 02/02/23 14:04:33.173 3850646] [compile_to_offloads.cpp:operator()@22] [k_c74_0] Cache loop-invariant global vars:
kernel {
$0 = offloaded range_for(0, 1) grid_dim=0 block_dim=32 
body {
  <f32> $1 = const 1.0
  <i32> $2 = const 1
  <i32> $3 = const 0
  <i32> $4 = loop $0 index 0
  <*f32> $5 = global ptr [S2place<f32>], index [$4] activate=true
  <i32> $6 = const 2
  <f32> $7 = alloca
  $8 = global load $5
  $9 : local store [$7 <- $8]
  <f32> $10 = alloca
  $11 = global load $5
  $12 : local store [$10 <- $11]
  $13 : for in range($3, $6) block_dim=adaptive {
    $14 = local load [$7]
    print "outside ", $14, "\n"
    <f32> $16 = alloca
    $17 = local load [$10]
    $18 : local store [$16 <- $17]
    $19 : for in range($3, $2) block_dim=adaptive {
      $20 = local load [$16]
      print "inside ", $20, "\n"
    }
    <f32> $22 = add $14 $1
    $23 : local store [$7 <- $22]
  }
  $24 = local load [$7]
  $25 : global store [$5 <- $24]
}
}
```
