### ISSUE TITLE
Vector argument expected to be a Matrix

### ISSUE THREAD

**Issue by AkeelMedina22** [taichi-dev/taichi#7302]
**Describe the bug**
Type hint for customized vector type expecting to be a Matrix when there is no Matrix type defined. 

**To Reproduce**
```py
import taichi as ti
ti.init(arch=ti.gpu)

vec4d = ti.types.vector(4, ti.f64)  # a 64-bit floating-point 4D vector type
v = vec4d(1, 2, 3, 4)  # Create a vector instance, here v = [1.0 2.0 3.0 4.0]

@ti.func
def length(w: vec4d):  # vec4d as type hint
    return w.norm()

@ti.kernel
def test():
    print(length(v))
    
if __name__ == "__main__":
    test()
```

**Log/Screenshots**
```
$ python my_sample_code.py
[Taichi] version 1.4.0, llvm 15.0.1, commit fbe92fd8, win, python 3.9.7
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "c:\Users\akeel\Desktop\taichi_test\math\vector.py", line 36, in <module>
    test()
  File "C:\Users\akeel\AppData\Local\Programs\Python\Python39\lib\site-packages\taichi\lang\kernel_impl.py", line 976, in wrapped    
File "c:\Users\akeel\Desktop\taichi_test\math\vector.py", line 29, in length:
def length(w: vec4d):  # vec4d as type hint
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Argument w of type <taichi.lang.matrix.VectorType object at 0x00000249454E8DF0> is expected to be a Matrix, but got <class 'taichi.lang.matrix.Vector'>.
...
```

**Additional comments**
This is the example taken from: https://docs.taichi-lang.org/docs/type#matrices-and-vectors.

**Comment by AkeelMedina22** [comment]
Is there any update on this issue?

**Comment by mmmovania** [comment]
Hey @AkeelMedina22. Just remove the type hint from w parameter of length function and it works.
```
import taichi as ti
ti.init(arch=ti.gpu)

vec4d = ti.types.vector(4, ti.f64)  # a 64-bit floating-point 4D vector type
v = vec4d(1, 2, 3, 4)  # Create a vector instance, here v = [1.0 2.0 3.0 4.0]

@ti.func
def length(w):   
    return w.norm()

@ti.kernel
def test(): 
    print(length(v))
    
if __name__ == "__main__":
    test()
```
It gives the following output.
```
[Taichi] version 1.4.0, llvm 15.0.1, commit fbe92fd8, win, python 3.10.9
[Taichi] Starting on arch=cuda
5.477226
```
See if this helps

**Comment by AkeelMedina22** [comment]
Interesting, thank you! I hope the same change is made in the documentation.
