### ISSUE TITLE
Rangefor continue gives wrong results

### ISSUE THREAD

**Issue by GaleSeLee** [taichi-dev/taichi#7307]
related to https://github.com/taichi-dev/taichi/pull/7305 and https://github.com/taichi-dev/taichi/pull/7293 conversation
```
import taichi as ti
ti.init(ti.cpu)

def test_cfg_continue():
    x = ti.field(dtype=int, shape=1)
    state = ti.field(dtype=int, shape=1)

    @ti.kernel
    def foo():
        for p in range(1):
            if state[p] == 0:
                x[p] = 1
                continue

            x[p] = 100


    foo()
    print(x[0])
    assert x[0] == 1

test_cfg_continue()
```
Error info(and x[0] will be 0)
```
Traceback (most recent call last):
  File "cfg.py", line 23, in <module>
    test_cfg_continue()
  File "cfg.py", line 21, in test_cfg_continue
    assert x[0] == 1
AssertionError
```

**Comment by lin-hitonami** [comment]
The global store statement representing `x[p] = 1` disappears after a `full_simplify` pass. Could you find which sub-pass of `full_simplify` causes this problem? Thanks!
https://github.com/taichi-dev/taichi/blob/6e7e31629f796c7922672da42ed40e987b2b1710/taichi/transforms/compile_to_offloads.cpp#L272-L274
```
[I 02/06/23 15:09:30.671 1231133] [compile_to_offloads.cpp:operator()@22] [foo_c74_0] Remove loop_unique:
kernel {
$0 = offloaded range_for(0, 1) grid_dim=0 block_dim=32 
body {
  <i32> $1 = const 1
  <i32> $2 = loop $0 index 0
  <*i32> $3 = global ptr [S4place<i32>], index [$2] activate=false
  <i32> $4 = global load $3
  <i32> $5 = const 0
  <i32> $6 = cmp_eq $4 $5
  <i32> $7 = bit_and $6 $1
  $8 : if $7 {
    <*i32> $9 = global ptr [S2place<i32>], index [$2] activate=true
    $10 : global store [$9 <- $1]
    $11 continue (scope=$0)
  }
  <*i32> $12 = global ptr [S2place<i32>], index [$2] activate=true
  <i32> $13 = const 100
  $14 : global store [$12 <- $13]
}
}
[I 02/06/23 15:09:30.671 1231133] [compile_to_offloads.cpp:operator()@22] [foo_c74_0] Simplified before lower access:
kernel {
$0 = offloaded range_for(0, 1) grid_dim=0 block_dim=32 
body {
  <i32> $1 = const 1
  <i32> $2 = loop $0 index 0
  <*i32> $3 = global ptr [S4place<i32>], index [$2] activate=false
  <i32> $4 = global load $3
  <i32> $5 = const 0
  <i32> $6 = cmp_eq $4 $5
  <i32> $7 = bit_and $6 $1
  $8 : if $7 {
    <*i32> $9 = global ptr [S2place<i32>], index [$2] activate=true
    $10 continue (scope=$0)
  }
  <*i32> $11 = global ptr [S2place<i32>], index [$2] activate=true
  <i32> $12 = const 100
  $13 : global store [$11 <- $12]
}
}
```

**Comment by lin-hitonami** [comment]
I guess it might be caused by the `dead_store_elimination` inside the CFG optimization.

**Comment by GaleSeLee** [comment]
> The global store statement representing x[p] = 1 disappears after a full_simplify pass. Could you find which sub-pass of full_simplify causes this problem? Thanks!
> 
> https://github.com/taichi-dev/taichi/blob/6e7e31629f796c7922672da42ed40e987b2b1710/taichi/transforms/compile_to_offloads.cpp#L272-L274
> 
> ```
> [I 02/06/23 15:09:30.671 1231133] [compile_to_offloads.cpp:operator()@22] [foo_c74_0] Remove loop_unique:
> kernel {
> $0 = offloaded range_for(0, 1) grid_dim=0 block_dim=32 
> body {
>   <i32> $1 = const 1
>   <i32> $2 = loop $0 index 0
>   <*i32> $3 = global ptr [S4place<i32>], index [$2] activate=false
>   <i32> $4 = global load $3
>   <i32> $5 = const 0
>   <i32> $6 = cmp_eq $4 $5
>   <i32> $7 = bit_and $6 $1
>   $8 : if $7 {
>     <*i32> $9 = global ptr [S2place<i32>], index [$2] activate=true
>     $10 : global store [$9 <- $1]
>     $11 continue (scope=$0)
>   }
>   <*i32> $12 = global ptr [S2place<i32>], index [$2] activate=true
>   <i32> $13 = const 100
>   $14 : global store [$12 <- $13]
> }
> }
> [I 02/06/23 15:09:30.671 1231133] [compile_to_offloads.cpp:operator()@22] [foo_c74_0] Simplified before lower access:
> kernel {
> $0 = offloaded range_for(0, 1) grid_dim=0 block_dim=32 
> body {
>   <i32> $1 = const 1
>   <i32> $2 = loop $0 index 0
>   <*i32> $3 = global ptr [S4place<i32>], index [$2] activate=false
>   <i32> $4 = global load $3
>   <i32> $5 = const 0
>   <i32> $6 = cmp_eq $4 $5
>   <i32> $7 = bit_and $6 $1
>   $8 : if $7 {
>     <*i32> $9 = global ptr [S2place<i32>], index [$2] activate=true
>     $10 continue (scope=$0)
>   }
>   <*i32> $11 = global ptr [S2place<i32>], index [$2] activate=true
>   <i32> $12 = const 100
>   $13 : global store [$11 <- $12]
> }
> }
> ```

Sure!
