### ISSUE TITLE
[Bug] Wrong compiler error message for ti.func

### ISSUE THREAD

**Issue by Morcki** [taichi-dev/taichi#7334]
**Describe the bug**
Wrong compiler error message for ti.func, expecting type error reports.

**To Reproduce**

```py
# sample code here
import taichi as ti
import taichi.math as tm
ti.init(arch=ti.vulkan, offline_cache=False)

@ti.func
def ComputeUnitSphereDistance(d : tm.vec3) -> ti.f32:
    # The correct one should be: square_length = d.norm_sqr()
    square_length = d * d
    return tm.acos(1 - square_length * 0.5)

@ti.kernel
def Test():
    val = tm.vec3(0, 0, 0)
    ok = 0
    if (ComputeUnitSphereDistance(val) > 0.0):
        ok = 1

Test()
```

**Log/Screenshots**

```
[Taichi] version 1.4.1, llvm 15.0.4, commit e67c674e, linux, python 3.8.10
[Taichi] Starting on arch=vulkan
Traceback (most recent call last):
  File "/home/taichi/Mocki/workspace/dev/hdri_editing/test.py", line 17, in <module>
    Test()
  File "/home/taichi/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 976, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiTypeError: 
`if` conditions must be an integer; found [Tensor (3) i32]. Consider using `if x != 0` instead of `if x` for float values.
```

**Comment by strongoier** [comment]
This is because the return value of a `ti.func / kernel` is not typechecked. We will consider it in the type system refactor plan and solve it in a systematic way.
