### ISSUE TITLE
@ti.data_oriented Vulkan macOS activating/setting Pointer "unsupported"

### ISSUE THREAD

**Issue by jarmitage** [taichi-dev/taichi#7534]
macOS 12.6 (21G115)

```py
import taichi as ti
ti.init(arch=ti.vulkan) # works with `ti.init()`
@ti.data_oriented
class MyClass:
    def __init__(self, n=32):
        self.n = n
        self.field = ti.field(ti.i32)
        self.pointer = ti.root.pointer(ti.i, self.n).place(self.field)
test = MyClass(32)
test.field[0] = 1
```

```sh
> python sketches/tolvera/taichi_sparse_scratch.py
[Taichi] version 1.4.1, llvm 16.0.0git, commit e67c674e, osx, python 3.10.6
[Taichi] Starting on arch=vulkan
RHI Error: Potential non-conformant Vulkan implementation, enabling VK_KHR_portability_subset
RHI Error: Taichi GGUI wide lines feature unavailable due to lack of device support
[E 03/10/23 11:59:19.883 15911111] [spirv_codegen.cpp:visit@424] Not supported.

Traceback (most recent call last):
  File "/test.py", line 10, in <module>
    test.field[0] = 1
  File "/taichi/lang/util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "/taichi/lang/field.py", line 362, in __setitem__
    self.host_accessors[0].setter(value, *self._pad_key(key))
  File "/taichi/lang/field.py", line 418, in setter
    snode.write_int(key, value)
RuntimeError: [spirv_codegen.cpp:visit@424] Not supported.
```

Same error:

```py
import taichi as ti
ti.init(arch=ti.vulkan)
@ti.data_oriented
class MyClass:
    def __init__(self, n=32):
        self.n = n
        self.field = ti.field(ti.i32)
        self.pointer = ti.root.pointer(ti.i, self.n).place(self.field)
    @ti.kernel
    def set(self, i: int, v: int):
        self.field[i] = v
test = MyClass(32)
test.set(0, 1)
```

```py
import taichi as ti
ti.init(arch=ti.vulkan)
@ti.data_oriented
class MyClass:
    def __init__(self, n=32):
        self.n = n
        self.field = ti.field(ti.i32)
        self.pointer = ti.root.pointer(ti.i, self.n).place(self.field)
test = MyClass(32)
@ti.kernel
def set():
    test.field[0] = 1
set()
```

**Comment by feisuzhu** [comment]
Thank you for reporting this, I can reproduce on Linux too.

**Comment by feisuzhu** [comment]
Pointer SNode is not supported on Vulkan at the moment, the error message is confusing.
Nightly builds gives better error message

![2023-03-15-110154_987x263_scrot](https://user-images.githubusercontent.com/857880/225194336-6516e064-ac23-484d-b683-f59b18217b05.png)

**Comment by jarmitage** [comment]
Will it be supported in future? It's a little hard to tell from the docs / dev process!

**Comment by PENGUINLIONG** [comment]
sorry about that but advanced sparse features are only supported in CPU and CUDA backends (these backends are powered by the LLVM backend).

**Comment by jarmitage** [comment]
> sorry about that but advanced sparse features are only supported in CPU and CUDA backends (these backends are powered by the LLVM backend).

Ok, maybe the docs can be made clearer in that case! Thanks

**Comment by jarmitage** [comment]
Closing as "won't fix"
