### ISSUE TITLE
How to run GGUI in threading.Thread?

### ISSUE THREAD

**Issue by jarmitage** [taichi-dev/taichi#7713]
```py
from threading import Thread
import taichi as ti

def render_gui():
    window = ti.ui.Window("Audio", (512, 512))
    canvas = window.get_canvas()
    while window.running:
        # canvas.set_image()
        window.show()

def main():
    ti.init(arch=ti.vulkan)
    gui_thread = Thread(target=render_gui)
    gui_thread.start()
    gui_thread.join()

if __name__=='__main__':
    main()
```

```
taichi_ggui_thread.py
[Taichi] version 1.5.0, llvm 16.0.0git, commit 7b885c28, osx, python 3.10.10
[Taichi] Starting on arch=vulkan
RHI Error: Potential non-conformant Vulkan implementation, enabling VK_KHR_portability_subset
Exception in thread Thread-2 (render_gui):
Traceback (most recent call last):
  File "/.miniconda3/envs/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/.miniconda3/envs/iil-python-tools/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/taichi_ggui_thread.py", line 5, in render_gui
    window = ti.ui.Window("Audio", (512, 512))
  File "/.miniconda3/envs/lib/python3.10/site-packages/taichi/ui/window.py", line 40, in __init__
    self.window = _ti_core.PyWindow(get_runtime().prog, name, res, pos,
RuntimeError: Caught an unknown exception!
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file NSView.m, line 13477.
[1]    5324 trace trap  taichi_ggui_thread.py
```

**Comment by PENGUINLIONG** [comment]
I guess you want to asynchronous rendering and computing but unfortunately it doesn't work with Taichi. Taichi GGUI and kernel launches are mutually exclusive and are implicitly synchronized. And it's not recommended to run Taichi in multiple threads since it doesn't currently support multithreading. You could try multiprocessing and see if it works though.

**Comment by amakiir** [comment]
I just stumbled onto this issue and I can confirm that the taichi GGUI and kernels work if started from different processes. At least in my simple examples.

**Comment by jarmitage** [comment]
> I just stumbled onto this issue and I can confirm that the taichi GGUI and kernels work if started from different processes. At least in my simple examples.

Can you share any examples?

**Comment by amakiir** [comment]
Sure. I got two examples. In one the GGUI is in the foreground and in the other in the background. Both times there are just float values and tuples of float values being passed between the processes in a pipe. I have not yet played around with fields in a multiprocessing context.


GGUI in the foreground:
```python
from multiprocessing import Process, Pipe
from multiprocessing.connection import PipeConnection
import taichi as ti
import time

ti.init(arch=ti.gpu)

@ti.kernel
def some_kernel_computing(data: int) -> float:
    # do some work
    return ti.random()


def background_process(pipe: PipeConnection):
    while True:
        data = pipe.recv()
        if data is None:
            break
        else:
            time.sleep(1)
            pipe.send((some_kernel_computing(data), some_kernel_computing(data), some_kernel_computing(data)))


def render_loop(pipe: PipeConnection):
    mouse_circle = ti.Vector.field(2, dtype=float, shape=(1, ))

    resolution = (800, 400)
    window = ti.ui.Window("MP Rendering in ", res=resolution , vsync=True, pos=(0, 20))
    canvas = window.get_canvas()

    pipe.send(1)
    while window.running:
        if pipe.poll():
            color = pipe.recv()
            print(color)
            canvas.set_background_color(color=color)
            pipe.send(100000)
        mouse = window.get_cursor_pos()
        mouse_circle[0] = ti.Vector([mouse[0], mouse[1]])
        canvas.circles(mouse_circle, color=(0.2, 0.4, 0.6), radius=0.05)

        window.show()


def main():
    pipe_parent, pipe_child = Pipe()
    p = Process(target=background_process, args=(pipe_child,), daemon=True, name="background_process")
    p.start()
    
    render_loop(pipe=pipe_parent)

    pipe_parent.send(None)
    
    p.join()


if __name__ == "__main__":
    main()
```


GGUI in the background:
```python
from multiprocessing import Process, Pipe
from multiprocessing.connection import PipeConnection
import taichi as ti
import time

ti.init(arch=ti.gpu)

@ti.kernel
def some_kernel_computing(data: int) -> float:
    # do some work
    return ti.random()


def foreground_process(pipe: PipeConnection):
    while True:
        if pipe.poll():
            data = pipe.recv()
            if data is None:
                pipe.send(None)
                break
        else:
            time.sleep(1)
            pipe.send((some_kernel_computing(1), some_kernel_computing(1), some_kernel_computing(1)))


def render_loop(pipe: PipeConnection):
    mouse_circle = ti.Vector.field(2, dtype=float, shape=(1, ))

    resolution = (800, 400)
    window = ti.ui.Window("MP Rendering", res=resolution , vsync=True, pos=(0, 20))
    canvas = window.get_canvas()

    while window.running:
        if window.is_pressed(ti.ui.RMB):
            pipe.send(None)
        if pipe.poll():
            color = pipe.recv()
            print(color)
            if color is None:
                break
            canvas.set_background_color(color=color)
        mouse = window.get_cursor_pos()
        mouse_circle[0] = ti.Vector([mouse[0], mouse[1]])
        canvas.circles(mouse_circle, color=(0.2, 0.4, 0.6), radius=0.05)

        window.show()

    pipe.send(None)


def main():
    pipe_parent, pipe_child = Pipe()
    p = Process(target=render_loop, args=(pipe_child,), daemon=True, name="background_process")
    p.start()
    
    foreground_process(pipe=pipe_parent)
    
    p.join()


if __name__ == "__main__":
    main()
```
