### ISSUE TITLE
[lang] Weird error message for wrong argument types in SharedArray initialization

### ISSUE THREAD

**Issue by bobcao3** [taichi-dev/taichi#7817]
```
TaichiCompilationError:
File "C:\Users\bobca\test.py", line 336, in rasterize:
            rasterize_count = ti.simt.block.SharedArray(1, ti.i32)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "E:\Applications\Miniconda3\lib\site-packages\taichi\lang\ast\ast_transformer_utils.py", line 25, in __call__
    return method(ctx, node)
  File "E:\Applications\Miniconda3\lib\site-packages\taichi\lang\ast\ast_transformer.py", line 550, in build_Call
    node.ptr = func(*args, **keywords)
  File "E:\Applications\Miniconda3\lib\site-packages\taichi\lang\simt\block.py", line 57, in __init__
    self.shared_array_proxy = impl.expr_init_shared_array(shape, dtype)
  File "E:\Applications\Miniconda3\lib\site-packages\taichi\lang\util.py", line 301, in wrapped
    return func(*args, **kwargs)
  File "E:\Applications\Miniconda3\lib\site-packages\taichi\lang\impl.py", line 35, in expr_init_shared_array
    ).expr_alloca_shared_array(shape, element_type)
TypeError: expr_alloca_shared_array(): incompatible function arguments. The following argument types are supported:
    1. (self: taichi._lib.core.taichi_python.ASTBuilder, arg0: List[int], arg1: taichi._lib.core.taichi_python.DataType)
-> taichi::lang::Expr

Invoked with: <taichi._lib.core.taichi_python.ASTBuilder object at 0x000002A9A6CBC970>, 1,
<taichi._lib.core.taichi_python.DataType object at 0x000002A78F53CF30>
```

I guess I can mostly read what's wrong here. Not an average user.

**Comment by turbo0628** [comment]
How about
```
rasterize_count = ti.simt.block.SharedArray((1,), ti.i32)
```

**Comment by turbo0628** [comment]
It's my bad, did not properly handle shape which only has one dimension, fixed :)
