### ISSUE TITLE
GGUI scene.mesh fails at compile `copy_all_to_vbo`

### ISSUE THREAD

**Issue by feisuzhu** [taichi-dev/taichi#7870]
**Describe the bug**
GGUI scene.mesh fails at compile `copy_all_to_vbo`

**To Reproduce**

```py
ti.init(ti.vulkan)

vertices         = ti.Vector.field(2, ti.f32, shape=200)
indices          = ti.field(ti.i32, shape=200 * 3)
normals          = ti.Vector.field(3, ti.f32, shape=200)
per_vertex_color = ti.Vector.field(3, ti.f32, shape=200)

color  = (0.5, 0.5, 0.5)
scene = ti.ui.Scene()
scene.mesh(vertices, normals, color, per_vertex_color, vertex_offset=0, vertex_count=50, show_wireframe=True)
```

**Log/Screenshots**
```
[Taichi Build] (base) [work] ☁  ~  python a.py
[Taichi] version 1.7.0, llvm 15.0.4, commit 528d6a83, linux, python 3.10.10
[Taichi] Starting on arch=vulkan
Traceback (most recent call last):
  File "/home/proton/a.py", line 12, in <module>
    scene.mesh(vertices, normals, color, per_vertex_color, vertex_offset=0, vertex_count=50, show_wireframe=True)
  File "/home/proton/dev/taichi/python/taichi/ui/scene.py", line 237, in mesh
    copy_all_to_vbo(vbo, vertices, normals, 0, per_vertex_color if has_per_vertex_color else 0)
  File "/home/proton/dev/taichi/python/taichi/lang/kernel_impl.py", line 976, in wrapped
    raise type(e)("\n" + str(e)) from None
taichi.lang.exception.TaichiCompilationError:
File "/home/proton/dev/taichi/python/taichi/ui/staging_buffer.py", line 70, in copy_all_to_vbo:
            vbo[i][3:6] = normal[i]
                          ^^^^^^^^^
Traceback (most recent call last):
  File "/home/proton/dev/taichi/python/taichi/lang/ast/ast_transformer_utils.py", line 27, in __call__
    return method(ctx, node)
  File "/home/proton/dev/taichi/python/taichi/lang/ast/ast_transformer.py", line 233, in build_Subscript
    node.ptr = impl.subscript(ctx.ast_builder, node.value.ptr, *node.slice.ptr)
  File "/home/proton/dev/taichi/python/taichi/lang/util.py", line 312, in wrapped
    return func(*args, **kwargs)
  File "/home/proton/dev/taichi/python/taichi/lang/impl.py", line 194, in subscript
    return value.__getitem__(_indices)
TypeError: tuple indices must be integers or slices, not Expr
```

**Additional comments**
No

**Comment by jim19930609** [comment]
You missed on positional argument: `indices`:

`scene.mesh(vertices, indices, normals, color, per_vertex_color, vertex_offset=0, vertex_count=50, show_wireframe=True)`

https://docs.taichi-lang.org/api/master/taichi/ui/scene/#taichi.ui.scene.Scene.mesh
