### ISSUE TITLE
module 'taichi' has no attribute 'sum'/ 'reduce' ... and other atributs

### ISSUE THREAD

**Issue by ShMonem** [taichi-dev/taichi#7885]
I have tried many times with different python/taichi versions.. still get the same error.

`Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import taichi as ti
[Taichi] version 1.5.0, llvm 15.0.4, commit 7b885c28, linux, python 3.8.10
>>> x = np.random.rand(10)
>>> x = ti.Vector(x)
>>> y = ti.sum(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shaimaa/.local/lib/python3.8/site-packages/taichi/__init__.py", line 82, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'sum'
'`

**Comment by bobcao3** [comment]
I don't think we provide these attributes. Taichi is a kernel style programming language and the tensor style APIs from numpy are not supported
