### ISSUE TITLE
https://github.com/taichiCourse01/taichi_sph

### ISSUE THREAD

**Issue by baaiy0610** [taichi-dev/taichi#8047]
Hello, when i run this demo code, it shows module 'taichi' has no attribute 'ext_arr'

[Taichi] version 1.6.0, llvm 15.0.5, commit f1c6fbbd, osx, python 3.9.7
Traceback (most recent call last):
  File "/Users/baiyang/Desktop/project/simulation/sph/taichi_sph/demo.py", line 3, in <module>
    from particle_system import ParticleSystem
  File "/Users/baiyang/Desktop/project/simulation/sph/taichi_sph/particle_system.py", line 7, in <module>
    class ParticleSystem:
  File "/Users/baiyang/Desktop/project/simulation/sph/taichi_sph/particle_system.py", line 69, in ParticleSystem
    new_particles_positions: ti.ext_arr(),
  File "/opt/anaconda3/lib/python3.9/site-packages/taichi/__init__.py", line 22, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'ext_arr'

**Comment by erizmr** [comment]
Hi @baaiy0610 , the sph implementation you use is outdated. Please check the repo https://github.com/erizmr/SPH_Taichi for a latest version.
