### ISSUE TITLE
Taichi GGUI not working in WSL2 with cuda

### ISSUE THREAD

**Issue by marekjg** [taichi-dev/taichi#8055]
**Describe the bug**
When trying to create window with GGUI on WSL2, taichi rises error that vulkan is not available.

**To Reproduce**
```py
import taichi as ti

ti.init(arch=ti.cuda)
window = ti.ui.Window(name='Window Title', res = (640, 360), fps_limit=200, pos = (150, 150))
```

**Log/Screenshots**
```
$ python my_sample_code.py
[Taichi] version 1.6.0, llvm 15.0.4, commit f1c6fbbd, linux, python 3.10.10
[Taichi] Starting on arch=cuda
RHI Error: Can not find Vulkan capable devices
Traceback (most recent call last):
  File "/home/marek/phd/stuttering/stuttering_detection/main.py", line 4, in <module>
    window = ti.ui.Window(name='Window Title', res = (640, 360), fps_limit=200, pos = (150, 150))
  File "/home/marek/miniconda3/envs/torch/lib/python3.10/site-packages/taichi/ui/window.py", line 36, in __init__
    self.window = _ti_core.PyWindow(
RuntimeError: Vulkan must be available for GGUI
...
```

**Comment by jim19930609** [comment]
In general, Taichi GGUI is running on Vulkan backend to perform rendering tasks. Can you verify if you have Vulkan SDK installed on your WSL2 system and its directory's included in the system path?

**Comment by jim19930609** [comment]
cc @bobcao3

**Comment by marekjg** [comment]
I have installed Vulkan SDK, here's log for `vulkaninfo` command: [vulkaninfo.log](https://github.com/taichi-dev/taichi/files/11528537/vulkaninfo.log).
And here's error when running `ti.init(arch=ti.vulkan)`:
```python
RHI Error: Can not find Vulkan capable devices
[W 05/22/23 10:03:17.717 27566] [misc.py:adaptive_arch_select@753] Arch=[<Arch.vulkan: 11>] is not supported, falling back to CPU
[Taichi] Starting on arch=x64```

**Comment by jim19930609** [comment]
Interesting... Taichi actually uses `volk` to search for Vulkan libraries. Have you tried Vulkan backend on WSL2 @bobcao3 ? could it be a cross-platform issue with volk on WSL2?

**Comment by PENGUINLIONG** [comment]
You can try lavapipe which is a cpu implementation of vulkan and GGUI should work with that
