### ISSUE TITLE
Running "ti example implicit_fem" will raise error in taichi v1.6.0

### ISSUE THREAD

**Issue by Mathias0** [taichi-dev/taichi#8085]
**Describe the bug**
Running "ti example implicit_fem" will raise error in taichi v1.6.0. the error is : Failed to load cusparse library.
"ti example implicit_fem" did not raise error in taichi v1.4.1.
My enviroment is Windows 10. My Nivdia drivers versions are up-to-date. CUDA version is 11. I tried with CUDA 12, same error keep raising.

**To Reproduce**

```py
import taichi as ti
ti.init(arch=ti.cuda)
A_builder = ti.linalg.SparseMatrixBuilder(3, 3)
solver = ti.linalg.SparseSolver(ti.f32, "LLT")
@ti.kernel
def fill(A: ti.types.sparse_matrix_builder()):
    for i,j in ti.ndrange(3,3):
        A[i,j] += 1
fill(A_builder)
A = A_builder.build()
solver.analyze_pattern(A)
```

**Log/Screenshots**

```
$ python my_sample_code.py
[Taichi] version 1.6.0, llvm 15.0.1, commit f1c6fbbd, win, python 3.10.11
[Taichi] Starting on arch=cuda
[W 05/26/23 13:14:03.363 18012] [cuda_driver.cpp:taichi::lang::CUDADriverBase::load_lib@36] cusparse64_11.dll lib not found.
[E 05/26/23 13:14:03.363 18012] [sparse_solver.cpp:taichi::lang::CuSparseSolver::init_solver@187] Failed to load cusparse library!


Traceback (most recent call last):
  File "my_sample_code.py", line 4, in <module>
    solver = ti.linalg.SparseSolver(ti.f32, "LLT")
  File "...\taichi\linalg\sparse_solver.py", line 34, in __init__
    self.solver = _ti_core.make_cusparse_solver(dtype, solver_type, ordering)
RuntimeError: [sparse_solver.cpp:taichi::lang::CuSparseSolver::init_solver@187] Failed to load cusparse library!
```

**Comment by Mathias0** [comment]
I solved it by full installing CUDA Toolkit. During installing CUDA Toolkit, be sure not to choose the recommanded installation, choose the customized installation instead and tick the CUSPARSE in libraries in Runtime in CUDA.
