### ISSUE TITLE
Unable to implement official examples using ti.gpu.

### ISSUE THREAD

**Issue by hgalytoby** [taichi-dev/taichi#8128]
I changed the official sample ti.cpu to ti.gpu but it doesn't work.

```py
import os
import time
import taichi as ti

N = 50000000

ti.init(arch=ti.gpu, device_memory_GB=1, device_memory_fraction=0.9)


@ti.func
def is_prime(n: int):
    result = True
    for k in range(2, int(n ** 0.5) + 1):
        if n % k == 0:
            result = False
            break
    return result


@ti.kernel
def count_primes(n: int) -> int:
    count = 0
    for k in range(2, n):
        if is_prime(k):
            count += 1

    return count


start = time.perf_counter()
print(f"Number of primes: {count_primes(N)}")
print(f"time elapsed: {time.perf_counter() - start}/s")

```

<img width="599" alt="image" src="https://github.com/taichi-dev/taichi/assets/50397689/e7cf77c1-98ce-4ad7-939b-76260aa3c238">

```py
[Taichi] version 1.6.0, llvm 15.0.1, commit f1c6fbbd, win, python 3.7.8
[Taichi] Starting on arch=cuda


[E 06/02/23 16:36:21.714 12832] [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void * *,unsigned __int64>::operator ()@92] CUDA Error CUDA_ERROR_OUT_OF_MEMORY: out of memory while calling malloc (cuMemAlloc_v2)
Traceback (most recent call last):
  File "C:\Python\newtest\taichi_test.py", line 7, in <module>
    ti.init(arch=ti.gpu, device_memory_GB=1, device_memory_fraction=0.9)
  File "C:\Python\newtest\venv\lib\site-packages\taichi\lang\misc.py", line 463, in init
    impl.get_runtime().prog.materialize_runtime()
RuntimeError: [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void * *,unsigned __int64>::operator ()@92] CUDA Error CUDA_ERROR_OUT_OF_MEMORY: out of memory while calling malloc (cuMemAlloc_v2)
```

view document  https://docs.taichi-lang.org/docs/install#cuda-issues

Using `TI_DEVICE_MEMORY_FRACTION=0.9` and `TI_DEVICE_MEMORY_GB=4` does not work.

When I use `export TI_ENABLE_CUDA=0` the program will not report an error but will have no result .

```python
print(f"Number of primes: {count_primes(N)}")  # 0
```

**Comment by bobcao3** [comment]
You should consider using a smaller amount of memory allocated because the GPU only has 4GB in total. Try 0.5 or 2 GB

**Comment by hgalytoby** [comment]
> You should consider using a smaller amount of memory allocated because the GPU only has 4GB in total. Try 0.5 or 2 GB

I have tried 0.5 0.4 0.3 0.2 0.1, all the same error.

**Comment by lin-hitonami** [comment]
When `device_memory_fraction` is set, `device_memory_GB` does not take effect. Please do not set both at the same time. Try `ti.init(arch=ti.gpu, device_memory_GB=1)` without setting `device_memory_fraction`.

**Comment by hgalytoby** [comment]
> When `device_memory_fraction` is set, `device_memory_GB` does not take effect. Please do not set both at the same time. Try `ti.init(arch=ti.gpu, device_memory_GB=1)` without setting `device_memory_fraction`.

I tried, but same error.

`device_memory_GB=0.5` as well.

<img width="1689" alt="image" src="https://github.com/taichi-dev/taichi/assets/50397689/66f0f7d8-f3a8-4d30-9667-5d1b3e1381b5">
