### ISSUE TITLE
Taichi developer install deletes itself after exit command or opening up a new terminal

### ISSUE THREAD

**Issue by sarahhaha** [taichi-dev/taichi#8144]
After installing taichi using the developer install instructions, (./build.py --shell
and then python3 setup.py develop), I am able to access it using the command ti, but as soon as I type 'exit' or Ctrl+C to exit out of it, it gives the following CommandFailed errors and I am unable to open taichi with ti again. I am also unable to open taichi in a new command prompt after the installation which makes me think that there was a problem with the installation itself.

**To Reproduce**
I have followed the Build Taichi from Source in the Developer Installation page https://docs.taichi-lang.org/docs/dev_install

```py
git clone --recursive https://github.com/taichi-dev/taichi

cd taichi

$env:TAICHI_CMAKE_ARGS += " -DTI_WITH_VULKAN:BOOL=ON -DTI_WITH_CUDA:BOOL=ON"

python build.py --shell

python setup.py develop
```

I am using python 3.10.

**Log/Screenshots**
I have copied this from my command prompt

```
TaichiBuild C:\Users\Taichi\taichi>ti
[Taichi] version 1.7.0, llvm 15.0.1, commit 3660ac8a, win, python 3.10.11

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi-lang.org/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

usage:
    baseline            |-> Archive current benchmark result as baseline
    cache               |-> Manage the offline cache files manually
    changelog           |-> Display changelog of current version
    debug               |-> Debug a single script
    diagnose            |-> System diagnose information
    doc                 |-> Build documentation
    example             |-> Run an example by name (or name.py)
    format              |-> Reformat modified source files
    format_all          |-> Reformat all source files
    gallery             |-> Use mouse to select and run taichi examples in an interactive gui.
    gif                 |-> Convert mp4 file to gif in the same directory
    lint                |-> Run pylint checker for the Python codebase of Taichi
    module              |-> Taichi module tools
    regression          |-> Display benchmark regression test result
    release             |-> Make source code release
    repl                |-> Start Taichi REPL / Python shell with 'import taichi as ti'
    run                 |-> Run a single script
    test                |-> None
    video               |-> Make a video using *.png files in the current directory
    video_crop          |-> Crop video in the same directory
    video_scale         |-> Scale video resolution in the same directory
    video_speed         |-> Speed up video in the same directory

Taichi CLI

positional arguments:
  command     command from the above list to run

options:
  -h, --help  show this help message and exit
>>> Running time: 0.00s

TaichiBuild C:\Users\Taichi\taichi>exit
Traceback (most recent call last):
  File "C:\Users\Taichi\taichi\build.py", line 11, in <module>
    sys.exit(ti_build.entry.main())
  File "C:\Users\Taichi\taichi\.github\workflows\scripts\ti_build\entry.py", line 190, in main
    dispatch.get(options.action, action_notimpl)()
  File "C:\Users\Taichi\taichi\.github\workflows\scripts\ti_build\entry.py", line 99, in action_wheel
    handle_alternate_actions()
  File "C:\Users\Taichi\taichi\.github\workflows\scripts\ti_build\alter.py", line 183, in handle_alternate_actions
    enter_shell()
  File "C:\Users\Taichi\taichi\.github\workflows\scripts\ti_build\alter.py", line 123, in enter_shell
    cmd("/k", "set", "PROMPT=TaichiBuild $P$G")
  File "C:\Users\Taichi\taichi\.github\workflows\scripts\ti_build\tinysh.py", line 160, in __call__
    raise CommandFailed(cmd, code)
ti_build.tinysh.CommandFailed: Command C:\Windows\System32\cmd.exe /k set "PROMPT=TaichiBuild $P$G" failed with code 1

C:\Users\Taichi\taichi>ti                                                                                                                     'ti' is not recognized as an internal or external command,                                                                                    operable program or batch file.     
```

**Additional comments**
This is what I get when I run ti diagnose after a fresh reinstall
TaichiBuild C:\Users\Taichi\taichi>ti diagnose
[Taichi] version 1.7.0, llvm 15.0.1, commit 3660ac8a, win, python 3.10.11

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi-lang.org/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

Taichi system diagnose:

python: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:51:25) [MSC v.1934 64 bit (AMD64)]
system: win32
executable: C:\Users\Taichi\AppData\Local\ti-build-cache\mambaforge\envs\3.10\python.exe
platform: Windows-10-10.0.22621-SP0
architecture: 64bit WindowsPE
uname: uname_result(system='Windows', node='DESKTOP-FH7RIEH', release='10', version='10.0.22621', machine='AMD64')
locale: en_US.cp1252
PATH: C:\Users\Taichi\AppData\Local\ti-build-cache\mambaforge\envs\3.10;C:\Users\Taichi\AppData\Local\ti-build-cache\mambaforge\envs\3.10\Library\mingw-w64\bin;C:\Users\Taichi\AppData\Local\ti-build-cache\mambaforge\envs\3.10\Library\usr\bin;C:\Users\Taichi\AppData\Local\ti-build-cache\mambaforge\envs\3.10\Library\bin;C:\Users\Taichi\AppData\Local\ti-build-cache\mambaforge\envs\3.10\Scripts;C:\Users\Taichi\AppData\Local\ti-build-cache\mambaforge\envs\3.10\bin;C:\Users\Taichi\AppData\Local\ti-build-cache\mambaforge\condabin;C:\Users\Taichi\AppData\Local\ti-build-cache\vulkan-1.3.236.0\Bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\Taichi\AppData\Local\ti-build-cache\vulkan-1.3.236.0\Bin;C:\VulkanSDK\1.3.246.1\Bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp;C:\VulkanSDK\1.3.239.0\Bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.1\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\Taichi\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\Taichi\AppData\Local\Programs\Python\Python310\;C:\Users\Taichi\AppData\Local\Microsoft\WindowsApps;C:\Users\Taichi\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\CMake\bin;C:\Users\Taichi\taichi\python\taichi\_lib
PYTHONPATH: ['C:\\Users\\Taichi\\AppData\\Local\\ti-build-cache\\mambaforge\\envs\\3.10\\Scripts', 'C:\\Users\\Taichi\\AppData\\Local\\ti-build-cache\\mambaforge\\envs\\3.10\\python310.zip', 'C:\\Users\\Taichi\\AppData\\Local\\ti-build-cache\\mambaforge\\envs\\3.10\\DLLs', 'C:\\Users\\Taichi\\AppData\\Local\\ti-build-cache\\mambaforge\\envs\\3.10\\lib', 'C:\\Users\\Taichi\\AppData\\Local\\ti-build-cache\\mambaforge\\envs\\3.10', 'C:\\Users\\Taichi\\AppData\\Local\\ti-build-cache\\mambaforge\\envs\\3.10\\lib\\site-packages', 'c:\\users\\taichi\\taichi\\python']

`lsb_release` not available: [WinError 2] The system cannot find the file specified

import: <module 'taichi' from 'c:\\users\\taichi\\taichi\\python\\taichi\\__init__.py'>

cpu: True
metal: False
opengl: True
cuda: True
vulkan: True

`glewinfo` not available: [WinError 2] The system cannot find the file specified

Mon Jun  5 16:33:17 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.79       Driver Version: 528.79       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8     5W / 115W |     62MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1684    C+G   ...dows\System32\LogonUI.exe    N/A      |
|    0   N/A  N/A      1692    C+G   C:\Windows\System32\dwm.exe     N/A      |
|    0   N/A  N/A      2644    C+G   ...823.37\msedgewebview2.exe    N/A      |
|    0   N/A  N/A      5760    C+G   ...wekyb3d8bbwe\Video.UI.exe    N/A      |
|    0   N/A  N/A      8464    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      9308    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      9728    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     11032    C+G   ...8wekyb3d8bbwe\GameBar.exe    N/A      |
+-----------------------------------------------------------------------------+

[Taichi] version 1.7.0, llvm 15.0.1, commit 3660ac8a, win, python 3.10.11

[Taichi] version 1.7.0, llvm 15.0.1, commit 3660ac8a, win, python 3.10.11
[Taichi] Starting on arch=x64

[Taichi] version 1.7.0, llvm 15.0.1, commit 3660ac8a, win, python 3.10.11
[Taichi] Starting on arch=opengl

[Taichi] version 1.7.0, llvm 15.0.1, commit 3660ac8a, win, python 3.10.11
[Taichi] Starting on arch=cuda

[Taichi] version 1.7.0, llvm 15.0.1, commit 3660ac8a, win, python 3.10.11

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi-lang.org/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/

                                TAICHI EXAMPLES
+-----------------------------------------------------------------------------+
| 0: ad_gravity           | 25:                     | 50: patterns            |
|                         | karman_vortex_street    |                         |
| 1: circle_packing_image | 26: keyboard            | 51: pbf2d               |
| 2: comet                | 27: laplace             | 52: physarum            |
| 3: cornell_box          | 28: laplace_equation    | 53:                     |
|                         |                         | poisson_disk_sampling   |
| 4: diff_sph             | 29: mandelbrot_zoom     | 54: print_offset        |
| 5:                      | 30: marching_squares    | 55: rasterizer          |
| differential_evolution  |                         |                         |
| 6: euler                | 31: mass_spring_3d_ggui | 56: regression          |
| 7: eulerfluid2d         | 32: mass_spring_game    | 57: sdf_renderer        |
| 8: explicit_activation  | 33:                     | 58: simple_derivative   |
|                         | mass_spring_game_ggui   |                         |
| 9: export_mesh          | 34: mciso_advanced      | 59: simple_texture      |
| 10: export_ply          | 35: mgpcg               | 60: simple_uv           |
| 11: export_videos       | 36: mgpcg_advanced      | 61: snow_phaseField     |
| 12: fem128              | 37: minimal             | 62: stable_fluid        |
| 13: fem128_ggui         | 38: minimization        | 63: stable_fluid_ggui   |
| 14: fem99               | 39: mpm128              | 64: stable_fluid_graph  |
| 15: fractal             | 40: mpm128_ggui         | 65: taichi_bitmasked    |
| 16: fractal3d_ggui      | 41: mpm3d               | 66: taichi_dynamic      |
| 17: fullscreen          | 42: mpm3d_ggui          | 67: taichi_logo         |
| 18: game_of_life        | 43: mpm88               | 68: taichi_ngp          |
| 19: gui_image_io        | 44: mpm88_graph         | 69: taichi_sparse       |
| 20: gui_widgets         | 45: mpm99               | 70: texture_graph       |
| 21: implicit_fem        | 46:                     | 71: tutorial            |
|                         | mpm_lagrangian_forces   |                         |
| 22:                     | 47: nbody               | 72:                     |
| implicit_mass_spring    |                         | two_stream_instability  |
| 23:                     | 48: odop_solar          | 73: vortex_rings        |
| initial_value_problem   |                         |                         |
| 24: jacobian            | 49: oit_renderer        | 74: waterwave           |
+-----------------------------------------------------------------------------+
42
Running example minimal ...
[Taichi] Starting on arch=x64
42.0
>>> Running time: 0.27s

Consider attaching this log when maintainers ask about system information.
>>> Running time: 6.81s

**Comment by bobcao3** [comment]
If you run `python -m taichi`, does it work?

**Comment by bobcao3** [comment]
I would guess if you use `python build.py --shell` then you would need to enter this shell every time? I'm not sure about this tho

@feisuzhu

**Comment by ailzhang** [comment]
cc: @feisuzhu

**Comment by feisuzhu** [comment]
@sarahhaha 

You have to use taichi package and its commands in the build shell.
There is a conda environment activated for you in the build shell, everything related to python (package install/remove) happens in the conda environment to avoid messing with your default python installation.

You can always enter the same conda environment by running `python build.py --shell` with the same version of python interpreter.

If you want to use the built Taichi in your own python installation, please use `python build.py` (without the `--shell` part) to build a wheel file and run `pip install dist/taichi-xxx.whl` in plain cmd shell to install in your own Python environment.
