### ISSUE TITLE
solver.info() is not supported.

### ISSUE THREAD

**Issue by tianlajiangjun** [taichi-dev/taichi#8199]
**Describe the bug**
by following the blog (https://mp.weixin.qq.com/s/BrgY5U4WBjqPo1smf4DkbA) of ti.linalg.SparseSolver in ti.cuda,we installed cuda v12.1 and ran the code successfully by renaming cusolver64_11.dll to cusolver64_12.dll.But solver.info() is not supported.

**To Reproduce**
we use the sample code in the blog:

```py
import taichi as ti
arch = ti.cuda # or ti.cuda
ti.init(arch=arch)

n = 4
# 第一步：构建 SparseMatrixBuilder
K = ti.linalg.SparseMatrixBuilder(n, n, max_num_triplets=4, dtype=ti.f32)

@ti.kernel
def fill(A: ti.types.sparse_matrix_builder()):
    for i in range(n):
        A[i, i] += 2.0  # 构建中只能使用 += 和 -=
# 第二步：填充非零元素
fill(K)
# 第三步：用构建器构建矩阵
A = K.build()
print(">>>> A = K.build()")
print(A)

b = ti.ndarray(ti.f32, shape=n)
@ti.kernel
def fill_b(b:ti.types.ndarray()):
    for i in range(n):
        b[i] += 1.0
fill_b(b)
print(b.to_numpy())


# 第四步：分析并分解系数矩阵
solver = ti.linalg.SparseSolver(solver_type="LLT", dtype=ti.f32)
solver.analyze_pattern(A)
solver.factorize(A)
x = solver.solve(b)
success = solver.info() # 获知求解成功与否
print(success)
print(x.to_numpy())
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
[Taichi] version 1.6.0, llvm 15.0.1, commit f1c6fbbd, win, python 3.8.13
[Taichi] Starting on arch=cuda
>>>> A = K.build()
[2, 0, 0, 0]
[0, 2, 0, 0]
[0, 0, 2, 0]
[0, 0, 0, 2]
[1. 1. 1. 1.]
[E 06/16/23 23:10:28.486 19356] [sparse_solver.h:taichi::lang::CuSparseSolver::info@122] Not supported.


Traceback (most recent call last):
  File "c:/Users/Administrator/Desktop/implic_fem/sparseSolver.py", line 40, in <module>        
    success = solver.info() # 获知求解成功与否
  File "D:\Anaconda\envs\taichi\lib\site-packages\taichi\linalg\sparse_solver.py", line 115, in info
    return self.solver.info()
RuntimeError: [sparse_solver.h:taichi::lang::CuSparseSolver::info@122] Not supported.
...
```

**Comment by ailzhang** [comment]
cc: @houkensjtu ?
