### ISSUE TITLE
Why TaiChi can't recognize subscript operation of 'taichi.lang.matrix.Vector'

### ISSUE THREAD

**Issue by Ives0721** [taichi-dev/taichi#8349]
## Problem code

In the code below, TaiChi will throw a IndexError about the index of `w`.

```python
import taichi as ti
ti.init(arch=ti.cpu)

w = ti.types.vector(9, float)([4/9, 1/9, 1/9, 1/9, 1/9, 1/36, 1/36, 1/36, 1/36])

@ti.data_oriented
class TestCls:
    def __init__(self, Nx: int, Ny: int, omega: float=1.0):
        # parameters to define a lattice
        self.Nx = Nx
        self.Ny = Ny

        self.feq = ti.Vector.field(9, float, shape=(Nx, Ny))
        self.rho = ti.field(float, shape=(Nx, Ny))

    @ti.kernel
    def initialize(self):
        rho, feq = ti.static(self.rho, self.feq)
        for x, y in ti.ndrange(self.Nx, self.Ny):
            for q in ti.ndrange((0, 9)):
                feq[x, y][q] = w[q] * rho[x, y]


test_obj = TestCls(5, 5)
test_obj.initialize()
```

PowerShell output looks like this

```
[Taichi] version 1.6.0, llvm 15.0.1, commit f1c6fbbd, win, python 3.9.16
[Taichi] Starting on arch=x64
<class 'taichi.lang.matrix.Vector'>
Traceback (most recent call last):
  File "d:\Codes\CorpRepo\LBDEM-TaiChi\try_ti.py", line 29, in <module>
    test_obj.initialize()
  File "D:\ProgramData\PyEnv\SCI\lib\site-packages\taichi\lang\kernel_impl.py", line 1035, in __call__
    raise type(e)("\n" + str(e)) from None
taichi.lang.exception.TaichiCompilationError:
File "d:\Codes\CorpRepo\LBDEM-TaiChi\try_ti.py", line 25, in initialize:
                feq[x, y][q] = w[q] * rho[x, y]
                               ^^^^
Traceback (most recent call last):
  File "D:\ProgramData\PyEnv\SCI\lib\site-packages\taichi\lang\ast\ast_transformer_utils.py", line 27, in __call__  
    return method(ctx, node)
  File "D:\ProgramData\PyEnv\SCI\lib\site-packages\taichi\lang\ast\ast_transformer.py", line 233, in build_Subscript
    node.ptr = impl.subscript(ctx.ast_builder, node.value.ptr, *node.slice.ptr)
  File "D:\ProgramData\PyEnv\SCI\lib\site-packages\taichi\lang\util.py", line 312, in wrapped
    return func(*args, **kwargs)
  File "D:\ProgramData\PyEnv\SCI\lib\site-packages\taichi\lang\impl.py", line 194, in subscript
    return value.__getitem__(_indices)
  File "D:\ProgramData\PyEnv\SCI\lib\site-packages\taichi\lang\matrix.py", line 320, in __getitem__
    entry = self._get_entry(indices)
  File "D:\ProgramData\PyEnv\SCI\lib\site-packages\taichi\lang\matrix.py", line 352, in _get_entry
    return self.entries[indices[0]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

## A way to avoid this

But when I change the definition of `w` into this, then everything works well.

```python
import numpy as np

w = ti.field(float, shape=(9,))
w.from_numpy(
    np.array([4/9, 1/9, 1/9, 1/9, 1/9, 1/36, 1/36, 1/36, 1/36])
)
```

## Question

How to pass the `w` defined by `ti.types.vector(9, float)` to the `@ti.kernel` without use `w` as input argument?

**Comment by jim19930609** [comment]
I was able to run the code with Taichi built with latest commit. Can you try installing the nightly build and see if this issue have already been resolved?

`pip install -i https://pypi.taichi.graphics/simple/ taichi-nightly`

**Comment by Ives0721** [comment]
> I was able to run the code with Taichi built with latest commit. Can you try installing the nightly build and see if this issue have already been resolved?
> 
> `pip install -i https://pypi.taichi.graphics/simple/ taichi-nightly`

Thanks. That's OK.
