### ISSUE TITLE
Taichi crashes when using break in kernel

### ISSUE THREAD

**Issue by feisuzhu** [taichi-dev/taichi#8351]
**Describe the bug**
It crashes

**To Reproduce**
```python
import taichi as ti
import numpy as np
ti.init(ti.cpu)

@ti.kernel
def bar(src: ti.types.ndarray(dtype=ti.u8)) -> ti.i32:
    for _ in range(1):
        for i in src:
            if i > 3:
                break
    return 233


foo = np.empty(100, dtype=np.uint8)
bar(foo)
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
(base) [work] ☁  ~  python test.py
[Taichi] version 1.7.0, llvm 15.0.4, commit aa0619fb, linux, python 3.10.6
[Taichi] Starting on arch=x64
[E 09/19/23 10:26:14.672 947338] [ir.h:as@248] Assertion failure: is<T>()


Traceback (most recent call last):
  File "/home/proton/test.py", line 15, in <module>
    bar(foo)
  File "/home/proton/miniforge3/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 1103, in wrapped
    return primal(*args, **kwargs)
  File "/home/proton/miniforge3/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 1035, in __call__
    return self.launch_kernel(kernel_cpp, *args)
  File "/home/proton/miniforge3/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 966, in launch_kernel
    raise e from None
  File "/home/proton/miniforge3/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 959, in launch_kernel
    compiled_kernel_data = prog.compile_kernel(prog.config(), prog.get_device_caps(), t_kernel)
RuntimeError: [ir.h:as@248] Assertion failure: is<T>()
```

**Comment by lin-hitonami** [comment]
`for i in src:` is a struct for loop, so it can only be used in the outermost loop. You can write like this if you want to iterate through a 1-d ndarray in inner for loops.
```
@ti.kernel
def bar(src: ti.types.ndarray(dtype=ti.u8)) -> ti.i32:
    ans = 0
    for _ in range(1):
        for i in range(src.shape[0]):
            ans += 1
            if i == 50:
                break
    return ans
```
