### ISSUE TITLE
[v1.7.0][Bug] Fix Quant Taichi error with "benchmark_advect"

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#8374]
# Reproduce
`cd quantaichi/eulerian_fluid/`
`python3 benchmark_advect.py`

# Log
```
[Taichi] version 1.7.0, llvm 15.0.4, commit fd46a563, linux, python 3.10.12
cmd args: Namespace(dim=2, res=512, debug=False, quant_all=False, quant_v=False, quant_dye=False, dye_type=0, no_gui=False, visualize=False, advect='mc', frames=100000, benchmark_id=0)
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File "/home/taichigraphics/workspace/TaichiRepos/Release/quantaichi/eulerian_fluid/benchmark_advect.py", line 164, in <module>
    solver.advect()
  File "/home/taichigraphics/workspace/TaichiRepos/Release/quantaichi/eulerian_fluid/benchmark_advect.py", line 118, in advect
    self.advection_op.advect(self.v, self.dye[0], self.dye[1], self.dye[2],
  File "/home/taichigraphics/workspace/TaichiRepos/Release/quantaichi/eulerian_fluid/advection.py", line 21, in advect
    self.advect_operator(*args)
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/lang/kernel_impl.py", line 1168, in __call__
    raise type(e)("\n" + str(e)) from None
taichi.lang.exception.TaichiTypeError: 
File "/home/taichigraphics/workspace/TaichiRepos/Release/quantaichi/eulerian_fluid/advection.py", line 82, in advect_mc:
                if not cond:
                ^^^^^^^^^^^^
`if` conditions must be an integer; found [Tensor (3) u1]. Consider using `if x != 0` instead of `if x` for float values.
```

**Comment by jim19930609** [comment]
Fix in: https://github.com/taichi-dev/quantaichi/pull/8
