### ISSUE TITLE
[v1.7.0][Bug] Fix Quant Taichi error with "demo.py"

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#8375]
# Reproduce
`cd quantaichi/eulerian_fluid/`
`python3 demo.py -d 3`

# Log
```
[Taichi] version 1.7.0, llvm 15.0.4, commit fd46a563, linux, python 3.10.12
cmd args: Namespace(dim=3, res=512, rk=3, advect='mc', debug=False, visualize=False, demo_id=0, quant_all=False, quant_v=False, quant_dye=False, dye_type=0, outdir=None, frames=10000)
[Taichi] Starting on arch=cuda
Level 0
  coarsened_grid_size 1024
  coarsened_offset (-512, -512, -512)

  sparse_grid_size 1040
  sparse_offset [-520, -520, -520]
Level 1
  coarsened_grid_size 512
  coarsened_offset [-256, -256, -256]

  sparse_grid_size 528
  sparse_offset [-264, -264, -264]
Level 2
  coarsened_grid_size 256
  coarsened_offset [-128, -128, -128]

  sparse_grid_size 272
  sparse_offset [-136, -136, -136]
[E 10/24/23 16:47:20.106 4075307] [cuda_driver.h:operator()@92] CUDA Error CUDA_ERROR_OUT_OF_MEMORY: out of memory while calling malloc (cuMemAlloc_v2)


Traceback (most recent call last):
  File "/home/taichigraphics/workspace/TaichiRepos/Release/quantaichi/eulerian_fluid/demo.py", line 100, in <module>
    solver = FluidSolver(
  File "/home/taichigraphics/workspace/TaichiRepos/Release/quantaichi/eulerian_fluid/solver.py", line 231, in __init__
    self.set_custom_source(res=640)
  File "/home/taichigraphics/workspace/TaichiRepos/Release/quantaichi/eulerian_fluid/solver.py", line 577, in set_custom_source
    self.set_custom_source_helper(self.dye[0].field, self.density_source[k],
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/lang/kernel_impl.py", line 1164, in __call__
    return self._primal(self._kernel_owner, *args, **kwargs)
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/lang/kernel_impl.py", line 1033, in __call__
    key = self.ensure_compiled(*args)
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/lang/kernel_impl.py", line 1001, in ensure_compiled
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/lang/kernel_impl.py", line 637, in materialize
    self.runtime.materialize()
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/lang/impl.py", line 471, in materialize
    self.materialize_root_fb(not self.materialized)
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/lang/impl.py", line 406, in materialize_root_fb
    root.finalize(raise_warning=not is_first_call)
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/_snode/fields_builder.py", line 170, in finalize
    return self._finalize(raise_warning, compile_only=False)
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/_snode/fields_builder.py", line 182, in _finalize
    return SNodeTree(_ti_core.finalize_snode_tree(_snode_registry, self.ptr, impl.get_runtime().prog, compile_only))
RuntimeError: [cuda_driver.h:operator()@92] CUDA Error CUDA_ERROR_OUT_OF_MEMORY: out of memory while calling malloc (cuMemAlloc_v2)

```

**Comment by lin-hitonami** [comment]
On my 3090 which has 24GB memory, it runs out of memory after the 65th iteration. I also tried it on taichi v1.5.0 and it perform the same as the master branch. Therefore it should be normal.
