### ISSUE TITLE
[v1.7.0][Bug] Fix Diff Taichi error with "diffmpm_benchmark.py"

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#8376]
# Reproduce
`cd difftaichi/examples`
`python3 diffmpm_benchmark.py`

# Log
```
python3 diffmpm_benchmark.py
[Taichi] version 1.7.0, llvm 15.0.4, commit fd46a563, linux, python 3.10.12
[Taichi] Starting on arch=cuda
Also check "nvprof --print-gpu-trace python3 diffmpm_benchmark.py" for more accurate results
Traceback (most recent call last):
  File "/home/taichigraphics/workspace/TaichiRepos/Release/difftaichi/examples/diffmpm_benchmark.py", line 304, in <module>
    main()
  File "/home/taichigraphics/workspace/TaichiRepos/Release/difftaichi/examples/diffmpm_benchmark.py", line 246, in main
    benchmark()
  File "/home/taichigraphics/workspace/TaichiRepos/Release/difftaichi/examples/diffmpm_benchmark.py", line 203, in benchmark
    ti.clear_kernel_profile_info()
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/__init__.py", line 23, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'clear_kernel_profile_info'
```

**Comment by jim19930609** [comment]
Fix in: https://github.com/taichi-dev/difftaichi/pull/68
