### ISSUE TITLE
[v1.7.0][Bug] Fix Diff Taichi error with "liquid.py"

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#8377]
# Reproduce
`cd difftaichi/examples`
`python3 diffmpm_benchmark.py`

# Log
```
[Taichi] version 1.7.0, llvm 15.0.4, commit fd46a563, linux, python 3.10.12
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File "/home/taichigraphics/workspace/TaichiRepos/Release/difftaichi/examples/liquid.py", line 387, in <module>
    def copy_back_and_clear(img: ti.ext_arr()):
  File "/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/__init__.py", line 23, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'ext_arr'
```

**Comment by jim19930609** [comment]
Fix in: https://github.com/taichi-dev/difftaichi/pull/68
