### ISSUE TITLE
[v1.7.0][Bug] Fix error with SandyFluid

### ISSUE THREAD

**Issue by jim19930609** [taichi-dev/taichi#8382]
# Reproduce
`cd SandyFluid`
`python3 src/main.py`

# Log
```
[Taichi] version 1.7.0, llvm 15.0.4, commit fd46a563, linux, python 3.10.12
[Taichi] Starting on arch=cuda
[W 10/24/23 18:03:45.101 4114418] 
Assign may lose precision: unknown <- i32
39936
/home/taichigraphics/workspace/TaichiRepos/Release/taichi/python/taichi/ui/scene.py:443: DeprecationWarning: Instantiating ti.ui.Scene directly is deprecated, use the get_scene() function from a taichi.ui.Window object instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/taichigraphics/workspace/TaichiRepos/Release/SandyFluid/src/main.py", line 17, in <module>
    gui = SimulationGUI(sim, output_img=OUTPUT)
  File "/home/taichigraphics/workspace/TaichiRepos/Release/SandyFluid/src/gui.py", line 27, in __init__
    self.camera = ti.ui.make_camera()
AttributeError: module 'taichi.ui.ui' has no attribute 'make_camera'
```

**Comment by jim19930609** [comment]
Fixed by https://github.com/taichi-dev/taichi/pull/8397
