### ISSUE TITLE
Segmentation fault on kernel.grad

### ISSUE THREAD

**Issue by oliver-batchelor** [taichi-dev/taichi#8442]
Simplified script below runs the forward pass fine, backward pass causes segmentation fault.

```
python spherical_harmoics.py

[Taichi] version 1.7.0, llvm 15.0.4, commit 59156b3c, linux, python 3.10.0
[Taichi] Starting on arch=x64
True
[E 12/21/23 19:33:09.236 3705923] Received signal 11 (Segmentation fault)


***********************************
* Taichi Compiler Stack Traceback *
***********************************
/local/mambaforge/envs/torch/lib/python3.10/site-packages/taichi/_lib/core/taichi_python.cpython-310-x86_64-linux-gnu.so(+0x4805a34) [0x7fc9486b0a34]
/local/mambaforge/envs/torch/lib/python3.10/site-packages/taichi/_lib/core/taichi_python.cpython-310-x86_64-linux-gnu.so(+0x1b3618e) [0x7fc9459e118e]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fc958bd0520]
[0x7fc9436c5372]

```

```
from functools import cache
import math
from beartype import beartype
import taichi as ti
from taichi.math import vec3
import torch

# Derived from torch-spherical-harmonics
# https://github.com/cheind/torch-spherical-harmonics

vec9f = ti.types.vector(9, ti.float32)


@ti.func
def rsh_cart_2(xyz: vec3) -> vec9f:
    x, y, z = xyz

    x2 = x**2
    y2 = y**2
    z2 = z**2
    xy = x * y
    xz = x * z
    yz = y * z

    return vec9f(
        0.282094791773878,
        -0.48860251190292 * y,
        0.48860251190292 * z,
        -0.48860251190292 * x,
        1.09254843059208 * xy,
        -1.09254843059208 * yz,
        0.94617469575756 * z2 - 0.31539156525252,
        -1.09254843059208 * xz,
        0.54627421529604 * x2 - 0.54627421529604 * y2
    )



def check_sh_degree(sh_features):
  n_sh = sh_features.shape[1]
  n = int(math.sqrt(n_sh))

  assert n * n == n_sh, f"SH feature count must be square, got {n_sh} ({sh_features.shape})"
  return (n - 1)


param_vec = ti.types.vector(9, dtype=ti.f32)


@ti.kernel    
def evaluate_sh_kernel(params:ti.types.ndarray(param_vec, ndim=1), 
    dirs:ti.types.ndarray(vec3, ndim=1), out:ti.types.ndarray(ti.f32, ndim=1)):
    
  for i in range(params.shape[0]):
      coeffs = rsh_cart_2(dirs[i])

      out[i] = coeffs.dot(params[i])



class _module_function(torch.autograd.Function):
  @staticmethod
  def forward(ctx, params:torch.Tensor, dirs:torch.Tensor) -> torch.Tensor:
      
      degree = check_sh_degree(params)
      ctx.kernel = evaluate_sh_kernel

      out = torch.zeros(dirs.shape[0], dtype=torch.float32, device=params.device)
      ctx.kernel(params, dirs, out)

      ctx.save_for_backward(params, dirs, out)
      return out

  @staticmethod
  def backward(ctx, doutput):
      params, dirs, out = ctx.saved_tensors
      out.grad = doutput

      ctx.kernel.grad(params, dirs, out)
      return params.grad, dirs.grad



@beartype
def evaluate_sh(params:torch.Tensor,  # N, K (degree + 1)^2,  (usually K=3, for RGB)
                dirs:torch.Tensor     # N, 3
                ) -> torch.Tensor:    # N, K
    
    return _module_function.apply(params.contiguous(), dirs.contiguous())


if __name__ == '__main__':
    ti.init(debug=True)

    degree = 2

    device = torch.device('cuda:0')
    params = torch.rand(100, (degree + 1)**2, dtype=torch.float32, device=device).requires_grad_(True)
    dirs = torch.rand(100, 3, dtype=torch.float32, device=device).contiguous()

    out = evaluate_sh(params, dirs)
    print(out.requires_grad)

    x = out.sum()
    x.backward()
```

**Comment by oliver-batchelor** [comment]
A longer version of this code (before simplification) gives a different assertion...



```
Internal error occurred. Check out this page for possible solutions:
https://docs.taichi-lang.org/docs/install
Traceback (most recent call last):
  File "/csse/users/owb14/sync/taichi_gaussian_rasterizer/gaussian_rasterizer/spherical_harmoics.py", line 168, in <module>
    x.backward()
  File "/local/mambaforge/envs/torch/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/local/mambaforge/envs/torch/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/local/mambaforge/envs/torch/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/csse/users/owb14/sync/taichi_gaussian_rasterizer/gaussian_rasterizer/spherical_harmoics.py", line 141, in backward
    ctx.kernel.grad(params, dirs, out)
  File "/local/mambaforge/envs/torch/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 1035, in __call__
    return self.launch_kernel(kernel_cpp, *args)
  File "/local/mambaforge/envs/torch/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 966, in launch_kernel
    raise e from None
  File "/local/mambaforge/envs/torch/lib/python3.10/site-packages/taichi/lang/kernel_impl.py", line 959, in launch_kernel
    compiled_kernel_data = prog.compile_kernel(prog.config(), prog.get_device_caps(), t_kernel)
RuntimeError: [type_check.cpp:visit@547] Assertion failure: stmt->ret_type == stmt->v->ret_type
```

```


from functools import cache
import math
from beartype import beartype
import taichi as ti
from taichi.math import vec3
import torch

# Derived from torch-spherical-harmonics
# https://github.com/cheind/torch-spherical-harmonics


vec16f = ti.types.vector(16, ti.float32)
vec9f = ti.types.vector(9, ti.float32)
vec4f = ti.types.vector(4, ti.float32)
vec1f = ti.types.vector(1, ti.float32)

@ti.func
def rsh_cart_0(xyz: vec3) -> vec1f:
    return vec9f(
        0.282094791773878
    )


@ti.func
def rsh_cart_1(xyz: vec3) -> vec9f:
    x, y, z = xyz
    return vec9f(
        0.282094791773878,
        -0.48860251190292 * y,
        0.48860251190292 * z,
        -0.48860251190292 * x,
    )

@ti.func
def rsh_cart_2(xyz: vec3) -> vec9f:
    x, y, z = xyz

    x2 = x**2
    y2 = y**2
    z2 = z**2
    xy = x * y
    xz = x * z
    yz = y * z

    return vec9f(
        0.282094791773878,
        -0.48860251190292 * y,
        0.48860251190292 * z,
        -0.48860251190292 * x,
        1.09254843059208 * xy,
        -1.09254843059208 * yz,
        0.94617469575756 * z2 - 0.31539156525252,
        -1.09254843059208 * xz,
        0.54627421529604 * x2 - 0.54627421529604 * y2,
    )

@ti.func
def rsh_cart_3(xyz: vec3) -> vec16f:
    x, y, z = xyz.x, xyz.y, xyz.z

    x2 = x**2
    y2 = y**2
    z2 = z**2
    xy = x * y
    xz = x * z
    yz = y * z

    return vec16f(
        0.282094791773878,
        -0.48860251190292 * y,
        0.48860251190292 * z,
        -0.48860251190292 * x,
        1.09254843059208 * xy,
        -1.09254843059208 * yz,
        0.94617469575756 * z2 - 0.31539156525252,
        -1.09254843059208 * xz,
        0.54627421529604 * x2 - 0.54627421529604 * y2,
        -0.590043589926644 * y * (3.0 * x2 - y2),
        2.89061144264055 * xy * z,
        0.304697199642977 * y * (1.5 - 7.5 * z2),
        1.24392110863372 * z * (1.5 * z2 - 0.5) - 0.497568443453487 * z,
        0.304697199642977 * x * (1.5 - 7.5 * z2),
        1.44530572132028 * z * (x2 - y2),
        -0.590043589926644 * x * (x2 - 3.0 * y2),
    )        


def check_sh_degree(sh_features):
  n_sh = sh_features.shape[2]
  n = int(math.sqrt(n_sh))

  assert n * n == n_sh, f"SH feature count must be square, got {n_sh} ({sh_features.shape})"
  return (n - 1)


@cache
def evaluate_sh_kernel(degree:int, dimension:int=3):
  assert degree >= 0 and degree <= 3

  rsh_cart_n = [rsh_cart_0, rsh_cart_1, rsh_cart_2, rsh_cart_3]
  rsh_cart = rsh_cart_n[degree]

  param_mat = ti.types.matrix(n=dimension, m=(degree + 1)**2, dtype=ti.f32)
  vec = ti.types.vector(n=dimension, dtype=ti.f32)


  @ti.kernel    
  def _evaluate_sh3_kernel(params:ti.types.ndarray(param_mat, ndim=1), 
                          dirs:ti.types.ndarray(vec3, ndim=1), 
                          out:ti.types.ndarray(vec, ndim=1)):
      
      for i in range(params.shape[0]):
          coeffs = rsh_cart(dirs[i])
          params_i = params[i]


          for d in range(dimension):
              out[i][d] = coeffs.dot(params_i[d, :])

  return _evaluate_sh3_kernel


class _module_function(torch.autograd.Function):
  @staticmethod
  def forward(ctx, params:torch.Tensor, dirs:torch.Tensor) -> torch.Tensor:
      
      degree = check_sh_degree(params)
      ctx.kernel = evaluate_sh_kernel(degree, params.shape[1])

      out = torch.zeros(dirs.shape[0], params.shape[1], dtype=torch.float32, device=params.device)
      ctx.kernel(params, dirs, out)

      ctx.save_for_backward(params, dirs, out)
      return out

  @staticmethod
  def backward(ctx, doutput):
      params, dirs, out = ctx.saved_tensors
      out.grad = doutput

      ctx.kernel.grad(params, dirs, out)
      return params.grad, dirs.grad



@beartype
def evaluate_sh(params:torch.Tensor,  # N, K (degree + 1)^2,  (usually K=3, for RGB)
                dirs:torch.Tensor     # N, 3
                ) -> torch.Tensor:    # N, K
    
    return _module_function.apply(params.contiguous(), dirs.contiguous())



if __name__ == '__main__':
    ti.init(debug=True)

    degree = 3
    dimension = 5

    params = torch.rand(100, dimension, (degree + 1)**2).requires_grad_(True)
    dirs = torch.rand(100, 3)

    out = evaluate_sh(params, dirs)
    print(out.shape)

    x = out.sum()
    x.backward()

    
    
```
